### ISSUE TITLE
NATS: proposal to change/augment spec to use message headers

### ISSUE THREAD

**Issue by bruth** [cloudevents/spec#1006]
As of [NATS 2.2](https://docs.nats.io/release-notes/whats_new/whats_new_22#message-headers) message headers have been supported (NATS is currently 2.8.2 for reference).

This issue is to propose change the protocol binding to put all fields into the header and have the `data` map to the message payload exclusively. This would remove the need of the JSON-encoded representation for all of the event attributes.

If this is a welcome change, I am happy to open a PR to change the document. Note these are not mutually exclusive, so for NATS servers that pre-date v2.2.x, the JSON encoded representation could still be maintained.

**Comment by duglin** [comment]
@derekcollison thoughts?

**Comment by derekcollison** [comment]
I think both options should be available. Be great to have header support for those who prefer binary payloads.

**Comment by bruth** [comment]
@duglin I can augment the current document with the header-based alternative and highlight the two options. Does that work for you?

**Comment by duglin** [comment]
@bruth yup!  Just ping @derekcollison when you submit the PR so he can review it as he's our expert in that space
