### ISSUE TITLE
Support CDATA as body type for 'data' element

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#1013]
### Discussed in https://github.com/cloudevents/spec/discussions/1011

<div type='discussions-op-text'>

<sup>Originally posted by **JimWeier-VeteransUnited** May  9, 2022</sup>
Data should be able to contain a CDATA string in the element named data </div>

**Comment by duglin** [comment]
@JemDay

**Comment by JemDay** [comment]
I think this should be doable ... this might mean we change such that "text" is always transferred as CDATA as opposed to an s:string, or we support both and leave it up to the SDKs to switch between the two styles - that has the potential for adding complexity into all of the SDKs though - @jskeet ??

**Comment by jskeet** [comment]
Hmm.... will have to look into it in more detail. I'm not even sure whether we need to explicitly say anything here, or whether it just drops out. Fundamentally I need to get my head back into the XML CloudEvents space - including updating my C# SDK prototype...

**Comment by duglin** [comment]
@JemDay @jskeet any update on this one?

**Comment by duglin** [comment]
per 1/19 call - @JemDay to PR it

**Comment by jskeet** [comment]
//remove-lifecycle stale
