### ISSUE TITLE
Flatbuffers Event Format

### ISSUE THREAD

**Issue by stevenhartley** [cloudevents/spec#1019]
Any thought for supporting Flatbuffers Cloudevent format (IOW, defining the CloudEvent using Flatbuffers IDL)?

**Comment by duglin** [comment]
Haven't heard about it, but a PR is always welcome :-)

**Comment by duglin** [comment]
Going to close this since there's no action to take on it.... but as I said, if someone is interested in creating a PR for it then we'd welcome to addition.
