### ISSUE TITLE
[Docs] Translate spec/cloudevents/languages/zh-CN/RELEASE_NOTES to zh-CN.md

### ISSUE THREAD

**Issue by VedaGao** [cloudevents/spec#1027]
Document to translate:

https://github.com/cloudevents/spec/blob/main/cloudevents/RELEASE_NOTES.md

Translation target:

https://github.com/cloudevents/spec/blob/main/cloudevents/languages/zh-CN/RELEASE_NOTES.md

Translators who accept the task SHOULD follow [instructions for CloudEvents translation](https://github.com/cloudevents/spec/blob/main/languages/languages-spec.md).

**Comment by VedaGao** [comment]
Plz assign this to me. thanks a lot.

**Comment by duglin** [comment]
I believe we can close this due to #1028. Please let me know if we need to reopen.
