### ISSUE TITLE
schemaregistry: Inconsistencies between 3. HTTP ("REST") API and 2. Schema Registry Elements

### ISSUE THREAD

**Issue by nielspardon** [cloudevents/spec#1036]
Following the operations described for the HTTP REST API in section 3 there are the following inconsistencies:

1. Creating an individual `Schema` is not supported by the described API. One can only create a new `Schema Version` [3.3.3. Add a new schema version](https://github.com/cloudevents/spec/blob/6cd09e5e210d7b04e0eda585c0c59fd1d5980ad2/schemaregistry/spec.md#333-add-a-new-schema-version).
    - That means there is no mechanism to provide any of the additional attributes for a `Schema` like `description`, `authority`, `format`, `createdtimeutc`, `updatedtimeutc` except the `id` attribute since this is a path parameter.
4. Let's assume one would add an API for creating a `Schema`:
    - There is no mechanism to retrieve any of the additional attributes since `Schemas` are only retrievable as a list of ids [3.3.1. List schemas for the group](https://github.com/cloudevents/spec/blob/6cd09e5e210d7b04e0eda585c0c59fd1d5980ad2/schemaregistry/spec.md#331-list-schemas-for-the-group).
    - There would be a collision of the `description` and for the `createdtimeutc` attributes for a `Schema` with the `description` and `createdtimeutc` attributes of a `Schema Version` when calling [3.3.4. Get the latest version of a schema](https://github.com/cloudevents/spec/blob/6cd09e5e210d7b04e0eda585c0c59fd1d5980ad2/schemaregistry/spec.md#334-get-the-latest-version-of-a-schema).
    - Assuming one would not provide an update `Schema` API, the semantic for `updatedtimeutc` of a `Schema` would be effectively the `createdtimeutc` of the latest `Schema Version` since that would be the only entity that could be updated.

**Comment by duglin** [comment]
ping @clemensv. I think this is related to some chats we've had recently about how to deal with the extra metadata associated with a schema doc.

**Comment by duglin** [comment]
I believe the latest Registry spec: https://github.com/cloudevents/spec/blob/main/registry/spec.md deals with this issue. @nielspardon would you agree? If so we can close this issue. If not, let me know which bits are still pending.

**Comment by duglin** [comment]
Moved to: https://github.com/xregistry/spec/issues/11
