### ISSUE TITLE
translation: cloudevents spec to hebrew

### ISSUE THREAD

**Issue by sasha-tkachev** [cloudevents/spec#1042]
I want to translate the CloudEvents spec to Hebrew. 

The issues I think I will encounter is RLT support from github

Never done this before but I think this will be cool experience

**Comment by duglin** [comment]
Sound interesting... looking forward to your PR ;-)

**Comment by sasha-tkachev** [comment]
@duglin I was right about the RTL support

I think I may need to write in html instead of markdown due to it 
see example here
https://github.com/sasha-tkachev/cloudevents-spec/blob/feature/hebrew-spec/cloudevents/languages/he/adapters/aws-s3.md

**Comment by sasha-tkachev** [comment]
oh, nevermind, seems it works fine without the div
