### ISSUE TITLE
spelling mistakes world in subscription spec

### ISSUE THREAD

**Issue by xdlbdy** [cloudevents/spec#1055]
Under the [Subscription Object config ](https://github.com/cloudevents/spec/blob/main/subscriptions/spec.md#config) section has a world of spelling mistakes
> When there is a Discovery `Enpoint` Service definition defined for the subscription manager, then the key MUST be one of the subscriptionconfig keys specified in the Discovery Endpoint Service definition

In the world of `Enpoint` spelling mistakes which lost a letter `d`, so the correct is `Endpoint`

**Comment by duglin** [comment]
Fixed by #1054

**Comment by duglin** [comment]
Thanks again for the fix/PR... in the future you don't need to an open issue if you don't want to. You can go straight to the PR if that's easier for you. We're not that formal :-)
