### ISSUE TITLE
[Registry] Feels like `channel` should be an array.

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#1062]
Feels like `channel` should be an array.

_Originally posted by @n3wscott in https://github.com/cloudevents/spec/pull/1041#discussion_r942655170_

**Comment by matzew** [comment]
Given one example being a `kafka streams` application:
- reading from a number of topics
- performing filtering via topics that are created on the fly
- writing results into different buckets/topics


I feel as well there is a need that a single `channel` string, for an "endpoint" is not enough. 

Ideally it is also a bit more structured, rather than a simple string (or array of simple strings)

**Comment by duglin** [comment]
@matzew can you give an example where a string isn't sufficient to uniquely differentiate one channel from another?
I kind of view it like an `ID` (e.g. UUID) and the matching algorithm is just a simple strcmp.

**Comment by matzew** [comment]
I wonder if some more sophisticated type is needed that allows proper navigation, for interoperability among providers?

**Comment by pierDipi** [comment]
@duglin 

This is an example:
- A Kafka topic A is registered to be a producer and consumer endpoint (with channel a)
- A Kafka topic B is registered to be a producer and consumer endpoint (with channel b)
- A Kafka topic C is registered to be a producer and consumer endpoint (with channel c)
- A Kafka consumer reads from topic A and topic B and produces to topic C, what is the channel of this endpoint?

**Comment by pierDipi** [comment]
wrt the channel being an unstructured string, I see this problem:

Given the above example, to register the Kafka subscriber endpoint, it needs to know which channel to use, and so it needs to navigate/search the registry before doing so.
Ideally, channel has a well know structure that would decouple the registration of related endpoints from each other.

**Comment by duglin** [comment]
> I wonder if some more sophisticated type is needed that allows proper navigation, for interoperability among providers?

Possibly but I'm trying to understand the use cases first and why a string isn't sufficient.  My head is stuck on equating this to a URL - some unique string that allows for people to be as precise as they need to be based on the domain. So, in a private env, perhaps a value of `department-123-queue` is sufficiently unique. But in a more public environment, perhaps it needs to be: `queues.bigCo.com/department-123-queue`

So, maybe saying it's a string is the issue, and we should say it needs to be something more like a relative-URI to imply that proper scoping is expected by the definer of this value.... perhaps?? I wouldn't want the scheme to be part of it though as that might make people think it's actually reachable, which will not be true in all cases. So, maybe a string with lots of text to make sure scoping is included??

**Comment by deissnerk** [comment]
I find this discussion about `channel` very interesting. Thanks everyone for bringing it up. 
I think a part of the confusion results from an unclear understanding of _endpoint_. 

@pierDipi To your example:
Let's ignore channel b for a while and focus on a and c. I would model it like this:
`channel a => consumer ep a=> producer ep client => message processing => consumer ep client => producer ep c => channel c`

It might look a bit strange in the beginning, but I think that, conceptually, both ends of a network communication should be regarded as _endpoints_, although I can't think of a use case where the discovery of a client would make sense. A _channel_ can be regarded as a special message processor that forwards messages either to a single consumer or to multiple consumers. 

As a consequence, I would not regard the consumer/producer between a and c as a channel.

**Comment by pierDipi** [comment]
Thanks for the comments @duglin and @deissnerk!

My use case started from the fact that I'd like to correlate endpoints in a many to many relationship to:
- show (logical) message processing topology views (like from the example above: producer/consumer endpoints for topic A and B are connected via some "unknown" (to the registry) message processor to endpoints for topic C),
- or notifying clients/teams connected to "downstream endpoints" for schema changes on "upstream endpoints"
- or correlating an HTTP/MQTT producer endpoint to a Kafka producer endpoint (like an HTTP/MQTT proxy for Kafka)

Maybe we were trying to fit these use cases in the channel construct but it seems we might need something else or evolve/clarify the channel description?

**Comment by deissnerk** [comment]
@pierDipi 
### message processing topology
This is indeed difficult with the current discovery concept, as it focuses on discovering endpoints that MAY BE used to produce to or consume from a certain channel. In my example above I explicitly added the clients' endpoints, although they are usually not discoverable. If we would make those client endpoints discoverable as well, we would be almost there. You could then discover clients that consume from a certain ep/channel. We don't have a standardized way to describe the entity an ep belongs to. In my description above `producer ep client` and `consumer ep client` would belong to the same unknown message processor. 

### notify downstream clients of schema changes
That should be possible, as the schemas have identifiers. Something, I'd like to see in the future is CloudEvents for the registry spec. With this in place you could subscribe to events about certain schemas. 
Propagating changes regarding the set of events that is available in a channel is more tricky, as it is not clear if an intermediary would always forward everything. Would your message processor simply take all events from a and b and forward them to c?

### HTTP/MQTT gateway for Kafka
If it is really just a proxy that forwards everything you could make it discoverable as another producer ep for the channel that backs the kafka topic. If, on the other hand it would do filtering or enriching, it would again be a message processor on its own. 

To effectively understand your topology I assume you need to incorporate some knowledge regarding the behavior of its nodes.

**Comment by duglin** [comment]
Moved to: https://github.com/xregistry/spec/issues/14
