### ISSUE TITLE
Based on definition of the content-type, we may just call it "encoding-format" to be more self explanatory

### ISSUE THREAD

**Issue by cathyhongzhang** [cloudevents/spec#107]
Assigned to: @cathyhongzhang

**Comment by cathyhongzhang** [comment]
You can assign this to me

**Comment by clemensv** [comment]
Introduced with MIME, Content-Type is a convention that is used in numerous protocols. "Encoding" is separate concept.

MIME (Email):
* Content-Type: https://tools.ietf.org/html/rfc2045#section-5 
* Content-Transfer-Encoding: https://tools.ietf.org/html/rfc2045#section-6 

HTTP:
* Content-Type: https://tools.ietf.org/html/rfc7231#section-3.1.1.5 
* Content-Encoding: https://tools.ietf.org/html/rfc7231#section-3.1.2.2 

AMQP:
* content-type/content-encoding: http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-properties  

MQTT: 
* ContentType: http://docs.oasis-open.org/mqtt/mqtt/v5.0/cs01/mqtt-v5.0-cs01.html#_Toc502667341 

It's not helpful to stray from that term if the semantics are the same and I do believe they are.

**Comment by yaronha** [comment]
agree w @clemensv
