### ISSUE TITLE
Prevent mixture of prefixes in AMQP?

### ISSUE THREAD

**Issue by jskeet** [cloudevents/spec#1070]
When considering the change in C# SDK due to #1050, it strikes me that there's a potential ambiguity about an AMQP message with a mixture of `cloudEvents:` and `cloudEvents_` prefixes.

Is it reasonable to mix and match? If not, we should prohibit it. If there's some reason why it could be useful, we should define correct behavior for a message with (say) `cloudEvents:id` and `cloudEvents_id` properties.

**Comment by duglin** [comment]
From Sept 1st call... most want consistency, no mixture within a CE

**Comment by duglin** [comment]
@jskeet any update on this one? Can we close it?

**Comment by jskeet** [comment]
I *believe* this was implemented in #1071. Check my logic, but then I think it's good to close.

**Comment by duglin** [comment]
Yep - agreed. Thanks. Closing
