### ISSUE TITLE
why are there not more bindings?

### ISSUE THREAD

**Issue by rvowles** [cloudevents/spec#1084]
Given the plethora of popular messaging systems out there that would seem to benefit CloudEvents to have a binding for, there seems to be a dearth of bindings? If I wanted to use Azure, I would probably use Azure ServiceBus, Google - Google Pub/Sub, Amazon - SNS/SQS, and there are others I have seen in various repositories being suggested. 

Is there a document somewhere that states the desire to keep the number limited or is it just that no-one has stepped forward to propose a protocol binding for these? If there is an answer to this question it would probably be worthwhile going into the README of this repo (once its answered, I'm happy to propose a PR to add it )

**Comment by rvowles** [comment]
In my hunting I have found a Google Pub/Sub one in a archived knative-gcp repo, and someone who has implemented a C# ServiceBus extension. I could see that including them in the official sdks and binding definitions might be considered out of scope, but would it be worthwhile to have a contrib repo(s)?

**Comment by duglin** [comment]
It's basically what you said... no one has stepped up to define the bindings. We welcome PRs! :-)
