### ISSUE TITLE
CloudEvent recipient context attribute

### ISSUE THREAD

**Issue by alexec** [cloudevents/spec#1089]
We have a use case where events have a specific recipient. This is used when an API conusmer has made an API request that requires an async response - aka "callback".

We'd like a standardized way to specify the recipient. I had this idea:

```json
{
  "specversion": "1.0",
  "source": "banking",
  "id": "abc123",
  "type": "banking.account.verified.v1",
  "to": "urn:service:xxx.yyy.zzz"
}
```

The contents of the recipient would be a URN specifying the recipient. 

Thoughts...
* Do we want to support CC and BCC headers (like email)?
* Do we want to be able to send this to just one service, or maybe many services? I.e can a callback also be an event notification? “E.g. `{“broadcast”: true}`.

**Comment by duglin** [comment]
Pretty sure @clemensv might have an opinion on this one 🙂

**Comment by alexec** [comment]
So this a binding level attribute. I could be written to Kafka headers, but should not be included in the CE.
