### ISSUE TITLE
Tracing: tampering

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#1092]
From our security audit folks... if someone tampers with the tracing headers during a multi-hop transmission, is that considered a security issue or just a requirement failure?

@joaopgrassi @clemensv

**Comment by joaopgrassi** [comment]
Hi @duglin !

I'm far from a security expert, but I think most of the things related to this topic can be found in the Trace Context W3C specification under [Security Considerations](https://www.w3.org/TR/trace-context/#security-considerations). There's also other concerns such as data privacy that you can also find on that page.

**Comment by duglin** [comment]
@joaopgrassi thanks for the reply. That doc doesn't directly address tampering or encrypting of things. Do you think that doc assumes that those concerns would be covered by just normal HTTP protection mechanisms, like using HTTPS instead of HTTP?

**Comment by dyladan** [comment]
Hello. I'm on the W3C working group which wrote the spec so maybe I can answer your questions.

>if someone tampers with the tracing headers during a multi-hop transmission, is that considered a security issue or just a requirement failure?

It could be considered either. When considering malicious disclosure or modification of the header values, the following things may happen:

### Trace Parent Disclosure

The IDs are specified to contain no personally identifiable or sensitive data. If the IDs are spec compliant the risk here is minimal.

### Trace Parent Modification

If the IDs are modified, the existing trace is certainly broken. If it is modified in such a way that it violates the expected format, it should be dropped by the tracing system, a new trace started, and your application will continue as normal with the new trace. If it is modified in a way that it keeps the expected format but an ID is changed, the application will continue as normal with the existing bad trace but your tracing system will receive "garbage data." Different tracing systems handle this in different ways, but it should not affect the end-user application. The absolute worst case scenario here is denial of tracing if your tracing backend handles this garbage data poorly. There should be little to no risk to the application itself.

### Trace State

The trace state values are not given any meaning by the specification. It is up to the tracing system reading and writing these values to ensure they are properly validating the format. This risks here are dependent on what data the tracing system puts into the tracestate, but again the spec states that it should not contain sensitive data. Further, all tracing systems should be expecting that it is possible their tracestate entry is entirely missing or misformatted.

**Comment by duglin** [comment]
@dyladan thanks - just to make sure I'm reading things correctly... you're basically saying that while bad things could happen on the receiving side due to bad/unexpected data, there shouldn't be any exposure of sensitive data and good coding should prevent data from causing bad semantics. Net: no security issue, it's more of a "write good code" concern.  Right?

**Comment by duglin** [comment]
Going to close this. If people think we need to reopen it please let us know.
