### ISSUE TITLE
sampledrate extension edge case

### ISSUE THREAD

**Issue by sasha-tkachev** [cloudevents/spec#1104]
It is not clear what to do when an intermediary which does event sampling receives an event which was sampled.

I think it MUST or at least SHOULD adjust the `sampledrate` value

**Comment by duglin** [comment]
I think at that point it's a new CloudEvent, so I agree it would have a new sampledrate value. Want to PR it? Unless people think this should be obvious already??

**Comment by duglin** [comment]
The default mental model I've had is that if a component modifies a CE then it should be a new CE. 

From Primer:
When an entity is acting as both a receiver and sender of CloudEvents for the purposes of forwarding, or transforming, the incoming event, the degree to which the outbound CloudEvent matches the inbound CloudEvent will vary based on the processing semantics of this entity. In cases where it is acting as proxy, where it is simply forwarding CloudEvents to another event consumer, then the outbound CloudEvent will typically look identical to the inbound CloudEvent with respect to the spec defined attributes - see previous paragraph concerning adding additional attributes.

However, if this entity is performing some type of semantic processing of the CloudEvent, typically resulting in a change to the value of the data attribute, then it may need to be considered a distinct "event source" from the original event source. And as such, it is expected that CloudEvents attributes related to the event producer (such as source and id) would be changed from the incoming CloudEvent.


--
Whether this change falls into the second category or if it's just a proxy is the question.

**Comment by duglin** [comment]
@sasha-tkachev is this still an issue?

**Comment by duglin** [comment]
@sasha-tkachev did you want to follow up on this one? I'm going to suggest we close it and we can re-open it if you find time to visit it.

**Comment by duglin** [comment]
Agreed on the 9/21 call to close this issue. If someone would like to reopen it and push it forward please let us know.
