### ISSUE TITLE
Encryption Extension

### ISSUE THREAD

**Issue by alexec** [cloudevents/spec#1113]
Split out from https://github.com/cloudevents/spec/issues/1093

All context attributes namespaced by `enc`:

* `encalg` the algorithm used to encrypt the Content Encryption Key, e.g. `RSA-OAEP`, e.g same as JWE
* `enc` the algorithm, e.g. `A128CBC-HS256`, e.g same as JWE
* `enckid` optional, the key ID
* `enccty` mandatory, the content type of the encrypted data
* `enczip` optional compression algorithm, e.g. `DEFLATE`

An alternative would be similar to HTTP headers:

```json
{
  "encryption": "enc=A123CBC-HS256;alg=RSA-OAEP;kid=abc123;cty=application/xml;zip",
  "contentencoding": "gzip"
}
```

**Comment by clemensv** [comment]
I am of the very strongly held opinion that I want at least one spec of separation between anything CloudEvents and crypto of any sort and we shouldn't be owning that spec. 

WS-Security shall be an eternal warning for everyone that this isn't healthy for the kind of standards set we try to define here. 

We can bind to S/MIME (see #1115), but we should not define something here that juggles algos and keys directly.

**Comment by duglin** [comment]
@alexec is this still something you want to work on? I'm going to propose we close it and we can re-open it if needed.

**Comment by duglin** [comment]
Agreed on the 9/21 call to close this issue. If someone would like to reopen it and push it forward please let us know.
