### ISSUE TITLE
JOSE Extension

### ISSUE THREAD

**Issue by alexec** [cloudevents/spec#1114]
We have had a few chats around encryption, signing, compression. JOSE does it all. 

By default, you can have an event that contains a JWS or JWE. That's just fine for non-performance uses cases.

Marshall the JWE, and  it's 27% more space and disk costly than possible.

Can we make this better by putting put the JOSE headers into the context attributes?

JWS has 3 fields:

* header (a key-value map: alg, kid)
* payload (bytes)
* signature (bytes)

JWE has 5 fields:

* header (a key value map: alg, kid, zip?, cty?)
* encrypted_key (bytes)
* iv (bytes)
* ciphertext (bytes)
* authentication tag (maybe zero bytes array)

When combined, you should sign the payload, then encrypt the result (payload, signature). 

Abstractly:

```
sign(header, payload) -> signature
encrypt(header, plaintext) -> (encrypted_key, iv, ciphertext, tag)
```

**Comment by alexec** [comment]
```json
{
  “jwsalg”: “H256”,
  “jwskid”: “k-0”,
  “jwealg”: “RSA-OAEP”,
  “jweenc”: “A256CBC-HS512”,
  “jwekid”: “k-0”,
  “jwecty”: “application/xml”,
  “jweencryptedkey”: “abc123”,
  “jweiv”: “v-0”,
  “jwetag”: “abc123”,
  “datacontentype”: “application/jws”,
  “data_base64”: “abc123”
}
```

**Comment by alexec** [comment]
What is the benefit of having signing and encryption headers?  Because we don’t want to sign the cipher text, neither encryption or signing headers are useful unless you’re going to decrypt the message. Headers are useful for things like message routing. 

@duglin can I get input here? When would we use headers rather than a field in the event data?

Both JWE and JWS can be used as message format today, if you don’t care about the larger message size, maybe you don’t care, and that is fine.

Instead, can we use S/MIME?

https://docs.jboss.org/resteasy/docs/2.3.4.Final/userguide/html/ch38.html

**Comment by clemensv** [comment]
JOSE probably gets weird in a Protobuf or Avro environment. It arguably exists because XML-Sig/Enc and WS-Sec got weird in a JSON environment :) 

If someone wants to apply JOSE to structured CloudEvents encoded as JSON there's no extra work we need to do, IMO. 

For binary modes on the various transports, you'll need a binding of an encryption/signature model to the transport message and JOSE isn't that.

**Comment by duglin** [comment]
What's the status of this one?

**Comment by duglin** [comment]
@alexec are you still thinking about this one? I'm going to suggest we close it unless it's still active. We can always re-open if needed.

**Comment by duglin** [comment]
Agreed on the 9/21 call to close this issue. If someone would like to reopen it and push it forward please let us know.
