### ISSUE TITLE
VOTE: apply for graduated status

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#1130]
We're on the verge of closing out the final (minor) issues found by our [security review](https://github.com/cloudevents/spec/blob/main/docs/CE-SecurityAudit-2022-10.pdf), so in prep for that we agreed to start a vote on going to CNCF Graduated Status (see [criteria](https://github.com/cncf/toc/blob/main/process/graduation_criteria.md#graduation-stage)). @markpeek and I will be reviewing that list but assuming we've done all of the steps on there, this vote is for formal approval of the group to go forward. On today's call (12/8) there were no objections.

The voting ends on Dec 15th @ 12pm ET

Please register your vote or objection by adding a comment to this issue. Everyone is encouraged to vote, but binding voters are: Google, IBM/RedHat, Microsoft, SAP, Solace, SentinelOne, VMWare, Jem Day, Erik Erikson, Tommy Chung

Binding voters please add a comment, not an emoji. It only shows 10 names and we can't tell who else clicked it.

**Comment by embano1** [comment]
Awesome! Done!

**Comment by jmcx** [comment]
All for it! 🚀

**Comment by salaboy** [comment]
Looking forward for this!

**Comment by lance** [comment]
🎓 sounds great!

**Comment by duglin** [comment]
Binding voters, please vote with a comment, not an emoji. We have so many emoji votes that it just say "3 more" and I can't see who those 3 votes are :-)
So far, the binding votes I have are:
Yes: IBM/Redhat, Microsoft, SAP, Solace, VMWare, Erik Erikson

Yet to vote: Google, Splunk, Jem Day, Tommy Chung

**Comment by jskeet** [comment]
LGTM, 🥳

**Comment by bigdavethewave** [comment]
LGTM

**Comment by duglin** [comment]
@JemDay asked me to register his vote for him... he votes "yes"

**Comment by techietommy** [comment]
Yes, let's do it!

**Comment by dbaldwin-s1** [comment]
LGTM (Yes)
