### ISSUE TITLE
How to represent multiple subjects

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [cloudevents/spec#1141]
Hi, 
I don't know if this is in the scope of the project but is there any established way to represent a CloudEvent with multiple subjects? In the specification I've not seen anything, but maybe this is not a useful use case

**Comment by duglin** [comment]
Not with spec-defined attributes no. You could add new attributes (extensions) for the secondary subjects, but you'd then need to ensure the receivers understand, and look for, those extensions.

I'm curious, what is your usecase for this feature?

**Comment by giovanni-bertoncelli** [comment]
I have a system that can generate notifications from external engines that emit events based on some rules previously defined. These rules can be related to more that one entity or even a geographical area that contains some of them. So each emitted event can relate to one or more business entity that triggers the notifications generation.

**Comment by giovanni-bertoncelli** [comment]
I was thinking to use some encoding in order to save multiple IDs inside the `subject` claim. But maybe it is not that elegant and I'll encode the subjects only inside my payload.

**Comment by duglin** [comment]
Interesting cases. I suspect a purist might say that there should be one event per "subject" (or "source"), along with some kind of "correlation-id" if someone wanted to be able to link them all back together at some point. But, let me pull in @clemensv for his perspective.

**Comment by duglin** [comment]
If that's the case then I think you might be stuck with a bit of a custom solution, meaning define some extensions with the additional subjects (or as you mentioned, define a way to encode multiple sources into one attribute). It just means that any generic CE receiver would not be able to process these extensions, but if you're ok with custom receivers then it should be ok.

**Comment by giovanni-bertoncelli** [comment]
I think I'm going with the custom `subject` serialization. Thanks for the amazing support!

**Comment by deissnerk** [comment]
If you are encoding multiple subjects into a single attribute, it might be important to have them in a well-defined order. Otherwise, the [standard subscription filters](https://github.com/cloudevents/spec/blob/main/subscriptions/spec.md#3241-filter-dialects) will not work as expected.
