### ISSUE TITLE
Use `stale` bot/action to automate issue and PR lifecycle management?

### ISSUE THREAD

**Issue by embano1** [cloudevents/spec#1142]
Looking at the issues, and to some extent PRs, there's a lot of issues without activity/author feedback i.e. stale.
Should we add Github's `stale` action to automate the process of pinging authors, and eventually closing issues without activity/feedback?

cc/ @clemensv @duglin

**Comment by duglin** [comment]
I like the idea of "pinging authors", but I'm not a fan of "auto closing" issues/PRs. It makes me feel like the maintainers aren't doing their job... at least in cases where we're not waiting on the originator. And in those cases I think we need to manually see if who is on-the-hook for the next step.

**Comment by duglin** [comment]
Luckily, our backlog isn't too bad. I think a large number of them are related to the new specs so I'm hoping we can revisit those issues soon since I think (at least) the discovery spec is becoming more real.

**Comment by embano1** [comment]
Stale bot can be configured to only ping w/out closing if that helps.

**Comment by duglin** [comment]
yep - I noticed that. I might try to set it up for the pinging stuff....

**Comment by embano1** [comment]
Done: https://github.com/cloudevents/spec/pull/1144
