### ISSUE TITLE
Logging event extension

### ISSUE THREAD

**Issue by alexec** [cloudevents/spec#1149]
I've been working a spec for Semantic Logs. It really just a spec for what is essentially as de-facto standard.

https://github.com/semantic-logs/spec

It got me thinking about how you'd bind this to a CloudEvent, how it's work with OpenTelemetry.

```json
{
  "specversion": "1.0",
  "type": "log.event",
  "source": "host.app",
  "id": "n/a",
  "time": "2023-01-23T01:02:03",
  "level": "INFO",
  "msg": "The message"
}
```

**Comment by duglin** [comment]
I wonder if "msg" would map to "data" ?

Also, see: https://github.com/cloudevents/spec/blob/main/cloudevents/extensions/severity.md

**Comment by duglin** [comment]
@alexec does the "severity" extension look like something that could work for you?

**Comment by alexec** [comment]
![image](https://user-images.githubusercontent.com/1142830/219466155-c193d22e-e6e6-43a4-aa23-ef72ceab8085.png)

**Comment by alexec** [comment]
could not have said it better myself

**Comment by duglin** [comment]
I'm just impressed that it even came close

However, I think it has it backwards. "severity" being a string is good for humans but w/o hard coding things you can't know if "high" is more or less sever than "low". At least with a number you can know for sure which is worse via a simple compare - and that's better for interop.

Not sure what it means by "standard extension" :-)

**Comment by alexec** [comment]
I'm not sure either what it means. ChatGPT regurgites a lot of other peoples opinions. 

I disagree about the ordering. 

Symbolic levels must be meaningful. Because they must be meaningful, there must be a way to establish meaning. The only accepted way to have a standard. The standard for severity levels is a de-facto standard: the set of the following symbols: error, fatal, info, debug, warning, trace. Users cannot specify their own custom levels.

To be blunt, allowing users to specify number or custom symbolic level fully undermines any usefulness of the specification.

The fact that OpenTelemetry allows ranges of numbers is madness.

Because you have now specified a small finite set, you can make that set ordered:

```
fatal, error, warning, info, debug, trace 
```

**Comment by sasha-tkachev** [comment]
Use the severity extension for log level. 
And we discussed it a few months ago about the msg attribute. 

Msg MUST NOT contain newlines. Which is hard to gurantee for log messages.

**Comment by alexec** [comment]
> Msg MUST NOT contain newlines.

Log files in JSON encoding can contain escaped new lines.

**Comment by alexec** [comment]
> Use the severity extension for log level.

This is probably good enough for most people.

**Comment by sasha-tkachev** [comment]
The spec prohibits newline in string attributes. 
Actually when ai come to think about it you can define it as binary attribute, but it will force you to base64 encode it in json format if im not wrong.

**Comment by alexec** [comment]
> The spec prohibits newline in string attributes.
> Actually when ai come to think about it you can define it as binary attribute, but it will force you to base64 encode it in json format if im not wrong.

If that is the case, then to supports logs you’d have to put them into data. Cannot be context attribute.
