### ISSUE TITLE
[Registry] How do people know what content-type the messages will be?

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#1162]
We have a `format` property that will tell people that the message is a CloudEvent, but nothing in the Endpoint metadata to indicate whether it'll be xml, json, avro, ... or what the possible formats might be so people could specify that choice on the Subscribe() operation (if it supported it).

We should consider adding something to indicate the content-type(s) of the messages.

**Comment by clemensv** [comment]
"Content-type" is a message-format specific field that exists in all message format definitions either explicitly or implicitly.  There is no hard correlation between the schema format and the media-type/content-type for a message. 

What is "vnd.contoso.application/foobar"?

It's an app-level hint.

**Comment by duglin** [comment]
Moved to: https://github.com/xregistry/spec/issues/19
