### ISSUE TITLE
[Registry] `format` vs `contenttype`

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#1163]
In the Registry spec we now have `format` and `schemaFormat`, should those be some variant of `contentType` instead to align with what CE calls the property?

**Comment by clemensv** [comment]
That would be nice, but 

a) protocols have no MIME media type
b) several schema formats have no proper media type. Proto doesn't, Avro doesn't. 
c) If there are MIME types, they often don't have version info and that might matter.

`schemaformat` is a companion attribute to `schemaurl`/`schema` and lives inside an object (definition) that itself has a `format`. 

We have three occurrences of the same pattern:

- Protocols: e.g. HTTP/1.1, AMQP/1.0, Kafka/3.5, ...
- Message Formats:  CloudEvents/1.0, AMQP/1.0, ...
- Schema Formats: Avro/1.11.0, Protobuf/3, XSD/1.1

That is far cleaner than supporting a multitude of real and invented media types where version info may or may not be available.

**Comment by duglin** [comment]
@stevenhartley I believe you were the one who raised this question during last week's call. Does @clemensv's answer make sense to you?

**Comment by duglin** [comment]
Moved to: https://github.com/xregistry/spec/issues/20
