### ISSUE TITLE
Pre-check-in scripts issue: Capitalization of keywords used as expressions in spec

### ISSUE THREAD

**Issue by clemensv** [cloudevents/spec#1165]
I am getting the validation error "registry/spec.md: line 2394: 'Required' MUST be capitalized ('REQUIRED')"

for 

```
###### `required` (Required)

- Type: Boolean
- Description: Indicates whether the property is required to be present in a
  message of this type.
- Constraints:
  - OPTIONAL. Defaults to `false`.
  - If present, MUST be a boolean value.
 ```
 
 In this instance, the validation script must move. I think the check needs to avoid all RFC keywords that appear surrounded by single and double quotes, square/round/squiggly parentheses, backticks, and inside of code blocks (triple backticks).
 
 @duglin

**Comment by duglin** [comment]
@clemensv go ahead and rebase and see if the issue is fixed

**Comment by duglin** [comment]
What does the `(Required)` mean in this case?
