### ISSUE TITLE
For discussion: SDK conformance tests

### ISSUE THREAD

**Issue by jskeet** [cloudevents/spec#1181]
Jem contacted me briefly in the Zoom call last week, saying that we should talk about conformance tests at some point. I've been meaning to propose something like the idea below for a while, and this finally gave me enough impetus to do it...

# Design for CloudEvents SDK conformance tests

Iniital author: Jon Skeet

Our SDKs will be most useful if they all follow the CloudEvents spec consistently. Where interpretation of the spec can vary, it should be fixed - but it's hard to achieve that without knowing where interpretations vary.

CloudEvents SDKs vary in design, so shared conformance tests will never test all SDK features comprehensively, but we can still get better alignment *with* shared conformance tests than without.

Test for event format support can usually be executed without much additional infrastructure or design. Tests for transport support may require additional work to parse "an HTTP request" etc from a commonly-designed format.

This proposal is currently oriented around event formats, but further work to support transports would be welcome.

## Designing data-driven tests

We should aim for human-writable, human-readable test suites. Most of our event formats (XML, protobuf, JSON) have text representations (using the JSON representation of protobuf messages) so it makes sense to use those representations for the tests.

All of those text formats can include the event representation within a larger context, so I propose that we use that to bundle similar tests together, avoiding the creation of a huge number of files.

I envisage tests for:

- Parsing from the event format to an in-memory CloudEvent
- Parsing from a batch event format to an in-memory batch of CloudEvents
- Parsing from invalid single/batch events, to test validation

Note that the validation should only be in the form of CloudEvent-specific ways in which data can be invalid. For example, we would want a test to prove that the `id` attribute must be provided, but *not* for inherently-invalid XML. (This way, every test can be loaded as part of a valid "document" or equivalent.)

An SDK which doesn't support batch for a format should be able to gracefully skip batch tests.

Every test should have an ID unique within that format (but ideally *shared* between different CloudEvent formats, where they're testing the same functionality).

Tests should be self-describing in the data as far as is reasonably possible: ideally, if one developer adds a new test, all SDK maintainers should be able to update their submodule (or however they access the data) and rerun their tests, observing the new test with no extra work. (That won't always be possible, as noted below, but in many cases it should just work out of the box.)

## Limitations of data-driven tests

While a good set of conformance tests can be *largely* data-driven (by which I mean "no per-test code"), there are some limitations to this approach.

### Formats for the data part of CloudEvents

The data part of events can vary widely, and is likely to be hard to express in a portable way. We can potentially test *string* data easily enough, but almost anything else is likely to require hand-written checks. We should probably plan for this, in terms of having a convention for how tests are documented for "in this test you should also check X".

### "Trusted" events

One inherent problem in data-driven tests is being confident in the assertions made. Parsing two JSON files and asserting that the values expressed in one are equal to the values expressed in another doesn't do much good if your JSON parser is already broken.

There are a few reasonably obvious options here, and suggestions for others are welcome.

#### Code-defined sample events

If we have a variety of events that are well-documented (and have unique IDs), those events can be hard-coded in per-language test frameworks and then compared with the result of parsing the specific format.

#### Canonical representations

If we pick one event format which is completely unambiguous, the sample events can be defined in that and then SDK authors "only" need to trust their handling of that format (and only so far as the sample events require). JSON cannot be used for this, as it doesn't provide type information for attributes. Unfortunately it's the only
event format which is likely to be implemented everywhere...

#### Non-production event format

We *could* design an additional event format solely for the purpose of testing, with design goals of being trivial to parse and completely unambiguous in representation. (This feels like it's probably not a good idea, but I mention it for completeness.)

## Sharing the tests

We already have a [conformance test repo](https://github.com/cloudevents/conformance) which is (if I understand it) aimed at testing HTTP receivers of the JSON event format.

I propose using the same repo, but potentially reorganizing it into folders, in order to allow one repo to contain multiple kinds of tests, with clear documentation around how the tests in each folder are expected to be used.

This repo can then be included as a submodule of individual SDKs as a simple way of sharing the tests without any duplication/divergence.

## Next steps

If this overall proposal sounds reasonable, I can create some tests for XML, JSON and Protobuf. This could be done in the .NET SDK repo if we're not *sure* that we want to reorganize the conformance repo, or we could do "just enough" reorganization to allow for some initial tests to be created.

Eventually we'll want to declare the test format "reasonably stable" so that SDK authors can integrate the tests without fear of having to redo their work every few days. Initially we should expect some churn though.

**Comment by jskeet** [comment]
Interestingly, I've just started prototyping this, and already found some unexpected behavior *in the SDK I maintain*. (It's clear from the comment in the code, but not what I naively expected.)

When parsing the following JSON structured event:

```json
{
    "specversion": "1.0",
    "id": "simpleExtensions",
    "type": "io.cloudevents.test",
    "source": "https://cloudevents.io",
    "extinteger": 10,
    "extboolean": true,
    "extstring": "ext"
}
```

... I expected the extension attribute types to be inferred as Integer, Boolean and String respectively. They all came out as strings. My comment in the code is:

```csharp
// Note: we *could* infer an extension type of integer and Boolean, but not other extension types.
// (We don't want to assume that everything that looks like a timestamp is a timestamp, etc.)
// Stick to strings for consistency.
```

This is the sort of thing that conformance tests *might* discover about differences in assumptions SDKs make. As JSON format spec doesn't say how an SDK should parse JSON like the above - it only talks about the representation of an extension which is *known* to be of a given type.

**Comment by duglin** [comment]
@jskeet how far are your goals for the current conformance repo (at least w.r.t. http/json) ?

**Comment by jskeet** [comment]
@duglin: My immediate goals are around format testing without bringing HTTP into the mix at all.

[This branch](https://github.com/jskeet/sdk-csharp/tree/json-conformance-tests) shows what I've started looking at.

I haven't seen anything like that in the conformance repo at the moment (and I definitely dislike the invention of another format - YAML - that would make it harder to adopt). I suspect the existing code in the conformance test repo is still useful (or at least would be with more documentation) but I think it has different aims.

**Comment by xSAVIKx** [comment]
That's an excellent idea. I started integrating conformance tests as a sub-module to the Python SDK, but I eventually gave up due to my lack of Go knowledge or some other things.

I guess that even just having several standardized "good" and "bad" events and expected results from this and that conversion is already a big step forward.

**Comment by jskeet** [comment]
The branch now contains:

- JSON format tests: 10 valid, 25 invalid
- XML format tests: 8 valid, 49 invalid
- Protobuf format tests: 6 valid, 20 invalid

Next step: work out how to get it into the https://github.com/cloudevents/conformance repo.

**Comment by jskeet** [comment]
One note: currently this is *just* about parsing. There's nothing to test that the sample events are formatted in a particular way. That would be useful to do, but requires a bit more work in terms of things like "compare the JSON output, but ignoring the order" etc.

**Comment by jskeet** [comment]
@duglin: I'd be happy for us to close this issue now, given that it's basically in progress in the conformance repo. Is that okay with you?

**Comment by duglin** [comment]
done! thanks

**Comment by duglin** [comment]
ping @cloudevents/sdk-maintainers @cloudevents/sdk-csharp-maintainers @cloudevents/sdk-go-maintainers @cloudevents/sdk-java-maintainers @cloudevents/sdk-javascript-maintainers @cloudevents/sdk-php-maintainers @cloudevents/sdk-powershell-maintainers @cloudevents/sdk-python-maintainers @cloudevents/sdk-ruby-maintainers @cloudevents/sdk-rust-maintainers 

Can you folks take a look at this proposal and in particular this: https://github.com/cloudevents/conformance/tree/format-tests/format to see if @jskeet's proposal sounds reasonable?

**Comment by duglin** [comment]
@embano1  @jcrossley3 @Cali0707 @lance @lionelvillard @clemensv @fabiojose @dazuma any thoughts?

**Comment by Cali0707** [comment]
I like the initiative!

My only thought is it would be nice to separate out the batch vs. non batch events into sub directories if possible. That way SDKs can test those separately, and don't need to fully implement batch support to be "conformant" for non-batch events

**Comment by embano1** [comment]
@duglin +1 I also like the initiative to make the SDKs more robust, simplify maintainability (tests), and evolution. My only concern with the proposal is that it requires maintainers/contributors to create per-SDK test frameworks which 1/ development effort: it can take significant time to implement across the SDKs (development effort) and 2/ parity: which will likely also lead to inconsistencies like we already have between the SDKs when it comes to the implementation of the test framework (e.g., supporting all event formats/encoding).

IMHO, while tests should use their individual language-idiomatic approaches, perhaps there's a way to standardize the send/receive/compare pipeline across the SDKs with a single conformance test framework, like a Go-based CLI which can be run from all SDKs (and I think was the original idea @n3wscott worked on)?

**Comment by jskeet** [comment]
@embano1: My experience with both "get a standardized tool to invoke some kind of server" and "write the tests in their language" is that there's work involved in both approaches, it's *much* easier to debug code in the "it's all in your language" case... and there's no setup of other languages etc involved in order to run the tests. It also means that the tests can check that in-memory representations are correct - whereas a send/receive/compare pipeline relies on testing the serialized version. If others would prefer the sort of pipeline approach, we can go with that - I just wanted to explain why I prefer the in-language approach.

@Cali0707: Are subdirectories particularly better than filenames for this? I think so long as we don't mix different test types within the same file (at least without some easy way of telling the difference), it should be easy enough for an SDK to only run tests for non-batches. I'm not massively against subdirectories - it just feels like using the filenames for the same purpose is a bit simpler.

**Comment by duglin** [comment]
re: test frameworks... would it be possible to live in-between the two worlds? Have a shared "testing driver/harness" but then ask each SDK to create a very simple receiver (e.g. http server) that can return whatever the test driver needs to verify things (e.g. dumps it's in-memory data in a common way). Then the per-SDK side of things can be written just once, but the test driver can grow over time (if needed) w/o each SDK needing to change their code. And if the test driver was packaged as a docker image then there's no setup of "another language" needed, aside from docker. Although, if it was written in go-lang, then we could just also just compile it into a stand-alone exe for the various envs we need - no "setup", just "download".

re: file structure... one potential situation to think about is how to deal with error conditions such as "invalid json". It might introduce challenges to have to represent invalid json in a doc that's required to be valid json.

@jskeet what do you propose for next steps?

**Comment by jskeet** [comment]
@duglin: "dumps its in-memory data in a common way" sounds very much like serialization to me - with all the relevant problems. And then it would still be awkward - in my experience - to do debugging in the way that I'd personally find useful. (And it's still definitely more complex to set up for CI. Not awful, but non-trivial compared with "include this in your existing tests".)

I think one potentially viable and simpler half-way house would be to have each SDK implement an HTTP server which *literally* just validates whether the body is valid or not. Maybe there'd be some metadata of "known extensions" - I can't remember offhand whether I ended up needing that in the conformance tests I originally wrote. The test harness would then just check that all the valid events are accepted, and all the invalid events are rejected.

We could still encourage SDK maintainers who wanted to provide a deeper level of conformance checking to write the per-SDK test framework for more detailed validation.

In terms of next steps - I think we should continue the discussion here for a bit, then I can update the branch as required - then we could merge. I won't have time to write any kind of test harness I'm afraid - but I could definitely write the .NET SDK side of it for testing the test harness :)

**Comment by duglin** [comment]
Is it sufficient that a valid CE is "accepted" or did you want to do things like verify that INTs are parsed as INTs and not STRINGs ?  Granted, all spec defined things are strings, but if we have well-known INT extensions then is that something we want to check?

**Comment by jskeet** [comment]
> Is it sufficient that a valid CE is "accepted" or did you want to do things like verify that INTs are parsed as INTs and not STRINGs ? Granted, all spec defined things are strings, but if we have well-known INT extensions then is that something we want to check?

For time attributes, we can use invalid CEs which still have strings (that aren't valid timestamps). Likewise for URIs. As you say, without any core int-based attributes, it's hard to validate that part - we could definitely have some well-known extensions (and have some metadata in the request to say which extensions are in play), but without knowing how other SDKs handle extensions, I don't know whether they wouldn't naturally reject such events.

**Comment by jskeet** [comment]
I would say that it's worth avoiding making the perfect the enemy of the good though - even just the valid/invalid, without reference to any extensions, is better than we've got now :)

**Comment by duglin** [comment]
Not looking for perfection as much as I think reality is that we may only get "one shot" at getting each SDK to write test code and any future changes to support more stuff might never happen.

**Comment by jskeet** [comment]
That's a good point. Maybe we should start with *one* SDK (other than .NET) and see how things go and what we can accomplish reasonably easily, before trying to roll out to others? I don't know which SDKs have particularly enthusiastic maintainers at this point...

**Comment by Cali0707** [comment]
I'm trying to pick up the Java SDK (since we use it in knative) - happy to work to implement the conformance tests there. My only concern is the Java SDK does not yet have batch support - I also need to add that

**Comment by duglin** [comment]
I suspect it might be Go since all of the other comments came from Go folks-DougSent from my iPadOn Aug 28, 2025, at 1:23 PM, Calum Murray ***@***.***> wrote:﻿Cali0707 left a comment (cloudevents/spec#1181)
I'm trying to pick up the Java SDK (since we use it in knative) - happy to work to implement the conformance tests there. My only concern is the Java SDK does not yet have batch support - I also need to add that

**Comment by duglin** [comment]
Closing and added to our v2.md doc as a potential future work item
