### ISSUE TITLE
Why `time` not granular to milliseconds?

### ISSUE THREAD

**Issue by alexec** [cloudevents/spec#1188]
`time` granularity is only to seconds. I need events timestamped to milliseconds.

**Comment by alexec** [comment]
Oddly, timestamp is zoned, but I'm not sure I'd ever want that because I don't know what zone means. Zone of customer? Zone of computer?

**Comment by duglin** [comment]
See: https://www.rfc-editor.org/rfc/rfc3339. In particular the "fraction" time stuff. That's where the milliseconds go.
In golang terms, see `RFC3339Nano = "2006-01-02T15:04:05.999999999Z07:00"` in the time package.

**Comment by alexec** [comment]
Are you saying it is milliseconds? If so, the Java SDK does not support that.

**Comment by alexec** [comment]
I might have spoken too soon. Let me dive deeper.

**Comment by alexec** [comment]
I am wrong:

> OffsetDateTime is an immutable representation of a date-time with an offset. This class stores all date and time fields, to a precision of nanoseconds, as well as the offset from UTC/Greenwich. For example, the value "2nd October 2007 at 13:45:30.123456789 +02:00" can be stored in an OffsetDateTime.

**Comment by alexec** [comment]
https://www.rfc-editor.org/rfc/rfc3339

**Comment by alexec** [comment]
So Java does support millis. Spec says RFC3339, which does not support millis. 

Please advise.

**Comment by alexec** [comment]
ISO-8601 does support millis.

**Comment by alexec** [comment]
This is excellent:

https://ijmacd.github.io/rfc3339-iso8601/

**Comment by alexec** [comment]
RFC3339 could be clearer. Led me to wrong conclusion.

**Comment by duglin** [comment]
LOL I was curious to see which Alex would win this argument :-)
