### ISSUE TITLE
Why do we need "data" in the "Context Attributes" section?

### ISSUE THREAD

**Issue by cathyhongzhang** [cloudevents/spec#119]
What is this "data" attribute? What is it used for?

**Comment by duglin** [comment]
Its the actual event.
So, if the original (pre-CloudEvent conversion) event looked like:
`{ "foo": "bar" }`
then the CloudEvent would be something like:
```
{ "source": "...",
  "event-id": "...",
  ..other attribtues...
  "data": { "foo": "bar" }
}
```
I think.

**Comment by SeanFeldman** [comment]
Sounds right.
Microsoft EventGrid defines `data` as
> Event data specific to the resource provider.

**Comment by cathyhongzhang** [comment]
In the previous section, context and data are defined as two separate entities. But in this section, data is part of event context. Does the "data" here means the location of the event payload in the event message (or the type of payload or something else)? A "data" field inside the event context needs a clear definition to avoid confusion.

**Comment by duglin** [comment]
For those who may not see the other issue, see this comment: https://github.com/cloudevents/spec/issues/108#issuecomment-375785406

**Comment by duglin** [comment]
@cathyhongzhang I think we can close this one since we approved #198 today.  Let me know if I'm mistaken and we should reopen it.
