### ISSUE TITLE
Migrate Registry to xRegistry org

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#1190]
Proposal for moving the Registry work to the xRegistry org (https://github.com/xRegistry):
- repo: `xregistry.github.io`
  The web site repo. Exists today as a WIP
- repo: `spec` 
  **Question**: `spec` or `specs` ? CE uses singular, but we expect multiple specs here, while CE is (sort of) one spec with lots of secondary/ancillary specs.
  **Proposal**: `spec` mainly for consistency with CE
- within the `spec` repo have the following directory structure:
  - `core` - the core/abstract xRegistry spec
  - `endpoint` - the Endpoint Registry spec
  - `message` - Message Registry spec
  - `schema` - Schema Registry spec
  - `pagination` - a better home than the CE repo
  - Notice they're singular not plural....e.g. "Schema Registry" not "Schemas Registry"

Another option is to create a new repo per spec, but that seems like a lot of overhead.

If we go with a mono-repo then we need to figure out the versioning scheme since it's possible that each of these specs could change at radically different rates. Some options include:
- 1 - No github branches/releases at all. Each repo creates a v.X directory for each release - would need a "latest" type of dir too
- 2 - follow CE's pattern, each release of any spec creates a new github branch/release with the name of the "spec" that caused it to be created. E.g. `core-v1.2` or `schema-v3.0`. The entire repo is "snapshotted" during that process. So there is a linear history of tags/branches/releases... but at any point in time there's a different reason (spec name) for the snapshot. 
- **Proposal**: 2nd option.

**Comment by duglin** [comment]
If you can't make the call this week, or if you just can't wait to comment ;-) , feel free to speak-up here so we can gather as much input as possible. I'd like to create a PR to do the migration after this week's call (and then approve it on next week's call).

**Comment by jskeet** [comment]
Side-note: we should discuss the impact on https://github.com/cloudevents/spec as well. Will it still make sense to have a toplevel "cloudevents" directory when most of the other specs have been moved? (I'm assuming pagination will go as well.) There's still cesql of course - not sure where that belongs, to be honest.

I'm okay with keeping it where it is (aside from anything else, that avoids more work *and* breaking links), but I think it's just worth thinking about.

**Comment by duglin** [comment]
Add text about the relationship between the specs...e.g. how are dependencies expressed and dealt with as thing are versioned.

**Comment by matzew** [comment]
I like the idea of the mono-repo here!

One comment/question: Regarding `Message Registry spec`, isn't that more a `Message (Group) Definition Registry spec`? Since we group them, and it provides their structure?

**Comment by duglin** [comment]
@matzew I guess message (and maybe endpoint) are different from schema in that schema IS the resource of interest, while the other two registries defines the shape of the thing of interest. Is it worth being more verbose when it seems like it should be obvious that the exact messages being sent are not in the registry, rather just their shape? What do others think?  @clemensv @deissnerk @jessemenning

**Comment by duglin** [comment]
See: https://github.com/xregistry/spec/pull/1
