### ISSUE TITLE
Submitting a new protocol binding

### ISSUE THREAD

**Issue by kydos** [cloudevents/spec#1198]
Hello, 

I would like to have some guidance on how we could submit a binding for the eclipse-zenoh protocol (See https://zenoh.io and http://github.com/eclipse-zenoh/zenoh). Should we just do a pull request, or is there any other process to be followed before getting to the PR? Thanks very much for providing some guidance!

**Comment by duglin** [comment]
Hi @kydos yes basically submit a PR is the best path when it's not too much trouble. Issues are ok if you think some discussion is needed before a proposal can be written (e.g. if a PR is ton of work and there's doubt that the idea will even be accepted), but if you know what the PR would look like I think having the concrete proposal for people to look at is usually the fast path.

**Comment by duglin** [comment]
Closing since I think the question was answered. If more is needed feel free to reopen
