### ISSUE TITLE
Github repo description references OpenEventing

### ISSUE THREAD

**Issue by janoberst** [cloudevents/spec#12]
This repo's name has changed and its contents have been modified to use CloudEvents, but the description of the repository seems to still say "OpenEventing." I found this just a tiny bit confusing and would've put up a PR for it, but I think this needs to be changed by a project admin in the Github interface.

I'm attaching a screenshot for future reference:

<img width="260" alt="cloudevents - openeventing" src="https://user-images.githubusercontent.com/19206/35167076-f8704d6e-fd08-11e7-994c-160d5d3253be.png">

**Comment by duglin** [comment]
Fixed - thanks

**Comment by duglin** [comment]
Fixed! thanks for noticing
-Doug
