### ISSUE TITLE
Add a known extension attribute to support bitemporal event data

### ISSUE THREAD

**Issue by aucampia** [cloudevents/spec#1200]
In my current and previous role, where I have worked on analytical data platforms, I have had a need for bitemporal event data [[ref](https://en.wikipedia.org/wiki/Bitemporal_modeling)]. For every event, I want to know the best approximation of when the event actually occurred (_actual time_), together with when the event was recorded in a specific message or representation (_recorded time_).

## Example

For a payment event, for example, I want to know the best approximation of the actual time when a person made the payment, and the time that the CloudEvent representing the payment was created.

If there were errors in the initial CloudEvent representation of a specific payment, or the schema of the event data changed, or the event had to be redacted, a new amended CloudEvent describing the same payment would be created with the same ID and the same _actual time_ as the previous CloudEvent, but the amended event would have a different _recorded time_.

## Benefits

Bitemporal event data makes it possible to do get reproducible inputs for data science, which in turn makes it possible to then do reproducible training and make reproducible predictions.

Knowing when an event was recorded also makes it possible to capture events into time interval blobs and to measure latency. If the actual event time is the only time associated with events, then consumers can't differentiate between an event that was republished long after the actual event time, and an event which just took a long time to propagate.

The recorded time also makes it easier to differentiate republished messages in an analytical data warehouse.

## Proposal

In my previous role, I used something similar to `orgexamplerecordedtime` for the attribute with the recorded time, but I would prefer to just use `recordedtime`. However, I think for that, it would be appropriate to register the attribute name in the CloudEvents specification repository as a known extension.

I will make a pull request to add this attribute, but meanwhile I would like to get feedback on the proposal.

**Comment by duglin** [comment]
I don't see a problem with a time representing the time the CE was created, but I'm curious about some of the scenarios you mentioned. In particular, the detection of the event showing up more than once... why wouldn't people look for a duplicate CE.ID rather than look at timestamps?

**Comment by aucampia** [comment]
> In particular, the detection of the event showing up more than once... why wouldn't people look for a duplicate CE.ID rather than look at timestamps?

Well, it would not be for detecting duplicates, it would be for distinguishing duplicates, so two events with the same CE.ID could be kept as long as their `createdtime` attributes are different, and they would be kept so that anything that was using the old event would still be able to get it if they extract events using both the `createdtime` and `time`.

**Comment by aucampia** [comment]
I'm a bit unsure about the name, some other options:

- `eventtime` - given that the `time` attribute should be the occurrence time, this is possibly the best option, however, this is also slightly confusing to people who may not be familiar with the CloudEvents terminology.
- `timerecorded` - this may be less ambiguous than `recordedtime`.
