### ISSUE TITLE
Proper use of cloudevents avro schema with arrays

### ISSUE THREAD

**Issue by SamlRx** [cloudevents/spec#1203]
We're trying to serialize objects that contain a list of ids contained in an array and I'm having a problem serializing this object using this avro schema (https://github.com/cloudevents/spec/blob/main/cloudevents/formats/cloudevents.avsc)

The message below seems to conform to the schema but the "observer_ids" part seems a bit counter-intuitive to write:
```json
{
      "attribute": {
          "id": "30f25372-323b-47a8-988b-b5b068fb0985",
          "type": "com.some.source.django_service.any_other_models.created",
          "time": "2020-01-01T11:12:00.000000Z",
          "source": "com.a.source",
          "specversion": "1.0",
          "contenttype": "application/json",
          "dataschema": "http://django_service.some.source.com/schema/v1/POST/any_other_models.json"
      },
      "data": {
          "id": "30f25372-323b-47a8-988b-b5b068fb0985",
          "observer_ids": {
              "value":{"observer_ids":[
                  {"value":{"id":1}},
                  {"value":{"id":2}},
                  {"value":{"id":3}}
              ]}
          }
      }
}
```

Is there a proper way to write an array directly into an Avro message using the schema above?
```json
{
      "attribute": {
          "id": "30f25372-323b-47a8-988b-b5b068fb0985",
          "type": "com.some.source.django_service.any_other_models.created",
          "time": "2020-01-01T11:12:00.000000Z",
          "source": "com.a.source",
          "specversion": "1.0",
          "contenttype": "application/json",
          "dataschema": "http://django_service.some.source.com/schema/v1/POST/any_other_models.json"
      },
      "data": {
          "id": "30f25372-323b-47a8-988b-b5b068fb0985",
          "observer_ids": [1, 2, 3]
        }
}
```

**Comment by duglin** [comment]
@alexec @JemDay

**Comment by JemDay** [comment]
Not that this helps you right now but I believe it's this type of concern that has resulted in @alexec starting work on a modified Avro format.

Ref: GH-1197

Note: As it currently stands that proposal only allows for byte[] as a data payload - if you see that as an issue now would be a good time to flag that.

**Comment by duglin** [comment]
@SamlRx have you look at Alex's PR? #1197 does that help you at all?

**Comment by duglin** [comment]
@SamlRx does https://github.com/cloudevents/spec/blob/main/cloudevents/working-drafts/avro-compact-format.md help ? 

@alexec any comments?

**Comment by duglin** [comment]
@SamlRx I'm going to suggest we close this since I'm not getting a response to the questions. Please let us know if this problem still exists since the other PR was merged.

**Comment by duglin** [comment]
Agreed on the 9/21 call to close this issue. If someone would like to reopen it and push it forward please let us know.
