### ISSUE TITLE
Add a documented extension for expiring events

### ISSUE THREAD

**Issue by djnalluri** [cloudevents/spec#1205]
I would like to propose a new extension that indicates a time after which, the CloudEvent (CE) may be ignored.

## Example
A sensor sends telemetry at regular intervals through an intermediary to a CE consumer. The intermediary is configured for at-least-once delivery guarantees. The consumer goes offline for some amount of time. Upon coming back online, it will be flooded with many old events until it catches up.

My perhaps niche use case has CE's triggering processes that the producers then check the output of. Producers wait for some amount of time before ignoring any output and may choose how long they wait depending on context.

## Benefits
A producer can hint to its consumers as to whether a CE is "current" or not. CE's that may trigger some amount of processing can be skipped to provide room for optimizations and avoid doing unnecessary work.

## Proposal
Create a new `expires` attribute containing a timestamp.

**Comment by jskeet** [comment]
I'd propose calling it `expirytime` instead of `expires`, for clarity.

**Comment by duglin** [comment]
We briefly discussed this on today's call and there was no objection with heading this direction so if you'd like to create a PR it would be welcomed! Nice timing too since we just accepted this one: #1201, which is kind of related

**Comment by djnalluri** [comment]
> Or are the use cases you have in mind more for cases where the CE producer has all of the smarts w.r.t. "what 'old' means" because it's dependent on the type of the event or who the producer is?

@duglin Precisely. I'll try to get a PR created sometime in the next week.
