### ISSUE TITLE
Add kubewatch from robusta.dev to adopters

### ISSUE THREAD

**Issue by aantn** [cloudevents/spec#1217]
Regarding kubewatch support for cloudevents, see https://github.com/robusta-dev/kubewatch/pull/50#event-9760066167 as well as https://github.com/robusta-dev/kubewatch/

**Comment by duglin** [comment]
@aantn thanks! Just created: https://github.com/cloudevents/cloudevents-web/pull/80

**Comment by aantn** [comment]
Fantastic,  thanks

**Comment by duglin** [comment]
closing since https://github.com/cloudevents/cloudevents-web/pull/80 is merged. Thanks again!
