### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by cfauchere** [cloudevents/spec#1219]
Reviewing this [section](https://github.com/cloudevents/spec/blob/main/subscriptions/spec.md#324-filters)

> The `filter` property in a subscription is a set of filter expressions, where each expression evaluates to either true or false for each event generated.
> 
> If any of the filter expressions in the set evaluate to false, the event MUST NOT be sent to the sink. If all the filter expressions in the set evaluate to true, the event MUST be attempted to be delivered.

We are trying to get the meaning of _filter is a set of filter expressions_. From the snippets we understand that `filter` is an object and not an array  which implies I can write something like this
```
{
  "filter": {
    "exact": {},
    "not": {},
    "suffix": {}
  }
}
```
Each of those 3 expressions need to resolve to TRUE for the event to be sent to the sink. This overlaps with the ALL filter with the difference that keys might not be unique which might be a problem with some framework or json parsers. A better syntax would be to allow only one dialect at the root level this would require ALL dialect if for some reason a given dialect needs to appear more than once.

**Comment by duglin** [comment]
I think there's a typo - it should say `filters is an array...` not `filter is an object`.

And so for:
```
"filters": [
    { "prefix": { "type": "com.example." } }
],
```
each `{ "prefix": { "type": "com.example." } }` would need to evaluate to true

**Comment by duglin** [comment]
See: https://github.com/cloudevents/spec/pull/1271
