### ISSUE TITLE
sql filter: clarification of non-boolean cesql expression result coercion to a boolean

### ISSUE THREAD

**Issue by Maslino** [cloudevents/spec#1221]
From sql filter docs:

> Use of this MUST have a string value, representing a [CloudEvents SQL Expression](https://github.com/cloudevents/spec/blob/main/cesql/spec.md). The filter result MUST be true if the result value of the expression, coerced to boolean, equals to the TRUE boolean value, otherwise MUST be false if an error occurred while evaluating the expression or if the result value, coerced to boolean, equals to the FALSE boolean value.

If cesql expression evaluation result is not boolean type, it should be coerced to boolean. Different programming languages have different type coercion rules. So what about cloudevents? 

If expression result is of type int32, is non-zero integer coerced to true?
If expression result is of type string, is non-empty string coerced to true?

**Comment by pierDipi** [comment]
cc @Cali0707

**Comment by Cali0707** [comment]
I can work on this, could you assign it to me @pierDipi ?

**Comment by pierDipi** [comment]
I don't have superpowers /cc @duglin

**Comment by duglin** [comment]
done!

**Comment by Cali0707** [comment]
/remove-lifecycle stale

@duglin can we discuss this at the next serverless WG meeting? I'd like to follow up on the thread from slack where we discussed things like not allowing any non-boolean return values in CESQL, and get feedback from others on what to do going forwards

**Comment by duglin** [comment]
Never mind - let's keep the call tomorrow - we have more items for the agenda. @Cali0707 can you make it tomorrow?

**Comment by Cali0707** [comment]
@duglin I'll be there!

**Comment by duglin** [comment]
Cool!

**Comment by duglin** [comment]
On the 10/19 call the group agreed that we should consider requiring all expressions result in a boolean value, then we don't need to do any conversion.  @Cali0707 agreed to create a PR for this.
