### ISSUE TITLE
Expand the CESQL tck tests

### ISSUE THREAD

**Issue by Cali0707** [cloudevents/spec#1225]
As we work in Knative Eventing to move the subscription API filters into beta, we would like expand the CESQL tck tests to cover more complex use cases. Specifically, expressing some of the other filter dialects (filter, suffix, exact) in CESQL with a combination of ANDs and ORs on required, optional, extension, and non-existing attributes.

cc @pierDipi

**Comment by duglin** [comment]
done and thanks!
