### ISSUE TITLE
CESQL: clarify behaviours of errors in OR expressions

### ISSUE THREAD

**Issue by Cali0707** [cloudevents/spec#1231]
Currently, in the Go SDK V2, `(type = 'dev.knative.example') OR (missingattribute = 'test')` results in an error, even if `type = 'dev.knative.example'`, so long as `missingattribute` is not set on the event. However, if this implementation were changed to eagerly return on a `true` value (which an optimized implementation _should_ do), then the return value would be `true`.

We should
1. Clarify whether the evaluation should be eager or not
2. Open issues to any SDKs with an implementation that does not match the new, clarified spec

**Comment by duglin** [comment]
@Cali0707 can we close this one now?

**Comment by Cali0707** [comment]
Yes, I believe so. Thanks!
