### ISSUE TITLE
Clean-up our OSS page

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#1242]
URL: https://github.com/cloudevents/spec/blob/main/docs/open-source.md

I went thru the projects on there and grouped them based on my analysis:

## Leave them
- CloudEvents Verify - last edit 2019. I think it supports v1.0 but nothing after that. It's probably ok to leave.
- Gloo - looks alive and well. Leave it.
- cloudevents-python: last touched 2018, so pre-v1.0. Issue: https://github.com/williamhogman/cloudevents-python/issues/4 
- Argo Events - looks alive and well. Leave it
- cloudevents.js - looks alive and well. Points to v1.0.2 of CE
- CloudEvents JSON Schema - last touched 2000, and it talks about v1.0 so it's probably ok. Leave it
- Knative eventing - alive and well. Leave it
- VMware Event Broker Appliance: looks alive and well. Leave it.

## Wait for a response, if none, drop them
- CloudEvents.NET only references v0.1 of the spec. I've opened an [issue](https://github.com/aliencube/CloudEvents.NET/issues/6) asking if they plan to upgrade to v1.x. If they don't answer (or say 'no') I recommend we drop them  - project appears to be dead, no edits since 2018
- Event Gateway: Issue: https://github.com/serverless/event-gateway/issues/527  project might be dead - no edits since 2019

## Drop them
- jCloudEvents - remove. The project is archived and read-only. @matzew is there a newer version? Or is the Java SDK sufficient?
- Strombrau Gateway - remove. Same a jCloudEvents, it's archived. @matzew any replacement?
- microBean: Issue: https://github.com/microbean/microbean-cloudevents/issues/1 - no plan to upgrade, so drop them

**Comment by justinyoo** [comment]
@duglin Thanks for chime me in. for the .NET one, as the official .NET implementation has been up & running, I would rather stop maintaining it.

**Comment by duglin** [comment]
@justinyoo thanks for getting back to us!
