### ISSUE TITLE
Broken TOC Links in Translated Cloudevents Docs

### ISSUE THREAD

**Issue by laipz8200** [cloudevents/spec#1277]
Seems the translated documents have incorrect links in their TOC.

For example in [this document](https://raw.githubusercontent.com/cloudevents/spec/v1.0.2/cloudevents/translated/zh-cn/primer_CN.md), the first link in the TOC is `[概览](#overview)`, but it should be `[概览](#overview概览)`.

As a result, this TOC link cannot jump to the correct location in the document.

I'm happy to assist in fixing these incorrect links. Please let me know how I can contribute.

**Comment by duglin** [comment]
@laipz8200 if you have time to open a PR to fix them that would be great!

**Comment by laipz8200** [comment]
@duglin I will make a PR in the next few days, please assign to me.

**Comment by laipz8200** [comment]
Sorry, I found this issue was already fixed and only needs to await the updated release of `README.md`.

I will close this issue, thank you for taking the time to reply. @duglin
