### ISSUE TITLE
Improve Privacy and Security section in spec

### ISSUE THREAD

**Issue by AxelNennker** [cloudevents/spec#1288]
The example provided in https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md#privacy-and-security does not follow the recommendation of the privacy and security section to encrypt the data.

```JSON
{
    "specversion" : "1.0",
    "type" : "com.github.pull_request.opened",
    "source" : "https://github.com/cloudevents/spec/pull",
    "subject" : "123",
    "id" : "A234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleothervalue" : 5,
    "datacontenttype" : "text/xml",
    "data" : "<much wow=\"xml\"/>"
}
```

**Comment by Rana-KV** [comment]
Hi @AxelNennker, I'm interested in this topic. Can I work this issue if it is not assigned?

**Comment by AxelNennker** [comment]
> Hi @AxelNennker, I'm interested in this topic. Can I work this issue if it is not assigned?

I am not a core member of cloudevents.
Also there is https://github.com/cloudevents/spec/pull/1290

So, read https://github.com/cloudevents/spec/blob/main/docs/GOVERNANCE.md and https://github.com/cloudevents/spec/blob/main/docs/CONTRIBUTING.md follow those guidelines
