### ISSUE TITLE
Receipt of events that are not understood by event consumer

### ISSUE THREAD

**Issue by lfourie** [cloudevents/spec#13]
I think we need to add some description on:
  1. nature of an event: critical - must be processed, non-critical - may be ignored, ..
  2. action taken when a consumer does not understand a critical event, etc.

**Comment by duglin** [comment]
No. 1 sounds like it might overlap a bit with the proposed "log-level" context attribute. WDYT?

No. 2 gets into defining the processing model of the events themselves. Is this something people want to include as part of the spec? I've been assuming that this spec is just defining the shape of the event (or if Yaron's idea is adopted, the API for accessing the properties of the event). What do others think?

**Comment by duglin** [comment]
As we are not currently defining a processing model, I propose that we close this issue as out of scope.

**Comment by duglin** [comment]
During 6/15 f2f we agreed to close this since "process model" is out of scope for the wg right now
