### ISSUE TITLE
How do people encode `data` in formats such as JSON?

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#133]
What, if anything, should our spec say about encoding the `data` property? For example, encoding binary data in JSON is not well defined by the JSON spec, should we say something about this to help interop?

**Comment by clemensv** [comment]
I found that I needed a firm opinion on that when writing the HTTP binding spec, so I'm already writing a companion "JSON event format" spec that explicitly calls out those rules. 

When "data" is left inside the JSON encoded structure, and the "content-type" value is not either "application/json" or has a "+json" suffix, "data" will be a base64-encoded binary type-declared by "content-type". If "content-type is either of the above (or left blank?), "data" is a JSON value and therefore rendered as a regular JSON object.

Reason I break this out into a further separate spec is that we'll also need the same definitions for AMQP and MQTT, and I can also imagine that some folks will want to have a more compact option and therefore may want to choose the MessagePack or BSON formats (either of which can accommodate binary as binary) for which we can write a parallel event format specs.

If all goes well, I'll have drafts for both the HTTP binding and the JSON data format by the end of today (Apr 5)

**Comment by rbramley** [comment]
Have been experimenting with an Avro serialization of CloudEvents (happy to contribute the [draft Avro schema file](https://gist.github.com/rbramley/c00bbd95f3f6ecc0cc1f90e5d6d6c90c)) and found that the `data` property can be a bit problematic. 

With Avro, when using a nested record for the `data` payload, the optional `schemaURL` and `contentType` are superfluous as schema validation is built-in. Though nesting records causes additional overhead for development plus runtime at event emission and downstream processing.

A map for event data would be too loose from a schema enforcement perspective, though would allow for a generic .avsc schema file. As it seems that Avro adopters would need to tweak the schema anyway, have been wondering whether a _data_ prefix could be an optional alternative to nesting under `data` (may also work for HTTP binding)? Thoughts welcomed!

**Comment by duglin** [comment]
Can we close this now?  @clemensv

**Comment by duglin** [comment]
during 6/15 f2f we agreed to close this as it is already resolved in the existing specs.
