### ISSUE TITLE
Property Naming Convention

### ISSUE THREAD

**Issue by clemensv** [cloudevents/spec#141]
As I'm writing the HTTP binding spec and the related JSON mapping, it's becoming apparent that the current naming convention for property names with words-separated-by-dashes is creating complications in the JSON mapping (and the assumed common projection into programming languages) that I'd rather avoid. 

I would very much prefer for the property names to drop the dash and either use camelCase or PascalCase.

**Comment by duglin** [comment]
+1 to camelCase

**Comment by clemensv** [comment]
Would appreciate if someone could do a renaming pass in the core spec and propose that as a PR. I kinda have my hands full.

**Comment by duglin** [comment]
I'll do it - should be an easy one.

**Comment by rbramley** [comment]
Another justification for the switch to camelCase is to support the use of Avro as a serialization format (as mentioned in the spec); Avro field names can start with [A-Za-z_] and subsequently contain only [A-Za-z0-9_].
