### ISSUE TITLE
definition of object.create, object.delete event type

### ISSUE THREAD

**Issue by ultrasaurus** [cloudevents/spec#164]
In 4/9 interop meeting (see [notes](https://docs.google.com/document/d/1OVF68rpuPK5shIHILK9JOqlZBbfe91RNzQ7u_P7YCDE/edit#), we talked about defining an event type that would be the same across platform when someone uploads a file to storage.

References:
* Microsoft Event Grid Blob event: https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-event-overview

**Comment by clemensv** [comment]
What we said was that we're going to look for use-cases with that characteristic for a demo. I didn't hear anyone seriously proposing standardizing such an event type. 

We'll oppose getting into event semantics before we have a full suite of transport bindings and event formats finalized.

**Comment by duglin** [comment]
I believe we can close this as it was part of the KubeCon EU 2018 demo talks. Please reopen if I'm mistaken.
