### ISSUE TITLE
CloudEvents Demo @ CloudNativeCon Europe

### ISSUE THREAD

**Issue by ac360** [cloudevents/spec#166]
**UPDATED: 4/26**

Hi all,

At CloudNativeCon Europe, I'm giving a talk on CloudEvents. The goals of the talk are:

* Introduce CloudEvents & announce the initial version.
* Communicate the "Why" and use-cases of CloudEvents.
* Illustrate what will be possible in the future w/ CloudEvents.
* Make it real for the audience by showing a demo.
* Tell our story of collaboration and celebrate those involved.

Thematically, the talk will focus on interoperability between environments.  The demo will focus on interoperability first and foremost.  Multiple Serverless Compute/FaaS providers are invited to participate in the demo, though you will have to do some work to integrate into the demo.

### Demo Scenario: Processing An Image File From Azure Storage Across FaaS Platforms

The demo involves a picture of Dan Kohn (executive director of the CNCF) being uploaded to an AWS S3 bucket.  When the picture is uploaded, the 'aws.s3.object.created' event is converted into a CloudEvent and routed via a hosted version of [Serverless Inc.'s Event Gateway](https://github.com/serverless/event-gateway) to any FaaS functions subscribed to the event.

If you would like to participate, create a FaaS function that does something with Dan Kohn's image and posts the result to the CloudEventsDemo twitter feed.

**[You can find all the details you need on how to participate in this repo](https://github.com/ac360/cloudevents-demo)**

**Comment by ac360** [comment]
# Demo Proposal - E-commerce

The demo will feature a minimal e-commerce web application and I will pretend to be a user that performs the following actions in the application:

* Registers
* Views two products
* Encounters an error
* Purchases a product

The web application will publish events from the client-side (for the sake of simplicity).  Some communication can happen 1-to-1 between FaaS Functions, to show off how CloudEvents can be transported freely w/o middleware.  Other communication can happen through our hosted [Event Gateway](https://github.com/serverless/event-gateway).  The Event Gateway can route events to any FaaS provider that can be accessed via a publicly accessible endpoint that can receive an HTTP POST request.  It can also route events to multiple FaaS consumers at the same time.

## Events & Possible Actions

These events will be published from the client-side of the ecommerce application:


### `user.profile.created`

This event is published and handled asynchronously after the user successfully registers for the application.    It will initially only include the user's email in the `data`.  Here are some potential actions:

* Enrich the user profile by processing the email w/ Clearbit's Enrichment API (or a similar service).
* Take the user profile image found by Clearbit and analyze it for vulgar content and insights to further enrich the user profile (use Google Vision API, AWS Rekognition or a similar service).
* Save the updated user profile.
* Save the user profile image to storage.
* Send a welcome email.  Use the enriched info to send a personalized email.
* Add the user to a CRM.
* Add the event to an analytics system.

### `user.profile.updated`

This event is published when the user's profile is successfully updated in a database.

* Back-up the profile image to another storage, on another provider/region/AZ.
* Back-up the user profile to another database, on another provider/region/AZ.
* Add the event to an analytics system.

### `error.received`

This event is published when the user encounters an error in the application.  For example, a back-end service does not work and a 500 status code is received.  Here are some potential actions:

* Send an error email to the Ops team.
* Send an error SMS to the Ops team.
* Reconfigure the back-end service to run a back-up option on another region or provider.
* Add the event to an analytics system.

### `user.viewed`

This event is published when the user looks at a specific product.  Here are some potential actions:

* Update the Recently Viewed service
* Perform some type of change to create a personalized experience
* Add the event to an analytics system.

### `user.purchased`

This event is published when a product is purchased in the ecommerce app.  Here are some potential actions:

* Slack integration notifying that a product has been purchased.
* Send email receipt.
* Add the event to an analytics system.
* Pull in the last 20 events and create a walkthrough of the user journey that led to the sale.

**Comment by duglin** [comment]
let's word this so that anyone can generate the events.

We also talked about an image recognition service.  So, if the event was text then we could analyze it for tone/sentiment, or if its an image we can analyze it to guess what's in it. And then tweet the result.

**Comment by ac360** [comment]
> let's word this so that anyone can generate the events.

@duglin Building a demo around publishing two events, each with multiple FaaS subscribers across platforms is a decent amount of work for the limited time that we have before CloudNativeCon (also there isn't much time to perform this demo during the talk).  At this time, I don't want to introduce more published events.  Overall, I think the two use-cases outlined above will convey the story and demonstrate what's possible.

> We also talked about an image recognition service. So, if the event was text then we could analyze it for tone/sentiment, or if its an image we can analyze it to guess what's in it. And then tweet the result.

Yes, that's going into the second use-case that I've outlined.

**Comment by duglin** [comment]
@ac360 can we close this now or do we still need to keep it open?  If we want to save the specifics of the demo, either for posterity or so we can continue to have it running, perhaps we could put this info into a wiki page instead?

**Comment by ac360** [comment]
Let's close it!
