### ISSUE TITLE
Discuss renaming 'Object' to something else in our Attribute type system section

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#167]
See https://github.com/cloudevents/spec/pull/152/files#r181143546 for more info.

Assigned to @clemensv

**Comment by clemensv** [comment]
Sent email to the mailing list:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cncf-wg-serverless/qKW4mYNvZYo/XrPREoppBQAJ

**Comment by clemensv** [comment]
Last call.

**Comment by inlined** [comment]
My suggestion from the meeting still stands. I propose `any` or `var`. These should feel comfortable to JS devs and don't overload the meaning of Object, which is distinct from string or array in JS.

**Comment by duglin** [comment]
Either `Any` or `Object` are ok with me.

**Comment by duglin** [comment]
@clemensv any update on this one?

**Comment by duglin** [comment]
During the 6/15 f2f we agreed to use "Any". Clemens to write-up a PR
