### ISSUE TITLE
Show sample json serialization for each context attribute

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#17]
I think it would be good to show some sample json serialization for each context attribute so there is no ambiguity around what it would look like. It would also be good to show what a complete "context" object would look like.  These actually might not be "samples" - by that I mean it might be good to normatively say something like "When serialized in JSON, the format of the event MUST adhere to the following...".  We'll see...

**Comment by yaronha** [comment]
I suggest to have language struct definitions (e.g. in Go), there can be multiple decode/encode options for the same message (e.g. Json, gRPC, ..)

**Comment by ac360** [comment]
@duglin I like this idea.  Perhaps putting the JSON example and the language struct examples in an `examples` folder in the `spec` repo would be best for this.
