### ISSUE TITLE
Will aligning on RFC6839 decrease interoperability?

### ISSUE THREAD

**Issue by inlined** [cloudevents/spec#175]
Bug filed to note concern from #148 (HTTP transport and JSON mapping). We should investigate how much software in the field will have difficulty handling the content-type proposed in the [JSON structured content mode](https://github.com/cloudevents/spec/blob/master/http-transport-binding.md#32-structured-content-mode).

The content-type `application/cloudevents+json` is completely valid per [RFC6839](https://tools.ietf.org/html/rfc6839#section-3.1), though not all software implements all specs. Some off-the-shelf HTTP frameworks will fail to implement RFC6839 and will not recognize that mime types ending in "+json" should use JSON parsing middleware. 

In order to prevent confirmation bias, I suggest we design the experiment before we expose ourselves to (more) data. We should agree on what methodology we would use and what amount of software incompatibility is acceptable *before* we do any (further) measurement. E.g. we could decide to weigh software by its predicted number of installs or its predicted percent of global traffic (e.g. by gartner reports). We could then decide that X% incompatibility is acceptable. Or we could survey which stacks we want to support as committee members.

**Comment by duglin** [comment]
At the 6/15 we agreed wait until we're close to v1.0 (ie. when we reach v0.9) to see what kind of feedback and user/implementation experience there is around this.

**Comment by duglin** [comment]
Given our discussion this week about trying to get to v1.0 soon, I think we need to revisit this one.
Given what implementation experience is out there and that no one has mentioned this as an issue yet, I'm inclined to think that our current spec is ok w.r.t. RFC6839.  Has anyone run into any issues with it and just not spoken up?

If you don't speak up, this issue might be closed so don't be shy

**Comment by deissnerk** [comment]
I ran into some related issue during the preparation of the demo for KubeCon EU 2019, but it could be solved. I still think that `application/cloudevents+json` is a good solution. IMHO the solution is that frameworks should correctly implement RFC6839.

**Comment by duglin** [comment]
Agreed to close on the 6/13 call.
