### ISSUE TITLE
Is eventID an attribute of the context?

### ISSUE THREAD

**Issue by ljnelson** [cloudevents/spec#186]
Thanks for the beginnings of this specification; it looks very interesting!

The [specification says](https://github.com/cloudevents/spec/blob/master/spec.md#context-attributes):

> Context is designed such that it can be delivered separately from the event data

The context includes `eventID` as an attribute.  It also includes `eventTime` and `eventType` (and `eventTypeVersion`).

I wonder if these are really attributes of the event itself, not attributes of the context it contains.

(Similarly as noted by [another issue](#119) `data` is not an attribute of context either.)

If I have a context in my hand, I would assume that if it is truly a separate concept I should not be able to "traverse" semantically from it to either the data it describes or the event it rode in on.  Otherwise it is not truly separate from either.

Please also see #187.

**Comment by ljnelson** [comment]
IMHO the language needs to be tightened up then overall, and I would offer a proposal, but I'm not sure which way to go due to the ambiguity.  You write above that "certain bits of metadata about the event (or occurrence)" can be extracted—but which is it?  The event, or the occurrence?  And effectively you're saying: there's stuff in the event, and some of it is the data, and the rest of it is stuff that can be extracted—if that's true, why bother to introduce the concept of a "context" at all?  Just speak about the event and its data payload.

Thanks for responding to these issues; I think it's an interesting discussion.

**Comment by duglin** [comment]
If we just talked about the "event data" and the "event metadata", would that help? That's pretty much how I view it, regardless of the specific terms we use.

**Comment by ljnelson** [comment]
See [my comment on #188](https://github.com/cloudevents/spec/issues/188#issuecomment-387810009).

**Comment by ljnelson** [comment]
Discussion carried on in #188; closing this issue per request.
