### ISSUE TITLE
Cardinality of concepts?

### ISSUE THREAD

**Issue by ljnelson** [cloudevents/spec#187]
Suppose I have some data (in the specification's sense of the word):

    foo

…and I want to describe that data, loosely speaking, with a context i.e.:

    contentType: text/plain
    extensions: some kind of map representing extensions here
    etc.

…and so on.  (My notation above is just to illustrate concepts; not supposed to be a binding.)

Now:

* Should I be able to broadcast two or more distinct events about the same data (`foo`) described by the one context (`contentType: text/plain ; extensions: ... etc.`)?
* Can a [context definitionally describing "circumstantial information about the Occurrence"](https://github.com/cloudevents/spec/blob/master/spec.md#context) be conceptually shared between events?
* Can one Occurrence appear in two events?  Must those two events' contexts be non-equal?

**Comment by duglin** [comment]
My 2 cents:
> Should I be able to broadcast two or more distinct events about the same data (foo) described by the one context (contentType: text/plain ; extensions: ... etc.)?

Yes

> Can a context definitionally describing "circumstantial information about the Occurrence" be conceptually shared between events?

Yes

> Can one Occurrence appear in two events? Must those two events' contexts be non-equal?

Yes. No, not per the spec.

IMO, the spec doesn't really control much with respect to the semantics of what an event is or how/when an event is created. It just tells you where to put certain data so people can easily find it. Its up to other specs (or implementations) to add in constraining semantics (like duplicate detection) if they need it.

**Comment by duglin** [comment]
If anyone disagrees, or @ljnelson if you think I didn't address your concerns, please speak up and I'll reopen the issue.

**Comment by ljnelson** [comment]
Thanks, @duglin.  

You write above, paraphrased, that a single context, consisting of its attributes and nothing else, may be placed into two distinct events.

In that case, what would the value of the `eventID` context attribute in both cases be?  The specification implies, but does not state, that this is a property of the event, not of the context that a given event might share with other events.  So surely this should not be duplicated?

You also write:

> the spec doesn't really control much with respect to the semantics of what an event is

…but the specification [defines it](https://github.com/cloudevents/spec/blob/master/spec.md#event), and takes care to define it as being separate from (a) a context and (b) the event data.  

In all of this, what I'm trying to pin down is: is it possible that a number of context attributes really describe the event itself (e.g. eventID, eventType, eventTime), or the occurrence it describes (maybe eventType should be occurrenceType? maybe eventTime should be occurrenceTime? maybe eventID should be occurrenceID?), and hence should be moved to a different "area" of the specification talking about attributes of the event itself, or the occurrence itself, and not of an event's context (which can be shared among events)?

**Comment by duglin** [comment]
I feel like this issue is very much related to some of the other ones you've opened. Is it possible to focus the discussion on just one issue instead of spreading things between issues? Or am I missing it and each is really a distinct idea?

**Comment by ljnelson** [comment]
Discussion carried on in #188; closing per request.
