### ISSUE TITLE
Conformance with JSONAPI Spec

### ISSUE THREAD

**Issue by jugaadi** [cloudevents/spec#189]
I propose [JSON Event Format(v0.1)](https://github.com/cloudevents/spec/blob/v0.1/json-format.md) to be defined as an extension of [JSONAPI format](http://jsonapi.org/format/) as both solutions appear to be similar. 
Due to its existing mature ecosystem, it can handle more usecases and will also help us onboard developers easily.

cc: @wycats

**Comment by jugaadi** [comment]
cc: @json-api

**Comment by duglin** [comment]
@jugaadi can you create a PR, or even just more info in this issue if you don't have the time, with details of how you see our JSON mapping doc changing to align with your proposal?

**Comment by duglin** [comment]
Is there any interest in this from the wg? Is there someone willing to champion it? If not we will probably close it in an upcoming call so please speak up.

**Comment by williamhogman** [comment]
On a semi-related note, I think it would be interesting to have the json-format implemented with json-schema.

`JSONAPI` seems to define the transport layer, so its scope seems to be bigger than that off `json-format.md` which could theoretically be a file-on-disk or an http request.

**Comment by duglin** [comment]
Per the 6/28 call - closing the issues since we couldn't find a champion to push this one forward.
