### ISSUE TITLE
Remove "references" section

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#19]
Before we ship a formal release I think we should remove the "References" section that shows what existing providers do for their events. This is very useful today as we work through the initial design, but once we get agreement on our stuff we no longer need to see what other people are doing since it doesn't align with what we're recommending.

Assigned to: @notque

**Comment by ultrasaurus** [comment]
I think this would be good material to keep around as background of what drove some of the design decisions.  Maybe we could create a sub-folder...  I expect / hope we'll also be documenting what we learn about real-world use cases and infrastrucutre that developers need to work with when implementing a system that supports events.  Not sure if these belong together, but could provide context for people understanding the spec.

**Comment by duglin** [comment]
@ultrasaurus you have an AI (AI: Sarah to open an issue for a doc to explain the spec, ecosystem, how it all fits together, etc… work with Yaron), I wonder if that doc would be a good spot for this info, if we keep it around. I just don't think it belongs in our spec.

**Comment by duglin** [comment]
Closing since this is now done
