### ISSUE TITLE
Possible alignment with IETF Security Event Token

### ISSUE THREAD

**Issue by independentid** [cloudevents/spec#190]
This specification has surprising alignment with the IETF's SET Token format which is going through final publication process to RFC.

It might be interesting to discuss possible alignment routes and shared common delivery methods to bring these initiatives together.

For more information see: 
SECEVENTS Working Group - https://tools.ietf.org/wg/secevent/
SET Security Event Token Draft - https://tools.ietf.org/html/draft-ietf-secevent-token-10 (in RFC writeup)

An example of usage:
OIDC Backchannel Logout - http://openid.net/specs/openid-connect-backchannel-1_0.html
RISC Risk Incident Sharing and Coordination - http://openid.net/wg/risc/

One of the features of SET as a message format is flexibility for profiling areas (e.g. such as platform) to work independently on a common format.  Technically, because SET is based on JWT (RFC7519), SETs have the ability to be signed (e.g. for after-the-fact verification) and encryption (for end-to-end security).

Comments appreciated.

**Comment by duglin** [comment]
Is there any interest in this from the wg? Is there someone willing to champion it?  If not we will probably close it in an upcoming call so please speak up.

**Comment by duglin** [comment]
Per the 6/28 call - closing the issues since we couldn't find a champion to push this one forward.
