### ISSUE TITLE
AI: research the intersection of tracing and event attributes

### ISSUE THREAD

**Issue by inlined** [cloudevents/spec#197]
As part of the 2018/04/10 call, I was asked to research whether the popular open tracing standards could intersect with [our thoughts on correlation](https://github.com/cloudevents/spec/issues/195). I am opening this bug (to be auto-closed within a week) to document the cursory research.

I looked at Distributed Tracing [W3C](https://w3c.github.io/distributed-tracing/report-trace-context.html), [Repo](https://github.com/w3c/distributed-tracing/blob/master/trace_context/HTTP_HEADER_FORMAT.md) and the [OpenTracing](opentracing.io) project. As far as I can tell, OpenTracing for distributed events is a layer on top of Distributed Tracing (it [reuses the same headers over HTTP](https://github.com/opentracing/specification/blob/master/rfc/trace_identifiers.md)).

I strongly believe that we should integrate OpenTracing into our spec, though there are some reservations for using its fields in correlation context I outlined with in #195:

* **Sequential Correlation**:
  1. Tracing APIs will allow visualization of sequencing in _cascading_ events, but do not help us us order events across requests.
  2. The `traceparent` header is freely changed at cloud boundaries. Clouds use the opaque (and 512B limited) `tracestate` header to restore `traceparent` when a request reenters a cloud if necessary.
  3. Tracing is enabled on a per-request basis. The Distributed Tracing spec has an option to suggest recipients also trace that request, though it is a MAY requirement rather than a MUST requirement for many reasons, including security.
* **Structured Correlation**:
  1. All candidates come from OpenTracing, not the vanilla Distributed Tracing spec.
  1. The suggested concept was OpenTracing's [Span Tags](https://github.com/opentracing/specification/blob/master/specification.md#set-a-span-tag). These are not a good fit because they aren't propagated across hops.
  1. [Baggage items](https://github.com/opentracing/specification/blob/master/specification.md#set-a-baggage-item) are a slightly better fit, though it has the opposite stance on propagation. If an action triggers another event, that second event would contain all the baggage items of the first event (feature or bug?)
  1.  OpenTracing is an extremely abstract spec. E.g. the golang version of OpenTracing [only has mock support for baggage items](https://github.com/opentracing/opentracing-go/search?utf8=%E2%9C%93&q=SetBaggageItem&type=) and it [seems like any key/value label pair is expressed as a raw HTTP header](https://github.com/opentracing/opentracing-go/blob/master/propagation.go#L64)

**Comment by inlined** [comment]
As an additional note, I now see that Distributed Tracing also has a "Correlation-Context" header, which might suit our needs.

https://github.com/w3c/distributed-tracing/blob/master/correlation_context/HTTP_HEADER_FORMAT.md

**Comment by duglin** [comment]
@inlined is there anything for us to do on this since you've opened up https://github.com/cloudevents/spec/pull/227 ?

**Comment by duglin** [comment]
I'd like to propose that we close this since we've adopted #227. Please speak up if you think otherwise.

**Comment by duglin** [comment]
on the call today we agreed to close this issue - we can reopen if new info comes up.
