### ISSUE TITLE
Website SSL certificate problem

### ISSUE THREAD

**Issue by tobilg** [cloudevents/spec#199]
I'm seeing a `NET::ERR_CERT_COMMON_NAME_INVALID` when I try to access [https://cloudevents.io/](https://cloudevents.io/). The certificate points to github.com

**Comment by leecalcote** [comment]
Another member of the community pointed this out during KubeCon last week. Thanks for capturing this @tobilg.

**Comment by duglin** [comment]
See: https://github.com/cloudevents/cloudevents.github.io/issues/2

**Comment by duglin** [comment]
Closing this one since https://github.com/cloudevents/cloudevents.github.io is the more appropriate repo to deal with the issue.
