### ISSUE TITLE
Before 1.0 I would like to discuss extension "graduation" process.

### ISSUE THREAD

**Issue by inlined** [cloudevents/spec#201]
If extensions are a breeding ground for potential new standard fields, it would be helpful for us to define what graduation entails. Extensions are often compared to x- attributes in headers or CSS properties, though many of these are widely considered to be a mistake by some in the community. IMO, the worst case scenario is that an extension graduates, the early adopting event providers must double send all extension data, and the final customer code must be prepared to handle the same semantic data from two different locations.

**Comment by duglin** [comment]
tagged for v1.0 & I agree we should have our extension process/goals/etc... before v1.0.

**Comment by duglin** [comment]
@inlined in https://github.com/cloudevents/spec/pull/225 I propose that extensions don't look any different from spec-defined attributes w.r.t how they are serialized. Therefore, when one graduates and is no longer an extension, no code needs to change - just its standing within the spec. Does that help?

**Comment by inlined** [comment]
I saw that. I need to think about ramifications of both; this is probably the best path forward though.

**Comment by duglin** [comment]
Given our current resolutions w.r.t. extension handling I think we can close this one. Please speak up if you think otherwise.

**Comment by duglin** [comment]
on the call today we agreed to close this issue - we can reopen if new info comes up.
