### ISSUE TITLE
Usage-based criteria for 1.0

### ISSUE THREAD

**Issue by inlined** [cloudevents/spec#202]
Though I think it's fine to label a release 1.0-candidate-1, I hope we don't imply any sort of stability guarantees until we have some usage in the market to help us vet our assumptions. What should our usage goals be before we certify a spec as 1.0?

**Comment by duglin** [comment]
I added this to the agenda for tomorrow, and have a proposal for us to shoot arrows at:

```
- When is v1.0 ready?
No more v1.0 issues/PRs
Other criteria?
# of impls?
# of uses in production?
Unchanged w/o major issue for X months?
Proposal: 3 uses in production & 3 months of maturation (after all major v1.0 issues are resolved)
```

**Comment by duglin** [comment]
We, sort of, discussed this during last week's call. There was a general consensus to get to v1.0 quickly as we think we're nearing the end. So, everyone, please be thinking about what kind of measuring stick we want to use to know when we think we're ready for v1.0.  E.g. is it just "no more open issues" or do we want to include some kind of "real world" usage? 

w.r.t. real-world usage, I know of:
- Knative
- MSFT Event Grid
- Adobe GDPR API
- Serverless.com

and I think there are more but I can't recall them right now. Please add others to this issue.

**Comment by duglin** [comment]
I'm going to assume that if we adopt a variant of my "update the roadmap" PR, that this line: https://github.com/cloudevents/spec/pull/462/files#diff-cd4a1b36ed2b93cfc52abf77a7d25d03R72
`Decide on duration and exit criteria for 'verification & testing' period` will cover this issue.

**Comment by duglin** [comment]
On the 8/29 call we agreed that the current usage of CloudEvents (see https://github.com/cloudevents/spec/issues/202#issuecomment-500131400 and https://drive.google.com/open?id=16PFtHwUVHv91RIXk9mva0Jfj6brYWwmW ) should cover things. So we agreed to close this issue.
