### ISSUE TITLE
CE Client SDK

### ISSUE THREAD

**Issue by yaronha** [cloudevents/spec#205]
Now that CE is starting to shape up we may want to provide client side language bindings and few protocol implementations to ease on CE adoption 

i.e. a client App in Py, Go, Java, Js, .. uses the lib to submit an event. the lib has pluggable transport, can start with HTTP, AMQP, Kafka, .. and cloud providers or vendors can add their own transports to it.

The work can be divided by all of us and can be used for testing or for apps that want to submit events, etc. 

seems like it boils down to 3 calls: init, destroy, submit 

Yaron

**Comment by duglin** [comment]
adding to "additional work stream list"
