### ISSUE TITLE
Brainstorm on how to move to a "normal" LGTM PR review process

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#21]
Since today we don't have a defined set of "maintainers" to approve PRs we decided to follow a model that more akin to how a standard body works. Which is, sort of, ok for now, but not ideal for a variety of reasons - biggest being that not everyone can make the calls.

I'd like to use this issue to track ideas for how we migrate to a "maintainer" process and, in particular, how we identify the initial set of maintainers. It might be as simple as take nominations and vote - I dunno.  But let's use this issue to gather ideas and then we'll work on creating a PR with a proposed solution.

**Comment by duglin** [comment]
For reference:
- company activities: https://cloudevents.devstats.cncf.io/d/5/companies-table?orgId=1
- company PRs: https://cloudevents.devstats.cncf.io/d/5/companies-table?orgId=1&var-period_name=Last%20decade&var-metric=prs
- people activities: https://cloudevents.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1
- people PRs: https://cloudevents.devstats.cncf.io/d/9/developer-activity-counts-by-repository-group-table?orgId=1&var-period_name=Last%20decade&var-metric=prs&var-repogroup_name=All&var-country_name=All

**Comment by duglin** [comment]
I"m going to suggest that we close this - does anyone have any concern about this?

**Comment by jskeet** [comment]
Given that @duglin generally manages the PRs for the specs, if he's happy with how things are working at the moment, that's good enough for me :)
