### ISSUE TITLE
Path Context Attribute

### ISSUE THREAD

**Issue by lfourie** [cloudevents/spec#22]
This is a proposed metadata attribute (from Context Attribute Backlog):

path

    Type: String
    Description: The destination endpoint address (e.g. URL) or target topic

**Comment by duglin** [comment]
Given the spec has this sentence:
```
Events are considered to be facts that have no given destination.
```
I believe we can close this issue as something we will not do.

**Comment by SeanFeldman** [comment]
Agreed.

**Comment by duglin** [comment]
I'll wait one more day and then close this. If you think we need to keep it open please speak-up.

**Comment by duglin** [comment]
Closing per WG agreement
