### ISSUE TITLE
content-type context attribute

### ISSUE THREAD

**Issue by lfourie** [cloudevents/spec#23]
This is a proposed metadata attribute (from Context Attribute Backlog):

content-type
    Type: String
    Description: The data encoding scheme (e.g. application/json). The data content type.
    Constraints:
        Required if the event contains a body.

**Comment by duglin** [comment]
#59 and this are duplicates but #64 will close both - leaving this open anyway only because of my question here: https://github.com/cloudevents/spec/pull/64#issuecomment-363609112
