### ISSUE TITLE
Do we need both binary and structured encoding?

### ISSUE THREAD

**Issue by inlined** [cloudevents/spec#239]
Recap from the F2F meeting on June 15, 2018.

The structured encoding has the benefit of being fully self contained; a simple relay can know that it has forwarded a CloudEvent losslessly. An events pipeline can simply stream HTTP bodies to disk*

The binary encoding has the benefit of simplicity; the idea of cross-encoding doesn't apply, it doesn't invent a new MIME type, and it is easier for IoT devices.

Our compromise was to define both formats and require every implementation to support both. This seems like the worst of both worlds because any conforming library must support edge cases of two encodings and no system can assume any optimizations of either.

Do we really want two formats? Can we drop one?

(*) Can it though? That sounds like extensions which have HTTP header mappings must also be part of the content body, which feels wasteful.

Assigned to: @inlined

**Comment by duglin** [comment]
> no system can assume any optimizations of either.

Can you elaborate on this one? Why can't an event consumer optimize one, or both, of the forms?

**Comment by inlined** [comment]
Maybe I should be careful with those RFC 2119 words, they often mean I'm articulating poorly or wrong. In this case I might have just worded it too strongly. 🙂

I know Clemens has been particularly worried about disk layouts of events. In the structured encoding, a zero-copy disk serializer is trivial. I assume (without having tried) that verifying a zero-copy fast-path is harder when the binary encoding requires an in-memory struct but the structured encoding does not.

As a platform developer, I mostly wish I knew which format my data would encode . As it is now, I have more than twice the development work (both formats + some abstraction layer) and I don't know what's most important to optimize until I see usage grow.

**Comment by duglin** [comment]
Ah, ok, thanks that helps me understand your concern.

**Comment by duglin** [comment]
@inlined you ok if I assign this one to you?

**Comment by duglin** [comment]
@inlined do you still want to pursue this one?

**Comment by duglin** [comment]
What do people think about this one?  Recently I've been thinking that requiring "binary" should be sufficient since the more I play with things the more I really like the idea of not changing the existing event that's flowing and just adding some extra metadata do it.

**Comment by bluemonk3y** [comment]
@duglin Yes, I would agree, furthermore, from a security perspective it would make sense to prevent a payload from being modified

**Comment by cneijenhuis** [comment]
I can't really articulate why, but I always felt that the "structured" mode is what a serverless dev will prefer. JSON is commonly used, and small-scale optimizations like shaving a few bytes off here or there are not a priority.

I don't have strong proof, but e.g. when directly invoking an AWS Lambda function, you can easily pass a JSON body, but not HTTP headers.

**Comment by duglin** [comment]
@cneijenhuis I think that's where my head was at originally as well when we first started CE. And I actually think that makes a lot of sense in environments like Knative where they normalize all events into a common format before passing them along to the service. This allows for the service to be written w/o regard to the transport/format of the original request.  That's really nice to me.

But then when I think about cases where the event isn't going through some middleware that's morphing things, the format and transport chosen by the event producer was picked for a particular reason (I assume :-) ), and I would think in those cases binary makes more sense since that CE isn't trying alter that decision - it's just enhancing it.

Maybe we're ok where we are... both have their places in this world.

**Comment by duglin** [comment]
Been thinking about this one and I'd like to proposal that we close this issue with no action.
I think both formats are needed. We could decide to not require both, but that's a separate issue and I think it's clear that some people have a need for each so dropping one would probably not help.  Thoughts?

**Comment by timbray** [comment]
If it were up to me I'd go with just one encoding and it'd be JSON. The world runs on it, apps that process it ignore fields they don't understand, and software that processes it is acceptably fast. Also, as a developer, I appreciate its human-readability.

**Comment by duglin** [comment]
Just as a data point... Knative uses the binary mode - at least from my experience.

**Comment by duglin** [comment]
Agreed to close on the 6/20 call - we decided to keep both forms.
