### ISSUE TITLE
Create a common presentation to introduce and discuss Cloud Events

### ISSUE THREAD

**Issue by markpeek** [cloudevents/spec#249]
At the SF f2f meeting we were discussing community outreach and how best to discuss Cloud Events with people. One idea was to create a common presentation to allow people to present at meetups or other conferences. This issue will track this action item.

Assigned to: @markpeek

**Comment by duglin** [comment]
@markpeek any update on this one? Part of me wonders if a "common" presentation would be feasible given people's natural desire to customize things for their own purposes. I do however like the idea of sharing presentations so people can leverage each other's work/ideas. Perhaps we just need to remind people of https://github.com/cloudevents/spec/tree/master/share every few months?

**Comment by duglin** [comment]
@markpeek with the KubeCon presentations we have do you still think we need this one?

**Comment by duglin** [comment]
@markpeek given we have these: https://drive.google.com/open?id=1n88hQ3wIrtRDtMGFM7geJcP2NFyDdCx5  do you think we can close this issue?

**Comment by duglin** [comment]
Executive decision :-)  going to close this as I think we have slides available for people to use. @markpeek feel free to re-open if I jumped the gun.
