### ISSUE TITLE
Logo Improvements

### ISSUE THREAD

**Issue by austencollins** [cloudevents/spec#259]
If you have suggestions for the CloudEvents logo design, please post them in this thread before Thursday, July 5th.

I recommend posting each design concept as a separate comment, so others can give them a thumbs-up and we can use that to get a signal of what people enjoy most.

**Comment by cneijenhuis** [comment]
![cloudevents](https://user-images.githubusercontent.com/2638512/42099620-33aa4806-7bbe-11e8-9bee-929b68991a00.png)

How can we send a message to someone we've never heard of? With a balloon mail!

> The goal of the CloudEvents specification is to define interoperability of event systems that allow services to produce or consume events, where the producer and consumer can be developed and deployed independently.

I believe a balloon mail is a great metaphor for the independence between producer (who just sends off the message without specifying a destination) and consumer (who may find the message in his backyard or during a walk in nature). It's also easy to associate with cloud(s).

Credit for the logo goes to my wife @silkeneijenhuis!

**Comment by ac360** [comment]
@cneijenhuis The balloon is clever.  Nice job.

**Comment by ac360** [comment]
![ce-normal-white](https://user-images.githubusercontent.com/2752551/42334041-32f1b8a0-8031-11e8-992b-21d2bd7f4c7a.png)

**Comment by ac360** [comment]
![ce-normal-black](https://user-images.githubusercontent.com/2752551/42334054-3a34aec4-8031-11e8-857a-ffbff0ea57ad.png)

**Comment by ac360** [comment]
![ce-normal-horizontal-white](https://user-images.githubusercontent.com/2752551/42334069-41000f3c-8031-11e8-942b-130a2c0c364b.png)

**Comment by ac360** [comment]
![ce-balloon-blue](https://user-images.githubusercontent.com/2752551/42334102-4d34f650-8031-11e8-82db-4aafe35d8492.png)

**Comment by ac360** [comment]
![ce-balloon-red](https://user-images.githubusercontent.com/2752551/42334110-52bd7066-8031-11e8-8c3c-42c82e4613e7.png)

**Comment by ac360** [comment]
![ce-balloon-straight](https://user-images.githubusercontent.com/2752551/42334116-58b23240-8031-11e8-9242-91f39b14093a.png)

**Comment by duglin** [comment]
Today's logo: 
![image](https://user-images.githubusercontent.com/1944671/42334120-80d61c0a-804a-11e8-9cfe-03af4618bda8.png)

**Comment by ac360** [comment]
![ce-balloon-red-horizontal](https://user-images.githubusercontent.com/2752551/42334133-62553068-8031-11e8-97c1-1a332631f9bf.png)

**Comment by leecalcote** [comment]
This [revision](https://github.com/cloudevents/spec/issues/259#issuecomment-402769871) keeps the initial version intact and is a nice improvement.

**Comment by alexellis** [comment]
Liking the refreshed font and (e) within a cloud as an icon.

**Comment by markfisher** [comment]
one idea for delineating the e would be adding an arrow where it meets the outline of the cloud itself

**Comment by ac360** [comment]
![cloudevents-logo-gap](https://user-images.githubusercontent.com/2752551/42641000-612dc3a4-85a8-11e8-8026-0686bc65a25d.png)

**Comment by duglin** [comment]
I believe we can close this one now.  Will add to the next call but please speak up if you think otherwise.
