### ISSUE TITLE
method context attribute

### ISSUE THREAD

**Issue by lfourie** [cloudevents/spec#26]
This is a proposed metadata attribute (from Context Attribute Backlog):

method
    Type: String
    Description: The (http) method used in the call

**Comment by duglin** [comment]
I think this brings up a broader question of whether the scope of a CloudEvent is just what an event looks like while it is being transported between the producer and the consumer, or is there the expectation that the CloudEvent will also be the basis for what is passed to the Function/software processing the event?  See https://github.com/cloudevents/spec/pull/124#discussion_r177907627

If we expect the CloudEvent structure to be the thing we pass along to downstream code, then:
- we may need to think about how the receiving infrastructure might need to modify the CloudEvent data - for example to add additional information like what is being proposed in this issue. For example, would the infrastructure add it under `extensions` or as a top-level context attribute? Guidance, at a minimum, might be good.
- if so, we should consider defining what some of these added-post-transport attributes might look like so there's consistency/interop for Function authors?

**Comment by duglin** [comment]
Does anyone think that this should be a REQUIRED attribute? Just asking for the purposes of identifying v0.2 work items. I'm guessing no one does but if I'm wrong and you think all CloudEvent should have this attribute then please speak up.

**Comment by duglin** [comment]
I'd like to get some input from some of the SDK developers on this one - @ac360 @markpeek @jlbutler

When I think about the in-bound processing of a framework/SDK, it seems very possible that they would like to offer some transport level information (like http method) to their application. However, this feels more like information that would go into a`context` object than into the event. Do people agree?  Should we close this?

**Comment by duglin** [comment]
My interpretation of the mood of the group is that a "method" attribute is probably not appropriate to add to the spec. And therefore I'm thinking we can close this issue w/no action.  What do people think?

**Comment by duglin** [comment]
Agreed to close on the 6/13 call.
