### ISSUE TITLE
Discuss forwarding of properties

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#266]
from: https://github.com/cloudevents/spec/pull/255/files#r200341390

> In the CloudEvents main spec we should indeed discuss routing/forwarding explicitly and make a hard rule that middleware MUST forward all elements of an event, including those that have been mapped onto transport constructs.

ping @clemensv

**Comment by jdstuart** [comment]
Can this be closed in favour of #290 ?

**Comment by duglin** [comment]
ok I'm going to suggest that we close this one and continue the discussion in #290. Since its my issue I'll just do it :-)
