### ISSUE TITLE
Add examples to Primer around "properties"

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#270]
At the last f2f @cathyhongzhang took an action to look into creating some additional examples
for the primer related to how properties might appear in the serializations and possibly
add some use cases explaining when each might be used.

Opening this issue just so we don't lose it.

Related to issue #269 

Assigned to: @cathyhongzhang

**Comment by duglin** [comment]
@cathyhongzhang is this still something you want to do?

**Comment by cathyhongzhang** [comment]
We ended up not defining a property bad attribute. I do not have anything to add at this time. This issue can be closed. Thanks.

**Comment by duglin** [comment]
Closing per @cathyhongzhang's comment
