### ISSUE TITLE
Lifecycle of core spec vs serialization/transport-binding specs

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#271]
We need to decide the versioning scheme for our specs. Are they all totally independent or are they grouped into a single unit when considering versioning?

For example, let's say we publish v1.0 of the core, json and http-binding specs.
Then we update the http-binding spec in non-compatible way - meaning it should be bumped to v2.0.

Do we bump all specs to v2.0 or just the http-binding spec? If just the http-binding spec then how does a receiver of a CloudEvent know which version of the http-binding spec is being adhered to since the CloudEventVersion property will still be at v1.0 ?  This might lead us to group all spec together.

But, if we do that then we may be forced to bump our version number on the core spec more often than we would like to. Any breaking change to ANY of our specs would cause all specs to be bumped. Not ideal either.

However, one thing to note... while a break change does mean the major version number must be incremented, a major version change does not necessarily mean that there were any breaking semantic changes to the spec. In other words... we can choose to go from v1.0 to v2.0 any time we want even if there are NO breaking changes. This would impact implementations because it would make their version compatibility checks harder of course.

**Comment by duglin** [comment]
Proposal:
- w.r.t. major version numbers, treat all specs as a single group. Meaning, no spec can go to v2 until they all do
- each spec can have a minor version bump as needed
- each spec will have a section to indicate which version of its dependent specs is required. For example: `Requires v1.0, or higher, of the CloudEvents spec`, or `Requires v1.0+ of the CloudEvents spec`.
- document this process someplace in our docs

**Comment by rspielmann** [comment]
Hi @duglin,

> Do we bump all specs to v2.0 or just the http-binding spec? If just the http-binding spec then how does a receiver of a CloudEvent know which version of the http-binding spec is being adhered to since the CloudEventVersion property will still be at v1.0 ? This might lead us to group all spec together.

Just a couple of unsorted thoughts from me:

- I think that the proposals from your second comment do not give an answer to the question how a receiver will know the version of the transport binding being used, even if a transport spec only receives a minor version bump. Might it be necessary to define a transport-specific property (e.g. a HTTP header, JSON property, ...) that states the version of the transport binding being used? I could also imagine the combination "old" transport binding and "new" CloudEvents version. What should happen then?
- Generally, I think that the CloudEvents core spec should be version-independent from transport/serialization/younameit binding specs. This would also ease the future addition of more transport bindings because if everything was coupled into a single version you would probably have to do a full spec release each time a new transport/serialization/... binding gets added.
- I fully agree with the last two enumeration items from your proposal.

Kind regards,
Robert

**Comment by duglin** [comment]
@rspielmann My current thinking is that if all of the specs are versioned together, then the CloudEvents version string should at least tell them which major version of that transport is being used. And if all minor versions are backwards compatible (within the major version), then would a receiver need to know anything more? All new bits of information in newer minor versions would always need to be optional.

In general I agree with you that it would be nice if the core spec were versioned independent from the transport specs, but wouldn't we then get into some painful explosion of possible combinations of core spec usage with transport specs?  Meaning, each transport would have to define how to process each version of CE - even really old ones.  By grouping it all together we limit the work to just that one version of the specs.

If we did keep things separate, how do you see it working? Each protocol would need to define a mechanism by which it would advertise its version? e.g. `CE-HTTP-Version` ?  Would we need to define some kind of version negotiation?  One nice thing about grouping everything together is that if you support vX of CE then you know exactly what each protocol looks like, no need for negotiations - I think.

Would love to hear what others think

**Comment by clemensv** [comment]
I would suggest that we version all the official spec documents as one, but maintain document level revision counters.

The JSON spec might be "Version 0.2" reflecting the overall release and have a document revision number "8" reflecting the significant (non typo) fixes that went into the document. 

Nobody will be able to keep track of what is what if we let the version numbers diverge.

**Comment by duglin** [comment]
@clemensv w.r.t. the doc version number, can you elaborate on when you see that changing or how people will use it? Does it change on each commit? Just when we think enough changes have gone into to justify a new "doc revision" label? 

I'm wondering if the net result of the "document revision number" is the same as the commit hash - meaning its really only there to give someone a concrete version to reference if they want an intermediate version. But, most people will really wait for an official release and those would be the official vX.Y versions of the group of specs.
