### ISSUE TITLE
Consider Providing JSON Schema Documents

### ISSUE THREAD

**Issue by dmlb2000** [cloudevents/spec#272]
http://json-schema.org/

Seems like there's a schema in JSON for describing JSON. I think it would make sense to have some json schema documents that match the described spec in the markdown.

**Comment by dmlb2000** [comment]
If this is something that is desired I can take a stab at a pull request for it.

**Comment by williamhogman** [comment]
Yes,

I’ve thought of that as well. If you wanna do a PR it be happy to merge :)
