### ISSUE TITLE
Request for transport: RFC8030 Generic Event Delivery over HTTP2 Push aka "WebPush" Protocol

### ISSUE THREAD

**Issue by rektide** [cloudevents/spec#280]
I would love to see a transport specified that uses [Generic Event Delivery over HTTP2 Push (RFC8030)](https://datatracker.ietf.org/wg/webpush/documents/) (aka it's working draft name, "webpush protocol"). Webpush is already an [enormously widely deployed transport](https://caniuse.com/#feat=push-api) for sending events. It allows a consuming client to connect to an HTTP endpoint, & as long as the connection is open it can receive event messages.

It also provides a means for servers to [let clients listen to a "set" of message-streams](https://tools.ietf.org/html/rfc8030#section-4.1) quickly, which can be a very important capability if a client needs to subscribe to many event streams.

Whereas the current HTTP transport says,

> This specification does not prescribe rules constraining the use or handling of specific HTTP methods

, RFC8030 already has a well defined transport that fits closely with the mission & purpose of CloudEvents, and harmonization of the two under the CloudEvents umbrella could lead to a harmonious, easy to use, standard way of performing CloudEvent delivery atop a well-known widely-implemented event-delivering protocol. Please consider creating a transport for RFC8030.

**Comment by duglin** [comment]
@rektide is this something you'd be willing to create a PR for?

Does anyone have any opinion on this? Or want to volunteer?

**Comment by clemensv** [comment]
Our HTTP transport binding defines how to map a CloudEvents to a HTTP message. The HTTP/2 push channel regular HTTP headers and HTTP entity bodies, so I think there's not a lot of specific work that needs to be done to support this and RFC8030 is pretty specific about how to set up the channel.

**Comment by duglin** [comment]
@rektide any thoughts on the above comment? If you agree I think we can close this issue.

**Comment by duglin** [comment]
@rektide you ok with me closing this given @clemensv's comment?  If I don't hear back soon this will be closed with the assumption that our HTTP spec covers this.

**Comment by duglin** [comment]
On the 6/28 call we agreed to close this with no action
