### ISSUE TITLE
authentication context attribute

### ISSUE THREAD

**Issue by lfourie** [cloudevents/spec#29]
This is a proposed metadata attribute (from Context Attribute Backlog):

authentication
    Type:
    Description:

**Comment by duglin** [comment]
Is this meant to be the authentication related to the delivery of the message/event or something else?

**Comment by duglin** [comment]
Does anyone recall what the intent of this attribute was?  @ac360 its from the backlog so perhaps you recall?

**Comment by duglin** [comment]
I'd like to propose that we close this one. I have not heard of anyone actively proposing that we need this. If during our future "security" related discussions we find that we need something like this then we can reopen it. Thoughts?

**Comment by duglin** [comment]
on 6/7 call we agreed to close this
