### ISSUE TITLE
Immutability of event context

### ISSUE THREAD

**Issue by deissnerk** [cloudevents/spec#290]
In the discussion of #277 I raised the question, if extension attributes can be changed or added by middleware, or if the event context is immutable. I remember that during the f2f meeting in Copenhagen @clemensv proposed to have two property bags, one for properties added by the source, and one for annotations added by middleware. AFAIK this is quite similar to what AMQP 1.0 supports. If we decide to abandon the idea of property bags for extensions, how do we handle the question of information added to the context by middleware? There are quite a few options:

1. Don't support information added by middleware. An event is immutable. If anything is changed, it becomes a new event with a new ID.
2. Allow adding of context attributes by any component on the way.
3. Add a dedicated property bag for information that is added after event creation. This could be part of the context or on the same level as data and context.

**Comment by cneijenhuis** [comment]
A question regarding 1. - if the middleware produces a new event, then the middleware is the (new) event producer. Therefore, wouldn't it be forced to set itself as the `source`?

On one hand, that looks right (one shouldn't be allowed to "impersonate" another event producer), on the other hand it will pose problems to the consumer (expected "example.org/user/...", got "middleware.com/foo").

**Comment by Vlaaaaaaad** [comment]
Regarding option 1( immutable events), if a new event is to be created two options seem to be available:
- make a bad clone of the initial event( reuse time and event id for example, see _Eliminating the who - no middleware concept idea_ section in https://github.com/cloudevents/spec/pull/128#issuecomment-395239721) 
- some type of embedding would have to be done which would leak transport and middleware details into the event


The security( signing and encryption) discussion will also have an impact on this. Also, https://github.com/cloudevents/spec/issues/266 seems to be related

**Comment by duglin** [comment]
Do we even need to make a statement about this at all? Whether a middleware acts like "a new source" or it acts more like a proxy is really up to it. I'm not sure CloudEvents itself needs to say anything either way.

There might be some best practices that middleware might want to think about/do - but for the most part it seems like our spec should not get into the processing model side of things, and stick with just how things appear on the wire.

**Comment by deissnerk** [comment]
@jdstuart I agree with your assessment of the options. My preference would also be option 3. 

@Vlaaaaaaad I also agree to you. I have my doubts about middleware cloning the original event. If an event is propagated through multiple channels, you might end up seeing different "versions" of the same event. I also agree on the nesting option.

@cneijenhuis The questions regarding the event source is a good point. 

@duglin Our design goals state:
>The metadata is not meant to duplicate any of the application data of the event itself, rather it is just the minimal information needed to route the request to the proper component that will process the event.

So the whole point of CloudEvents is to define some data that is needed for processing the event on its way from producer to consumers. To do so, we will need some assumptions about this processing.

**Comment by BenBeattieHood** [comment]
Isn't any middleware essentially an event source in itself? An event that has been enriched would be considered a new event, emitted from a separate domain responsibility. I'm unsure why this wouldn't apply to metadata too?

**Comment by duglin** [comment]
I tend to think of middleware as an event source too - however, whether it changes the `source` attribute is up to it.

I guess I don't yet see the need to differentiate who added an attribute to an event. To the event consumer all they should see (and care about) is the data itself and not who added it, or modified it, along the way. If we start to put data into different bags based on who is adding it then we need to add complex rules for which takes precedence and I think a much simpler model would be to just let the new value replace the old one - then there's no ambiguity or complexity in the processing model. And, keep in mind, there will be some middleware (like proxies) that really will want to modify the original metadata and I don't think its our place to ban those.

I guess I'd like to understand the usecase for why we're even considering such processing rules.

**Comment by sslavic** [comment]
By https://github.com/cloudevents/spec/blob/master/primer.md middleware is, among other things, expected to

> Transformation that changes the event's structure, like mapping from a proprietary format to CloudEvents, while preserving the identity and semantic integrity of the event.

**Comment by duglin** [comment]
Discussed a bit on today's call. @deissnerk will continue to think about possible next steps, but please comment here is you have any comments or thoughts on this topic.

**Comment by duglin** [comment]
@deissnerk have you thought about what you'd like to do with this one?

**Comment by duglin** [comment]
Given all of our previous discussions on this and related topics, what do people think about this adding some text to the primer to indicate:
- middleware can modify the cloudevent being forwarded - we already have text like this already so this may already be done
- there may be times when the middleware needs to act as a proxy vs as a new event-source
- when acting as a proxy, it will typically preserve most of the properties of the cloudevent, perhaps adding new ones if necessary
- when acting as a new event-source, it will typically perform some kind of transformation of the incoming cloudevent and therefore might generate a new `ID` and `source` to distinguish it from the original cloudevent
- however, these are not requirements and a middleware component is free to do whatever is necessary to properly do its job - the above are just common patterns.

@deissnerk any more thoughts on this?

**Comment by deissnerk** [comment]
@duglin 
For some attributes a change really may endanger the integrity of the event. For the event ID the spec says
> MUST be unique within the scope of the producer

If the ID, the event type or the source is modified, this scope of the producer changes. Furthermore, the event time is defined as
> Timestamp of when the event happened.

It wouldn't make sense to change that, if it wasn't an entirely new event. 

There might be transformations for event types or the source field like de-referencing a relative URI reference in the source field, if the event is propagated out of the context where the base URI would be well-known.

In the spec we cannot foresee all the scenarios for changing event context attributes, but perhaps we can somehow define boundary conditions. Uniqueness within the scope of the producer is important.

**Comment by duglin** [comment]
> In the spec we cannot foresee all the scenarios for changing event context attributes...

I think that's my major concern. I'm not sure we can ever come up with normative text for the spec since there are probably good use cases for changing all properties and there are good use cases for not changing them. It just depends on what the middleware is doing, and expected to do. I think the best we could hope for is to write down what we "typically" expect middleware to do (in the primer), but in the end that component needs to get it's job done and we shouldn't stop it. If it does things that people don't like, then people will stop using it. I think it's kind of a self-correcting problem.

**Comment by deissnerk** [comment]
There are some constraints, derived from the existing spec, like the ones I mentioned before. This also relates to #331. If an event ID in combination with the source has to be unique, this has some implications on changes to attributes. If the time is changed, this would be a new event and consequently a new ID as one and the same thing can't happen twice. If the source is changed, uniqueness must be ensured. Etc.

**Comment by duglin** [comment]
But it seems to me that most of those are already covered by the spec and we wouldn't need to repeat it. If the middleware is acting as a proxy for the producer then it would probably still be bound by the original producer-specific uniqueness rules - and it is up to it to do so w/o us telling it how. If it is acting as a new producer then it still needs to abide by the spec, but for its own producer-defined values.

Do you have a proposal for the text you think is needed?

**Comment by evankanderson** [comment]
I think it would be useful to either document that the event context is immutable, or to provide specific guidance about how to modify event contexts. I think [Doug's comment](https://github.com/cloudevents/spec/issues/290#issuecomment-462789951) is on the right track. Example recommendations:

* If the `source` attribute is changed, the `type` and `id` should be updated as well.
* If the `time` attribute is updated, the `id` attribute should also be updated.

**Comment by duglin** [comment]
@deissnerk since this is your issue - what are your thoughts on some of the ideas put forward?

**Comment by deissnerk** [comment]
@duglin 
@evankanderson 's comment is pretty much in line with my comment [here](https://github.com/cloudevents/spec/issues/290#issuecomment-463377759). I'll try to come up with a PR for the primer.

**Comment by deissnerk** [comment]
@duglin @markpeek Just thought about your comments in #388:
> Producers and consumers MAY add or interpret optional attributes. Middleware MUST propagate optional attributes. Middleware that does not should be considered both a consumer and a producer per the primer.

So far we do not distinguish middleware, consumers and producers in the spec, only in the primer. How can we add the MUST requirement from above to the spec without this distinction, if on the other hand in the primer we state that modifying the event context is basically ok?

**Comment by duglin** [comment]
What if we did add those to the spec? Even if just to say that middleware is both a consumer and producer.

-Doug

**Comment by duglin** [comment]
we don't actually defined "event producer" or "event consumer" in the spec, it can't hurt to define them in the terminology section: https://github.com/cloudevents/spec/blob/master/spec.md#terminology

**Comment by deissnerk** [comment]
@duglin Good point, but middleware in my quote of @markpeek above is neither producer nor consumer. I'm thinking about a third role we could call _event processor_ as something that does some processing of the event (even changes) and passes it on. Or perhaps an _event consumer_ would be a special _event processor_ that does **NOT** pass the event on. 
But even then there is some inconsistency regarding middleware. Why MUST middleware forward optional attributes, if we generally allow modifications? By definition deleting an optional attribute would still result in a valid event.

**Comment by duglin** [comment]
Perhaps http ( https://www.ietf.org/rfc/rfc2068.txt ) can help here - I noticed that they distinguish between proxies and gateways, and in particular it says this about proxies:
```

   The extension-header mechanism allows additional entity-header fields
   to be defined without changing the protocol, but these fields cannot
   be assumed to be recognizable by the recipient. Unrecognized header
   fields SHOULD be ignored by the recipient and forwarded by proxies.
```
And I'm wondering if their definition of gateway is similar to this new role you're thinking of:
```
   gateway
      A server which acts as an intermediary for some other server.
      Unlike a proxy, a gateway receives requests as if it were the
      origin server for the requested resource; the requesting client
      may not be aware that it is communicating with a gateway.

```

Need to think more about it, but it seems as though anything that is really just there to help move the event along (either as a proxy or even as the CE wrappering mechanism) and not really meant to add any semantic meaning to the event should probably do its best to not lose any data and that would include extensions.  But something that is actually manipulating the data in some way (to add semantic value), feels more like a gateway and an event producer. And in those cases can choose to forward or drop any data it doesn't think is needed. However, in those cases I'd be inclined to say that the CE properties indicating the event producer (e.g. source) really should point back to this entity and not the original event producer.

**Comment by deissnerk** [comment]
@duglin Interesting thought. I wonder, if we really need to distinguish intermediary and proxy, or if a distinction between intermediary and a consumer that produces a new event is sufficient. In a first step I would add definitions for producer(?), consumer and intermediary to the terminology section of the spec. I saw these terms being used a lot already in the spec and primer. 
It's an interesting question, if a definition of producer is needed with all the ongoing discussions around source and subject. I wonder if our current definition of source as the attribute _describing the producer_ is correct.

**Comment by deissnerk** [comment]
Clarified with #461
