### ISSUE TITLE
Specify if event-type should enforce a type format

### ISSUE THREAD

**Issue by rachelmyers** [cloudevents/spec#31]
Decide and document if the [`event-type`](https://github.com/cloudevents/spec/blob/master/spec.md#event-type) attribute should include a type format.

**Comment by schatekar** [comment]
Does a "type format" tell how `data` is structured? Is this something covered by the context attribute `schema-url`?

//cc @duglin

**Comment by duglin** [comment]
yea, it seems to me that between `schema-url` and `content-type` we should be covered.

**Comment by duglin** [comment]
I'll wait one more day before closing this one. If you think the current spec's attributes don't already address this please speak up.

**Comment by duglin** [comment]
Closing per WG agreement
