### ISSUE TITLE
Optional ontology-based identifier attributes for semantic interop, correlation, and event sourcing

### ISSUE THREAD

**Issue by dmigliori** [cloudevents/spec#312]
Semantic interoperability relies on a designated ontology between two or more machines to automatically and accurately interpret the meaning of exchanged data and apply it to a valuable end.  In other words, semantic interoperability relies on ontology-based “contextual metadata” supplementing “data” to form “contextual events” exchanged among machine resources or services. This ontology must account for metadata exchanged between disparate systems and environments. It represents the highest level of interoperability between connected systems.

Ontology models comprise core concepts of class, entity, and attribute (which have multiple aliases for the same concepts).     These same core concepts also exist in the [entity-attribute-value (EAV) model](https://en.wikipedia.org/wiki/Entity%E2%80%93attribute%E2%80%93value_model).  However, in a hierarchical class model of an ontology, an attribute can be inherited from a parent (super) class of an entity's class.  

Event processing and routing rules of event consumers may include a combination of class, entity, and attribute identifiers.  While these identifiers could be consolidated within a single "topic" attribute, event processing and sourcing is more efficient by maintaining these identifiers in separate structured attributes without the need for parsing or transformation.  Thus, the identifiers of class, entity, and attribute are proposed as optional or extension attributes to the CloudEvents spec.  With this implementation, the "data" attribute represents the value of the identified attribute of the identified entity of the identified class.   

Correlation is supported by events that contain a reference to other entities within the "data" (value) attribute.  (See section "Representing substructure: EAV with classes and relationships (EAV/CR)" in the link above).

Note that the "source" attribute is distinct from these proposed identifiers.  A source could be a temperature sensor that produces a raw event based a value change which is associated with the air temperature (attribute) of a room (class) number 401 (object) within a building within a city (correlation events).

Just as "Events are everywhere", "Entities are everywhere".  And the highest level of interop requires a coupling of the two within a common event format.

**Comment by duglin** [comment]
@dmigliori plans for this one?

**Comment by dmigliori** [comment]
@duglin I will create a PR proposing an extension comprising these ontology-based attributes

**Comment by duglin** [comment]
@dmigliori what's the status of this one?

**Comment by dmigliori** [comment]
With the addition of the Subject attribute, the ontology element identifiers can now be accommodated within the current CE attributes as  follows:

Topic:  Class (topic can also include Attribute and Enumerated Value)
Subject:  Class  instance (object)
Data: Class attribute / attribute value pairs

This use of CE attributes was implemented in the KubeCon Europe demo of supply chain event management.   However, batching of ontology-based events will still need to be addressed in a separate issue.  This issue can be closed.
