### ISSUE TITLE
snake_case instead of camelCase

### ISSUE THREAD

**Issue by jric** [cloudevents/spec#324]
I realize that camelCase is the defacto standard for JSON field names.  That said, the most common convention in the data world is to use snake_case field names.  There are a couple of good reasons to do this.

1. Reason:  Many databases are built or configured to be case-insensitive.  CAMELCASEBECOMESHARDTOREAD under those conditions.  ETLs that will take these events and store them into one of these databases, in order to be most usable, will also have to map the field names to something more readable.
2. Reason:  Snake_case contains more information than camelCase.  McDougal Field can typically be mapped back and forth to McDougal_Field, but not without specialized knowledge can it be mapped back and forth to McDougalField.

Since we want our event field names to map onto the field names in the databases where we store them, I propose that we switch to use the data format that works best in the database world.

Downsides:
1. Snake_case requires more bytes to encode
2. camelCase is the standard for JSON
3. It's a major change to the existing draft spec

If this proposal is accepted, I will create the patch.

**Comment by duglin** [comment]
Based on our decision on last week's call to go with #321 I believe we can now close this.
