### ISSUE TITLE
Web Hooks: How to distinguish denied delivery and missing support of validation?

### ISSUE THREAD

**Issue by deissnerk** [cloudevents/spec#328]
The [web hook spec](https://github.com/cloudevents/spec/blob/master/http-webhook.md#4-abuse-protection) states:
> If the handshake outcome is that the delivery is denied, the sender MUST NOT deliver events to the target.

A few lines later it says:
> Delivery targets SHOULD support the abuse protection feature. If a target does not support the feature, the sender MAY choose not to send to the target, at all, or send only at a very low request rate.

I wonder, if there is a way for the sender to determine, if a target just does not support http OPTIONS, or if the event delivery is denied. In both cases I would expect a response with status 405 and no `WebHook-Allowed-Origin:` header.

**Comment by duglin** [comment]
would it be a 405 or 401 Unauthorized?  wouldn't each sender have its own auth/creds and a rogue sender would fail the auth check?

**Comment by clemensv** [comment]
If the target doesn't support OPTIONS it doesn't support validation. You get a 405 and no header. If it supports OPTIONS but no validation, you get a success code response, but the header will be missing. The WebHook-Allowed-Origin header really is the success indicator. 

Without validation, it's really up to the target for whether it wants to allow deliveries. Mind that the protection mechanism is primarily for the delivering party and not for the target. We want to give the delivering party a way to protect itself from becoming a DDoS engine.

If the target doesn't allow deliveries without prior validation, it would just respond with 401.

**Comment by deissnerk** [comment]
Thank you, @clemensv. If I understand that correctly, the sending party MUST NOT send events, if the target reacts with 401. In all other cases it is up to the sender, if it wants to take the risk of being abused. Correct?

**Comment by duglin** [comment]
Do we need a PR to clarify things?

**Comment by fohoffmann** [comment]
During implementation of chapter 4 “Abuse Protection” we had a discussion why the 401 approach isn’t sufficient for the sender to protect itself being abused: Assuming the spec adds in chapter 3 “Authorization” a mandatory recommendation to stop sending events to a target in case it returns a 401 due to negative authorization check. I.e. to treat a 401 as an implicit "unsubscribe". This would solve the “Abuse Protection” problem and adds the advantage to react on later changes:

Case 1: An attacker subscribes a “foreign” Webhook at sender. Sender sends first event, target does not expect the event and reacts with 401. Sender takes this as unsubscribe, spam is stopped with the first event.

Case 2: An unsubscribe of the target later is for whatever reason not processed (in-time) or the authorization is revoked. The target starts to return 401, which immediately ends further event sending.  

The overall advantage is that chapter 4 could be set completely on “might” and with that avoid the unclear protocol situation in case a target is not supporting OPTIONS and responds with 405. The protocol itself is much leaner and hence implementation simpler.

**Comment by duglin** [comment]
@deissnerk @clemensv @fohoffmann we need to clarify anything in the spec?

**Comment by deissnerk** [comment]
@fohoffmann in case 1 the receiving end point might react with some other 4xx or 5xx code. Even worse, it might for some reason accept the POST request and do something. As the OPTIONS call is specifically defined to just return information about the possible operations on an endpoint, it is better suited for the validation.
This does not exclude that the sender should behave like a good web citizen and stop sending events, if it receives error codes like the 401 as reply to event deliveries. The OPTIONS call is just an additional measure to avoid the risk of the sender being abused.
@duglin To clarify the spec, we could make it explicit that 401 is a denial.

**Comment by duglin** [comment]
I was a little worried about repeating the http specs, but I see we already do a bit of that already in the webhook spec so adding a little more about 401 having some special meaning in the context of eventing seems reasonable.  Would you be willing to write-up a PR?

**Comment by fohoffmann** [comment]
Yep, will check with @deissnerk and we will make a proposal.

**Comment by deissnerk** [comment]
@duglin @clemensv @fohoffmann 
I was just about to create a PR for this. I was thinking about adding a sentence to section 4.2 that clarifies that 401 is a clear denial where the sender MUST NOT send messages. Then I saw this:

>If the delivery target does not allow delivery of the events or does not expect
delivery of events and nevertheless handles the HTTP OPTIONS method, the
existing response ought not to be interpreted as consent, and therefore the
handshake cannot rely on status codes.

Stating that status codes cannot be relied on, but that 401 is a clear denial seems to me a bit contradictory. Another way to resolve this, could be to remove 
> If the handshake outcome is that the delivery is denied, the sender MUST NOT deliver
events to the target.

Then it is always up to the sender to decide.

**Comment by duglin** [comment]
@deissnerk what's the status of this?  Did you want to submit a PR to remove that sentence?

**Comment by duglin** [comment]
@deissnerk what's the status of this issue?

**Comment by duglin** [comment]
Since #528 is merged i think we can close this. @deissnerk let me know if I'm wrong and we can reopen

**Comment by gooman-uk** [comment]
> Mind that the protection mechanism is primarily for the delivering party and not for the target. We want to give the delivering party a way to protect itself from becoming a DDoS engine.

This maybe a dumb question ... but can't the whole abuse protection model be circumvented by a simple man-in-the-middle attack? A DDOS hacker would simply create an API gateway that accepts and responds to the HTTP OPTIONS validation request and then forwards everything else on to the target.
