### ISSUE TITLE
CloudEvents "Integer" type isn't mapped within JSON format

### ISSUE THREAD

**Issue by dmigliori** [cloudevents/spec#329]

**Comment by duglin** [comment]
This has been brought up before and I believe @clemensv (as original author of the data types section) wanted to wait until we had an "integer" type in our model. @clemensv any new thoughts on this?

**Comment by clemensv** [comment]
Yes. @inlined added the Integer type for the benefit sampling extension. It wasn't there originally. 

So that's arguably unfinished homework from that respective PR 😁

I'll amend the JSON mapping.

**Comment by duglin** [comment]
Closing as this was fixed in PR https://github.com/cloudevents/spec/pull/345
