### ISSUE TITLE
Specify if event-type should include a version.

### ISSUE THREAD

**Issue by rachelmyers** [cloudevents/spec#33]
Decide and document if the [`event-type`](https://github.com/cloudevents/spec/blob/master/spec.md#event-type) attribute should include a version.  A version is currently included in a separate attribute, `event-type-version`.

**Comment by duglin** [comment]
I think merging the two is something worth considering.

**Comment by duglin** [comment]
Marking as v0.2 since this is a REQUIRED attribute

**Comment by duglin** [comment]
During the 6/15 f2f agreed that the proposed resolution to #142 will address this, so once that issue is resolved we can/will close this.

**Comment by duglin** [comment]
Per the previous comment, since #142 is closed we can now close this one too. Closing...
