### ISSUE TITLE
What is the recommended way to handle multiple records per event ?

### ISSUE THREAD

**Issue by fsunaval** [cloudevents/spec#330]
AWS S3 and many other cloud providers provide multiple records per event.

E.g. the event notification format for S3 is as follows.
https://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html

{  
   "Records":[  
      {  
         "eventVersion":"2.0",
         "eventSource":"aws:s3",
         "awsRegion":"us-east-1",
         "eventTime":The time, in ISO-8601 format, for example, 1970-01-01T00:00:00.000Z, when S3 finished processing the request,
         "eventName":"event-type",
         "userIdentity":{  
            "principalId":"Amazon-customer-ID-of-the-user-who-caused-the-event"
         },
         "requestParameters":{  
            "sourceIPAddress":"ip-address-where-request-came-from"
         },
         "responseElements":{  
            "x-amz-request-id":"Amazon S3 generated request ID",
            "x-amz-id-2":"Amazon S3 host that processed the request"
         },
         "s3":{  
            "s3SchemaVersion":"1.0",
            "configurationId":"ID found in the bucket notification configuration",
            "bucket":{  
               "name":"bucket-name",
               "ownerIdentity":{  
                  "principalId":"Amazon-customer-ID-of-the-bucket-owner"
               },
               "arn":"bucket-ARN"
            },
            "object":{  
               "key":"object-key",
               "size":object-size,
               "eTag":"object eTag",
               "versionId":"object version if bucket is versioning-enabled, otherwise null",
               "sequencer": "a string representation of a hexadecimal value used to determine event sequence, 
                   only used with PUTs and DELETEs"            
            }
         }
      },
      {
          // Additional events
      }
   ]
}  

A typical scenario this can happen is when I push records to S3 via kinesis firehose.  It will chunk the records into individual large objects, thus producing just one notification and allowing the user function to parse multiple records with one lambda function call.

My question is:
How can I convert such an event to cloudevent format ?
If the answer is "This is not supported and the event source should not do it" I am fine with that too.
But am open to hearing suggestions from the community.

thanks,
Farhad.

**Comment by fsunaval** [comment]
Yes, complete multiple event records stuffed inside one event notification. 
Splitting them into multiple CloudEvents is easily doable but it will create a massive burst of CloudEvents.
Consider AWS Kinesis Firehose sending data to the stream from hundreds of thousands of sources to be loaded continuously into S3.     Each event notification sometimes consists of 100 records or more (complete events).  Splitting them into separate CloudEvents will create a 100:1 fanout of events.
I was wondering if there are any plans to make the CloudEvents specification support a list (record) of events also.

**Comment by cneijenhuis** [comment]
My gut feeling is that batching of messages should be handled at the transportation layer.

There are transport layers that (natively) support publishing events in bulk, and also for receiving events in bulk. (Producer and consumer(s) can also choose different batch sizes). Kinesis seems to have that, too: https://docs.aws.amazon.com/kinesis/latest/APIReference/API_PutRecords.html

Once you know how a CloudEvent is mapped to such a transport layer, it should be easily possible to publish/consume them in bulk.

So you'd have to create 100 events out of a single record you have received, but you may be able to publish those 100 events with a single API call as well.

**Comment by fsunaval** [comment]
>So you'd have to create 100 events out of a single record you have received, but you may be able to >publish those 100 events with a single API call as well.

Ok, so for my understanding.
I have received a single S3 event which has 100 other S3 events bundled into it.
I need to convert this S3 event into cloud event format.  

I split up each of the 100 bundled S3 events into a separate CloudEvent notification.  At this point I have 100 CloudEvents (eventType: com.amazon.aws.S3.ObjectCreated:Put)
What happens next?    If I send these 100 CloudEvents into a single event (doesn't matter whether the transport layer or the application layer does this task), then I violate the CloudEvent specification.

The CloudEvent specification currently specifies a single data record per event.
{
    "cloudEventsVersion" : "0.1",
    "eventType" : "com.example.someevent",
    "source" : "/mycontext",
    "eventID" : "A234-1234-1234",
    "eventTime" : "2018-04-05T17:31:00Z",
    "comExampleExtension1" : "value",
    "comExampleExtension2" : {
        "otherValue": 5
    },
    "contentType" : "text/xml",
    "data" : "<much wow=\"xml\"/>"
}

and not

{
    [
        "cloudEventsVersion" : "0.1",
        "eventType" : "com.example.someevent",
        "source" : "/mycontext",
        "eventID" : "A234-1234-1234",
        "eventTime" : "2018-04-05T17:31:00Z",
        "comExampleExtension1" : "value",
        "comExampleExtension2" : {
            "otherValue": 5
        },
        "contentType" : "text/xml",
        "data" : "<much wow=\"xml\"/>"
    }
}

**Comment by cneijenhuis** [comment]
> I have received a single S3 event which has 100 other S3 events bundled into it.

Sorry to be pedantic, but I would formulate it as: You have received a single **S3 [message](https://github.com/cloudevents/spec/blob/master/spec.md#message) (or notification)** which has 100 **S3 events** bundled into it.

You convert those 100 S3 events into 100 CloudEvents.

Let's assume your transport layer offers the following APIs (in pseudo-code):

```
function publishEvent(Event event);
function publishEvents(Array[Event] events);
```

You can then choose between calling the first function 100 times, or calling the second function 1 time with an array of 100 events.

The CloudEvents specification does not need to specify how an array of 100 events looks like - it only specifies how a single CloudEvent is represented on this transport layer, and then the transport layer can specify how an array of events is represented.

**Comment by fsunaval** [comment]
>The CloudEvents specification does not need to specify how an array of 100 events looks like - it only >specifies how a single CloudEvent is represented on this transport layer, and then the transport layer >can specify how an array of events is represented.
Thanks. I will accept this as the answer and close the issue.

**Comment by rperelma** [comment]
https://github.com/cloudevents/spec/issues/282
