### ISSUE TITLE
revert the specversion to cloudeventsversion for compatibility

### ISSUE THREAD

**Issue by kevinwengh** [cloudevents/spec#349]
The field cloudeventsversion is the identifier to determine the format and concrete implementation among different versions of the CloudEvents objects incoming. Swagger has long support the terminology of "Discriminator" and naturally identifier field such as **cloudeventsversion** is used as discriminator. Changing the name of a discriminator has huge impact on both service and client side. 

From service side, APIs leverage the discriminator field to deserialize incoming data into typed object instances, even when a call contains events objects wrapped under different version CloudEvents spec (0.1 or 0.2 or both). Internal implementation of APIs should then process the events accordingly by operating on the deserialized object. 

From customer side, they should able to call a single API to publish the events, no matter how many different version of cloudEvents object to be published. Customer should not be forced to call different APIs in order to publish/submit different versions of events. 

In issue #323, the cloudeventsversion is changed to specversion, which will break our implementation at Oracle CloudEvents service, when we add support for future version of cloudEvents. 

So I am propose that we change the **specversion** back to **cloudeventsversion** . and for future reference, we should never change that field name.

**Comment by duglin** [comment]
The reasons you gave for not changing it are correct, but really only apply once we reach (or get close to) v1.0. Pre-1.0 versions of the spec are, by definition, free to have quite radical changes and this has been our assumption in our decision making process.  We have often told people that "we can change our minds later if needed, before we get to v1.0". This gives us the freedom to test out choices w/o feeling locked into them.  I have no strong feeling on whether we change back or not, this is more of a comment on the process or "rules of engagement" I think most people have been operating under.

**Comment by kevinwengh** [comment]
I totally agree with you that we should have smaller room for dramatic change when we get closer to 1.0 version. But before that, I think field like cloudeventsversion is the anchor, which should be changed only when there is very strong justification. I think the justification in #323 is not enough for make the change. 

Changing the cloudeventsversion is essentially an unnecessary punishment for early adapter like Oracle. we published v0.1 kind of officially, so we need some continuity and consistency. 

furthermore, I think cloudeventversion name is concise and clear. the specversion is ambiguous. if we want to be clear, then keep cloudeventsversion. if we want really simple, we should use version. the specversion probably not a good choice in either case.

**Comment by duglin** [comment]
We discussed this on today's call and decided that there was no new information that warranted us re-opening this topic.
