### ISSUE TITLE
Does schema-url apply to the whole event or to the data alone?

### ISSUE THREAD

**Issue by rachelmyers** [cloudevents/spec#35]
Decide and document if the [schema-url](https://github.com/cloudevents/spec/blob/master/spec.md#schema-url) attribute is applicable to the whole event or to the data alone.

Assigned to: @duglin

**Comment by duglin** [comment]
I would think it would be just the "data" since the schema/format of the other stuff is defined by this specification and should be the same for all instances of CloudEvents (at the same CloudEvent version level).

If people agree I can write-up a PR.

**Comment by duglin** [comment]
Seems related to: https://github.com/cloudevents/spec/issues/36

**Comment by duglin** [comment]
PR #48 should cover this
