### ISSUE TITLE
RocketMQ transport binding

### ISSUE THREAD

**Issue by zongtanghu** [cloudevents/spec#351]
Apache RocketMQ is a distributed messaging and streaming platform with low latency, high performance and reliability, trillion-level capacity and flexible scalability.So,I'd like to propose a RocketMQ transport binding for CloudEvents.

**Comment by zongtanghu** [comment]
I have alread committed the PR.The PR link is https://github.com/cloudevents/spec/pull/352;

**Comment by duglin** [comment]
I believe we can close this one now that we have RocketMQ listed here:  https://github.com/cloudevents/spec/blob/master/proprietary-specs.md

@zongtanghu please speak up if I'm wrong and we need to reopen this.
