### ISSUE TITLE
Where does the producer specify the format/encoding of the data attribute?

### ISSUE THREAD

**Issue by rachelmyers** [cloudevents/spec#36]
Decide and document where the producer specifies the format/encoding of the [data](https://github.com/cloudevents/spec/blob/master/spec.md#data-1) attribute in this schema.

**Comment by duglin** [comment]
I believe that #59 and #35 (once adopted) should address this one

**Comment by duglin** [comment]
I believe we can now close this one

**Comment by duglin** [comment]
Not hearing any objection to closing this (since #48 and #64 are resolved) I'm going to do so. Let me know if we need to reopen it.
