### ISSUE TITLE
Encrypt the CloudEvent "data" attribute

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#373]
On today's call Tam asked if we wanted to add the ability to encrypt the CloudEvent's `data` attribute to ensure it is not tampered with. Please add your thoughts on this topic to this issue so we can have a record of the discussion.

In the end, we'll either add a new feature to the spec or we'll add something to the Primer explaining why we chose to do nothing so that new folks can understand our reasoning behind the decision since this questions has come up more than once in the past.

**Comment by clemensv** [comment]
See https://github.com/cloudevents/spec/issues/379#issuecomment-458516954 

If you need to, you can provide a [JWE](https://tools.ietf.org/html/rfc7516) payload that also contains a [JWS](https://tools.ietf.org/html/rfc7515) signature over all the context attributes, such that the receiver who can decrypt the payload can then verify that the context attributes have indeed not been tampered with. There are obviously variations where that signature can also travel in plain text such that the context attributes can be verified without having the decryption material, and, in turn, the encrypted portion then again protects that signature. Equivalently, you could do something similar with S/MIME.

We could put a simple scenario description into the primer as an example, but I'm somewhat hesitant to spell that out in deep detail because of the depth of that pit.

**Comment by duglin** [comment]
Given @clemensv's comment and the lack of other comments, I'd like to propose that we add some text to the Primer so that people know we thought about it and purposely decided to not add it to the spec at this time.

Any concerns with this approach?

**Comment by evankanderson** [comment]
I'm also concerned with the interaction between middleware changing context attributes, the use of context attributes for event routing, and any sort of signing integrity on the events.

Note that encryption alone may not prevent tampering; for example replay attacks would allow an attacker in the routing fabric to repeat an earlier data payload as a replacement for the data payload in a later event.

**Comment by evankanderson** [comment]
(That is a vote for documenting that we assume a trusted chain of middleware, and that transport protocols should support point-to-point security guarantees between trusted middleware components.)

**Comment by JemDay** [comment]
I've commented on a related issue, but i'll re-iterate here...

We need to make statements along the lines of :
_".. sensitive information SHOULD BE be present in event context attributes.."_
_".. the *data* content SHOULD be encoded/encrypted if sensitive information is present.."_

Essentially the encryption of _data_ is a producer/consumer concern, the various _context attributes_ MUST be in-the-clear to allow for routing to occur.

**Comment by duglin** [comment]
@JemDay in your first point, is there a typo? did you mean to say "SHOULD NOT" ?

**Comment by JemDay** [comment]
@duglin - Thanks for providing proof-reading services..

_".. sensitive information SHOULD NOT be present in event context attributes.."_

**Comment by duglin** [comment]
Based on the above comments it seems like a possible proposal might be to add text to the spec saying:
- we assume a trusted chain of middleware
- transport protocol point-to-point security should be used
- sensitive information SHOULD NOT be present in event context attributes, and SHOULD be unencrypted to allow for proper routing by middleware
- the `data` content SHOULD be encoded/encrypted if sensitive information is present. But this encryption is application specific and out of scope of the spec

What do people think? We could also remove the RFC2119 language and move this into the primer.

**Comment by erikerikson** [comment]
> we assume a trusted chain of middleware

Perhaps greater explicitness?  You could add "and users remain responsible for validating that middleware confidentiality guarantees meet their confidentiality requirements" except more elegantly stated?  I'm trying to ask how the guidance may be more end user consumable a

**Comment by Vlaaaaaaad** [comment]
I really like encrypting just `data` considering the whole rabbit hole we went down on during the extensions talk about how immutability/ encryption/ signing affects the bag of extensions and nested bags and bllaah.

Different encryption implementations could come up as extensions and we'll be able to address the problem nicely after 1.0 without limiting anybody.

**Comment by cneijenhuis** [comment]
> the data content SHOULD be encoded/encrypted if sensitive information is present. But this encryption is application specific and out of scope of the spec

👍 for that. I think as an alternative we can also mention the claim check pattern.

**Comment by JemDay** [comment]
See #399

**Comment by duglin** [comment]
I believe that #399 address this issue so I'm going to close it. Let me know if I got this wrong.

**Comment by alexec** [comment]
When the `data` field is encrypted, I’m assuming you just set `datacontenttype` to be `multiparty/encrypted`? Any example of that in the wild?
