### ISSUE TITLE
Duplicate paragraph in primer

### ISSUE THREAD

**Issue by nuhamind2** [cloudevents/spec#374]
> Event Tracing
> 
> An event sent from a source may result in a sequence of additional events sent from various middleware devices such as event brokers and gateways. CloudEvents includes metadata in events to associate these events as being part of an event sequence for the purpose of event tracing and troubleshooting.
> 
> An event sent from a source may result in a sequence of additional events sent from various middleware devices such as event brokers and gateways. CloudEvents includes metadata in events to associate these events as being part of an event sequence for the purpose of event tracing and troubleshooting.

**Comment by duglin** [comment]
@nuhamind2 thanks! I opened PR #375 to fix this
