### ISSUE TITLE
Producer Identity

### ISSUE THREAD

**Issue by erikerikson** [cloudevents/spec#378]
As part of #276, information about the identity of the producer can be lost once the connection across which the event is sent gets terminated.  Is addressing this need in certain systems within scope for CloudEvents?

**Comment by clemensv** [comment]
This is, in effect, the signing aspect of my comment on your other issue https://github.com/cloudevents/spec/issues/379#issuecomment-458516954 

The producer can prove its authorship of the event by signing it and the receivers can validate the signature if they have access to the required key material and that key material is known to be trustworthy. S/MIME and X.509 might be elements of that solution, but as laid out in the other comment, it might not be trivial for a receiver to get at all information required to verify the signature and/or the author's identity and trustworthiness. 

It's something that needs solving, but CloudEvents 1.0 is not the place, IMO.

**Comment by jamesurquhart** [comment]
Newb question/comment. Is another term for the combines subjects of #276 "data providence", i.e. tracking the origin and authenticity of the data that makes up the event? If so, this is both a critical issue (in the long term) and a notoriously difficult one to solve. If we do "solve" it, however, it might be a key driver to adoption, as the IoT, financial, and healthcare industries have been asking for it for years. I would agree its not needed for 1.0, but I think it deserves attention and thinking, and maybe acknowledgement that it is missing in the current spec, but intended for future specs.

**Comment by duglin** [comment]
@erikerikson you ok with tagging this as a post-v1.0 item?  Or do you think we need to discuss it for v1.0?

**Comment by erikerikson** [comment]
Sure thing: post v1.0 is fine with me.
