### ISSUE TITLE
URI vs URI-reference

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/spec#384]
Found an issue when URI was changed to be URI-reference, the definition of URI was removed but the usage of URI remains in schemaurl.

see https://github.com/cloudevents/spec/blob/master/spec.md#schemaurl for usage of URI

**Comment by cneijenhuis** [comment]
Good catch, that was me in https://github.com/cloudevents/spec/pull/338.

I think I started looking for usages of URI in the Swagger/JSON schema - which doesn't contain `schemaurl` at the moment - and, as I only found `source`, changed only that in `spec.md`.

I'll clean that up, and also add `schemaurl` to `spec.json`.

Thanks!

**Comment by cneijenhuis** [comment]
Correction: `schemaurl` has already been added to `spec.json` yesterday via https://github.com/cloudevents/spec/pull/372 😉 

Opened https://github.com/cloudevents/spec/pull/386
