### ISSUE TITLE
spec version from v0.1 to v0.2 unclear

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/spec#385]
`cloudEventsVersion` was renamed to `specversion` and in attempting to write a parser that accepts an incoming message, there is a chance to receive a hybrid message.

For example, how do I process this:

```
{
    "specversion" : "0.2",
    "cloudEventsVersion" : "0.1",
    "type" : "com.github.pull.create",
    "eventType" : "com.example.someevent",
    "source" : "https://github.com/cloudevents/spec/pull/123",
    "id" : "A234-1234-1234",
    "eventID" : "B234-1234-1234",
    "time" : "2018-04-05T17:31:00Z",
    "comexampleextension1" : "value",
    "comexampleextension2" : {
        "othervalue": 5
    },
    "extensions" : {
      "comExampleExtension" : "value"
    },
    "contenttype" : "text/xml",
    "data" : "<much wow=\"xml\"/>"
}
```

What is the event id? What event type is this?

**Comment by duglin** [comment]
What's funny is that if this is a valid 0.1 and 0.2 message, then kudos to the producer!  :-)

W.r.t. what should the receiver do... my vote would be: it's up to them. I think they're free to interpret it as 0.1 or 0.2 - but if it were me I'd look for "specversion" first.  Then once they spot the version property name they want to use, they must adhere to that version's parsing rules.

**Comment by n3wscott** [comment]
This event is valid for both v0.1 and v0.2 but the event type and id are different is what I am illustrating.

**Comment by duglin** [comment]
If we assume that the "specversion" field will not change its name once we hit v1.0, which it shouldn't, I don't think we need to worry about this case - you shouldn't need to test the old name.

I guess we could add stuff that says "if you see,and understand, both then only process 'specversion'", but then we're carrying around the idea of an alpha-level field forever.  Seems unnecessary to me.

If, for some reason, we do change the name in the future, I think we can deal with it at that point.

**Comment by deissnerk** [comment]
If you look for specversion first, the event will be an invalid 0.2 event. All fields that are not part of the 0.2 spec, would automatically become extensions. As the old field names contain upper case letters, this does not comply with 0.2.

**Comment by duglin** [comment]
@n3wscott is this still an issue?

**Comment by n3wscott** [comment]
No I don't think so.

/Close

**Comment by duglin** [comment]
thanks - closing
