### ISSUE TITLE
define schemaurl's content?

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/spec#392]
At the moment, schemaurl is defined as a URI-Ref and the content is a "schema" but we do not define what this means. Can we elaborate?:: Is it json schema? is it openapi? asyncapi? schema.org?

**Comment by cneijenhuis** [comment]
We don't prescribe the content type, therefore I don't see how we could prescribe the type of schema used.

E.g. if someone decides to send a XML document with CloudEvents, the `schemaurl` could point to an XML schema.

That said, shouldn't it be reasonable to figure out if the type of schema is one that is supported? E.g. if the content type is JSON, and the schemaurl ends in `.schema.json`, it is fair to assume it is a JSON schema.

**Comment by clemensv** [comment]
https://github.com/cloudevents/spec/issues/394#issuecomment-475153649

My notion is that schemaurl is just an identifier.

**Comment by duglin** [comment]
@n3wscott thoughts on next steps for this one?

**Comment by duglin** [comment]
@n3wscott any comment on this one? I'm inclined to think the spec is ok as is and we should close this.

**Comment by n3wscott** [comment]
ok
