### ISSUE TITLE
Question: What's best practice to add data versioning?

### ISSUE THREAD

**Issue by cmenzi** [cloudevents/spec#393]
Hi

I'm went through the latest CloudEvents docs and cannot find any examples on how to do the data versioning?

I saw the an example of a Azure EventGrid Message and saw that there is `eventTypeVersion` in the header, but I think was based on CloudEvents V1.

* Is the `SchemaUrl` the right element to use for event versioning?
* Do I need to add `CloudEventExtension`?

Or is there something, I didn't saw?

Cédric

**Comment by cneijenhuis** [comment]
Hi Cédric,

Yes, you can use the schema, and/or the eventtype.

See https://github.com/cloudevents/spec/blob/master/spec.md#type and https://github.com/cloudevents/spec/blob/master/spec.md#schemaurl (both also link to https://github.com/cloudevents/spec/blob/master/primer.md#versioning-of-attributes)

Does that help?

**Comment by cmenzi** [comment]
@cneijenhuis Yes, this is very helpful. Thx. Didn't saw that.
