### ISSUE TITLE
Document structure leads to confusion between context and extension attributes

### ISSUE THREAD

**Issue by r-marques** [cloudevents/spec#401]
I find the current structure of the Context Attributes section a bit confusing. It took me a while to realize that the attributes being described were actually context attributes and not examples of extension attributes since they follow the description of extension attributes.

I think that it would be best to move the the extension attributes description to the end of the Context Attributes section.

**Comment by duglin** [comment]
@r-marques I can definitely see why there would be confusion.
See if https://github.com/cloudevents/spec/pull/402 addresses your concerns.
