### ISSUE TITLE
Webhook - Auth & Validation

### ISSUE THREAD

**Issue by JemDay** [cloudevents/spec#407]
A couple of questions have come up internally regarding the WebHook specification.

**Authorization**

The spec mandates that the delivery targets **MUST** support both mechanisms to transport the access-token. I would like to propose changing to a **SHOULD** as we probably would never promote the URI Query model because of potential token leakage.

There is also an implication that OAuth tokens are the _only_ model; this effectively rules out other mechanisms such as TLS mutual auth.

**Comment by clemensv** [comment]
The goal of this specific specification is to create a narrow usage profile of HTTP for posting events to enable broad interoperability. The constraints for AuthNZ are therefore deliberate. The token can be any token you like; even OAuth does not prescribe a token format. What RFC6750 defines is what a "bearer token" is.

The token in the URI parameter is not my preference, but I keep seeing scenarios where embedding short-lived tokens with URIs is useful or occasionally even unavoidable (like with generic tooling that doesn't allow setting the Authorization header)

**Comment by duglin** [comment]
@JemDay what are your thought on this? If you still think we need some changes can you open a PR to help force the discussion?

**Comment by JemDay** [comment]
@duglin - Yes, i think that's the more appropriate route.
