### ISSUE TITLE
Clarify namespace

### ISSUE THREAD

**Issue by sslavic** [cloudevents/spec#41]
1. Does `namespace` identify event or event source (producer)?
2. If latter, what is the value `namespace` adds on top of `source-id`?
3. Is there a use case where events with same (`event-type`, `event-type-version`) can be published by more than one event source, so with difference in at least one of (`source-id`, `source-type`)?
4. If `namespace` identifies event source and there's value added of `namespace` on top of `source-id` would it make sense to include `namespace` together with (`source-id`, `source-type`) as property of source object?

**Comment by deissnerk** [comment]
In yesterday's call the need for specific examples was mentioned several times. Do we have an issue that captures this? Is it part of #37 ? I think it also affects #58 and probably many others.

**Comment by duglin** [comment]
if by example you mean "use cases driving our work", then yea I think #37 is part of it, but also the use-cases.md file that @ac360 recently added should cover it too - and PRs are welcome to add more. We should probably make sure we don't duplicate stuff between those two things (too much).

**Comment by duglin** [comment]
Can we pull this one into the overall "what is the source?" discussions? It seems related to me since they're all about identifying where the event came from so it makes sense to tackle them all at the same time.

**Comment by ultrasaurus** [comment]
I think this is addressed by: https://github.com/cloudevents/spec/pull/123
