### ISSUE TITLE
cloudevents logo link is broken 

### ISSUE THREAD

**Issue by alanconway** [cloudevents/spec#421]
This link is broken:
    https://github.com/cncf/artwork/blob/master/cloudevents/horizontal/color/cloudevents-horizontal-color.png

It is used in the main cloudevents README.md at
    https://github.com/cloudevents/spec/blob/master/README.md
and several other places, and is causing spurious build failures for PR branches, e.g. 
    https://travis-ci.org/cloudevents/spec/builds/524139840?utm_source=github_status&utm_medium=notification

**Comment by duglin** [comment]
@dankohn you made this change in the CNCF repo - is there a way for us to be notified of changes like this? We have links (in docs and demos) that point to these images.

**Comment by dankohn** [comment]
I apologize. I'll aim not to change images in the artwork repo again.
