### ISSUE TITLE
Avro format enconding

### ISSUE THREAD

**Issue by fabiojose** [cloudevents/spec#426]
I would like to propose an official Avro encoding schema to be supported by CloudEvents.

I've seen a lot of uses cases, in special here in my current project, with Apache Kafka and the many of them were using Avro as the format. Inspired by [this](https://gist.github.com/rbramley/c00bbd95f3f6ecc0cc1f90e5d6d6c90c) Gist (thanks @rbramley), the following schema could be the first draft:

```json
{
  "namespace":"io.cloudevents",
  "type":"record",
  "name":"CloudEvent",
  "version": "1",
  "doc": "CloudEvents Spec for Avro format encoding (the version is just for the schema itself)",
  "fields":[
    {
      "name":"specversion",
      "type":"string"
    },
    {
      "name":"type",
      "type":"string"
    },
    {
      "name":"source",
      "type":"string"
    },
    {
      "name":"id",
      "type":"string",
    },
    {
      "name":"time",
      "type":[
        "null",
        "int"
      ],
      "logicalType": "date"
    },
    {
      "name":"schemaurl",
      "type":[
        "null",
        "string"
      ]
    },
    {
      "name":"contenttype",
      "type":[
        "null",
        "string"
      ]
    },
    {
      "name":"data",
      "type":[
        "null",
        "string"
      ]
    },
    {
      "name":"extensions",
      "type":[
        "null",
        {
          "type":"map",
          "values":[
            "string",
            "int",
            "long",
            "float",
            "double",
            "boolean",
            "bytes"
          ]
        }
      ]
    },
  ]
}
```

- Official Avro spec available [here](https://avro.apache.org/docs/1.8.2/spec.html)

__Extensions__

To define a top-level extension (like below) is not allowed by Avro spec for `avsc`, because we do not have the feature for dynamic fields like JSON. Because of this, you will see the `extension` attribute to the example above.

```json
...
    "comexampleextension1" : "value",
    "comexampleextension2" : {
        "othervalue": 5
    }
...
```

For that, we may employ Avro spec for `ìdl` that is a higher-level language for authoring Avro schemas.

- Official Avro IDL docs available [here](https://avro.apache.org/docs/1.8.2/idl.html)

__Special Types__

What I mean with _special types_, logical types in JSON Schema, are: `uri-reference`. We do not have this type in Avro.

For that, again, we may employ Avro IDL.

**Comment by duglin** [comment]
@fabiojose I'm not familiar with Avro, would this fit into the category of being a protocol that would benefit from interop between multiple implementations (like our http binding), or is it more focused on just one impl (like the rocketmq binding) ?

**Comment by fabiojose** [comment]
@duglin Avro can be used with multiple binding. It's just a message format very similar to protobuf. No, it's not focused on just one impl.

**Comment by fabiojose** [comment]
@clemensv some insights about Avro?

**Comment by clemensv** [comment]
That’s a great idea. Avro and CBOR are the two extra encodings which I’d love to see. 

I’m in favor. Who writes the spec.

**Comment by fabiojose** [comment]
> That’s a great idea. Avro and CBOR are the two extra encodings which I’d love to see.
> 
> @duglin this would be a different event format, not a different transport.
> 
> I’m in favor. Who writes the spec.

I will write down the first version and I appreciate the considerations of everyone.

**Comment by gunnarmorling** [comment]
Ha, came here to file a feature request for Avro myself, it's there already :) I'm not sure where things stand with that format spec, but I'll be happy to help out with it.

**Comment by fabiojose** [comment]
@gunnarmorling I've made the PR! Looking forward to your comments!
