### ISSUE TITLE
Add guidance to not require extensions to primer

### ISSUE THREAD

**Issue by Tapppi** [cloudevents/spec#428]
We were about the relation between [the `partitionKey` extension](https://github.com/cloudevents/spec/pull/218) and the kafka binding on the call 09.05.2019 and there was a great snippet of someone saying that the binding should not require the extension. I think that applies on a general level and the primer should suggest that plugins/bindings/programs (what's the lowest common denominator here?) that work with CloudEvents not require extensions unless absolutely necessary.

**Comment by duglin** [comment]
@Tapppi would you like to submit a PR?

**Comment by duglin** [comment]
@Tapppi we added text to spec that talks about what OPTIONAL means and how people need to be prepared for cases where people ignore (or don't use) the extensions.  Do you think we need more than that?

2nd para in: https://github.com/cloudevents/spec/blob/master/spec.md#notational-conventions

**Comment by duglin** [comment]
I"m going to suggest that we close this - does anyone have any concern about this?

**Comment by jskeet** [comment]
As a relative newcomer to the CloudEvents ecosystem, the way I read the primer and spec on extension attributes was always that they were very optional. I think how a particular binding treats an extension can easily be documented in that specific binding, and I have confidence in the review process to discourage any binding from requiring an extension unless it's clearly justified.
