### ISSUE TITLE
Should we define errors for size limits exceeded?

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#433]
As part of #405 someone asked if we should define well-known errors when the size limits are exceeded.  I'm opening this issue so we can discuss the option.

/cc @clemensv

**Comment by judepereira** [comment]
I'm all for this, at least for HTTP, since it's a widely used transport. 413 is the standard for HTTP I think: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413

**Comment by duglin** [comment]
@judepereira, or anyone else, would you like to submit a PR?

**Comment by judepereira** [comment]
I don’t mind taking a stab at this. I’ll have a PR open on Tuesday. 


Cheers,
Jude Pereira

**Comment by judepereira** [comment]
Just a quick update - I haven't had the time to do this yet, will try and do it tonight.

**Comment by duglin** [comment]
@judepereira should we close this one?

**Comment by judepereira** [comment]
Oh yes, please do close it.

**Comment by duglin** [comment]
thanks!
