### ISSUE TITLE
Should we document unhappy paths?

### ISSUE THREAD

**Issue by Vlaaaaaaad** [cloudevents/spec#434]
While chatting at KubeCon+CloudNativeCon with @noelo they asked a very good question: how does CloudEvents handle the unhappy paths? What happens if a 500 is returned by the HTTP transport? What about a 429? What about all other transports? Apparently AMQP does have some ACK/ NACK included.

Do we want to document this? Would a primer per-transport make sense for this?

**Comment by duglin** [comment]
if we do something in this space, I like your idea of making it a per-transport thing rather than trying to add processing model logic to the core spec.

**Comment by duglin** [comment]
@Vlaaaaaaad what would you like to do with this one?

**Comment by Vlaaaaaaad** [comment]
Hm... I agree that this is not requirement for 1.0.

On one hand, releasing 1.0 will get a lot of people interested and I think we'll see things built on top of the SDKs: friendlier libraries with error-handling included for example. So this issue will get handled then.

On the other hand, it would be nice to have this before 1.0 so there's a clear expectation that unhappy paths are not handled. I do believe I am too unfamiliar with transports to try my hand at fully defining this. Do you all think a specific mention in the primer is worth it?

A specific case of this was treated in https://github.com/cloudevents/spec/pull/451 which did get closed because we kinda specify that we don't have any retries, as per https://github.com/cloudevents/spec/pull/451#issuecomment-503985463.

**Comment by duglin** [comment]
hmmm just brainstorming.... given what happened with #451 and the discussion in #414 , I wonder if adding something to the Primer that said something like:
- - -
# Error Handling

The CloudEvents specification, for the most part, does not get into the processing model associated with the creation or processing of CloudEvents. As such, if there are errors during the processing of a CloudEvent it is assumed that the normal transport-level error reporting mechanisms will be used.
- - -
would cover it?

**Comment by Vlaaaaaaad** [comment]
Yeah, something along those lines seems to me to be the best way forward.

**Comment by duglin** [comment]
Wanna PR it?

**Comment by Vlaaaaaaad** [comment]
I could, but it feels weird to take your text and create a PR for it. You should get the credit for that.

**Comment by duglin** [comment]
LOL I don’t really care but ok if I have WiFi on the flight I’ll do it. 

Thanks,
-Doug
