### ISSUE TITLE
Could Any also take Uri-reference and timestamp attributes

### ISSUE THREAD

**Issue by gunnarmorling** [cloudevents/spec#436]
Reading the current wording of the spec it seems `Any` couldn't `Uri-reference` and `timestamp` attributes. Is this intentional? It seems it'd exclude usage of those two in maps for instance. Or if they actually are allowed for `Any`, this should be clarified. I can provide a PR if that's how it is meant.

**Comment by cneijenhuis** [comment]
Good point - I think this is not intentional. Feel free to open a PR.

**Comment by gunnarmorling** [comment]
Done: PR #437.

**Comment by duglin** [comment]
Closed by #454
