### ISSUE TITLE
Multi-tenant system support

### ISSUE THREAD

**Issue by lennygran** [cloudevents/spec#443]
This is more like a question, rather an issue. There are plenty of systems required multi-tenancy support. Usually, such systems include `tenantId` or similar attribute as part of the event envelope. The main rationale here is very often the tenant-based rules, such as routing, security, etc. may be applied outside of the event handling, but the intermediaries that have no business understanding of the event body. 

Alternatively, this type of information can be carried via an extension.  

Do you see a value of defining such attribute? If so, what would be your preference - the context attribute or extension?

**Comment by duglin** [comment]
My initial reaction is that it would be an extension, if part of CE at all, because it seems like this might be better put into whatever authN/authZ scheme you're using as part of the transport layer.  Just my 2c

**Comment by lennygran** [comment]
@duglin, yes, I was thinking about an extension. But I wanted to see if others have a different opinion. I would not directly relate it to the authN/Z in particular because this information is often used in routing, scheduling/processing priorities, etc., therefore falling into generic messaging concerns. It also feels that this would be useful for products that are dealing with multi-tenancy, hence would be nice to have it as part of CE for consistency. 

If no objections, I'll create a PR and put it for review.

**Comment by duglin** [comment]
never any objection to PRs  ;-)
