### ISSUE TITLE
Revise Map encoding for attributes in AMQP

### ISSUE THREAD

**Issue by clemensv** [cloudevents/spec#460]
Looking at [the AMQP bindings](https://github.com/cloudevents/spec/blob/v0.3/amqp-transport-binding.md#3132-amqp-application-property-values), it's not clear that ["Map" values](https://github.com/cloudevents/spec/blob/v0.3/spec.md#context-attributes) can be represented as requested in AMQP, because the [application-properties](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-messaging-v1.0-os.html#type-application-properties) section does not allow values of the [map](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-types-v1.0-os.html#type-map) type.

> The keys of this map are restricted to be of type string (which excludes the possibility of a null key) and the values are restricted to be of simple types only, that is, excluding map, list, and array types.

_Originally posted by @evankanderson in https://github.com/cloudevents/spec/pull/456#issuecomment-502879572_

That constraint is one that the AMQP TC now regrets, but it's difficult to change now. The AMQP-native way to do this would be to store the Map as a binary-encoded AMQP map, which is a little weird, but would be close to the wire model you'd have if maps were allowed. The more straightforward way for apps would be to store it as a JSON-encoded string.

**Comment by evankanderson** [comment]
I think either format would be fine, but unless the AMQP TC wants to revise the standard, we should probably suggest one of the workarounds -- I'm not sure which to recommend, but I suspect that the binary-encoded AMQP map would need some sort of indication for bridging into other formats so that it's clear that the value is an encoded Map and not an arbitrary Binary string.

**Comment by duglin** [comment]
@clemensv do you want to work on a PR for this one?

**Comment by clemensv** [comment]
@duglin Yes, I will work on this.

**Comment by clemensv** [comment]
@duglin @evankanderson  

As the linked thread shows, @rgodfrey reminded me that the key reason for the type limitation is that message/event selectors and filters generally don't allow for traversing complex structures, also because that can become rather expensive and drives complexity (suddenly people will want expressions that search inside a collection). 

It would be possible to create a capability override in AMQP to allow for complex types (lists and maps) in application-properties even if the core spec disallows it, but the capability override might not be consistently supported on a multi-hop route. In reality, we're not sure whether implementations have a hard enforcement of the rule that the values must not be complex, but filters will certainly not be able to do anything with that content.

Therefore, and informed by the filter consideration, I would prefer if we would explicitly discourage usage of complex types in attributes for CloudEvents altogether, and the AMQP binding would use JSON encoding as an escape hatch similar to how HTTP handles it now.

**Comment by evankanderson** [comment]
Do we have a concrete use case for Map values at the moment?

Map values are one of the more complex areas of the spec, and the only one
which does not seem to be used in the core or extensions. Furthermore, it
sounds like several other ecosystems (HTTP and AMQP) don't support them,
and the AMQP decision was guided by careful consideration.

Would it be simpler to remove Map from the v1 spec altogether?

**Comment by evankanderson** [comment]
Reviewing the spec, it turns out that Map is an important part of Any, which is needed for the `data` attribute. But we could remove Map and Any from consideration in Context Attributes, which would remove a number of tricky cases from the encoding, and also remove the problematic HTTP header text.

Suggested https://github.com/cloudevents/spec/pull/467 to remove Any and Map types from Context Attributes.

**Comment by clemensv** [comment]
@evankanderson I second #467 to resolve this issue
