### ISSUE TITLE
schemaurl -> dataschemaurl ?

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#474]
Anyone else think it's odd that we have:
- datacontenttype
- datacontentencoding

but then we have:
- schemaurl

when all 3 are about `data` ? Should `schemaurl` really be `datacontentschemaurl` ?
Or just `datacontentschema` since we don't put the type into other property names.
I'd actually be ok with just `dataschema[url]` since I think starting with `data` is the most important thing.

Of course we could just do:
- datatype
- dataencoding
- dataschema

Thoughts?

**Comment by cneijenhuis** [comment]
I'm torn between renaming all three, and sticking to what we have in order to not open another can of worms before `1.0` 😉
