### ISSUE TITLE
Should datacontentencoding maps to Content-Transfer-Encoding ?

### ISSUE THREAD

**Issue by fabiojose** [cloudevents/spec#477]
Should `datacontentencoding` maps to `Content-Transfer-Encoding` in the HTTP Transport Binding?

There is no mention about that like we have with `datacontenttype`, which maps to `Content-Type`. It is maybe an issue specifically with the binary content mode.

- datacontentencoding: https://github.com/cloudevents/spec/blob/master/spec.md#datacontentencoding
- HTTP Transport Binding: https://github.com/cloudevents/spec/blob/master/http-transport-binding.md#13-content-modes

**Comment by duglin** [comment]
I suspect this might be slightly different though because in the switch from 'binary' to 'structured' mode your choice of encoding `data` may need to change drastically based on what your structured format allows in the `data` attribute's value character set. And visa-verse.

E.g. when going from structured to binary you may actually go from base64 encoded to no-encoding at all.

I wonder if it would make sense to say:
- `datacontentencoding` and HTTP's `Content-Encoding` headers serve similar purposes
- whether they are the same values in both structured and binary modes will vary depending on the structure serialization chosen

Dunno. What do other people think? Could just be more of an FYI kind of thing to help people understand why `datacontentencoding` exists

**Comment by duglin** [comment]
hmm is it Content-Encoding or Content-Transfer-Encoding?

**Comment by fabiojose** [comment]
Like we have in the spec, `datacontentenconding` is based on the `Content-Transfer-Encoding` spec. 

Yes, is `Content-Transfer-Encoding` what I am asking.

Here: https://tools.ietf.org/html/rfc2045#section-6.8

**Comment by clemensv** [comment]
While the fields correspond directly, I wouldn't prescribe a mapping because it's more than a little weird to carry binary as Base64 where you can carry Binary raw. For an SMTP transport, I would prescribe a mapping, but not for any of the transports we've got.

**Comment by fabiojose** [comment]
Just to be clear for me, consider bellow.

If we have this event:

```json
{
  "specversion": "0.3",
  "id": "45c83279-c8a1-4db6-a703-b3768db93887",
  "type": "com.github.pull.create",
  "source": "https://github.com/cloudevents/spec/pull/123",
  "time": "2019-06-21T17:31:00.000Z",
  "datacontenttype": "application/json",
  "datacontentencoding": "base64",
  "data": "eyJtdWNoIjoid293In0="
}
```

And map that event to binary, we end up with this? `ce-datacontentencoding:base64`

```bash
curl -X POST \   
     -d'eyJtdWNoIjoid293In0=' \
     -H'Content-Type:application/json' \
     -H'ce-specversion:0.3' \
     -H'ce-type:com.github.pull.create' \
     -H'ce-source:https://github.com/cloudevents/spec/pull/123' \
     -H'ce-id:45c83279-c8a1-4db6-a703-b3768db93887' \
     -H'ce-time:2019-06-21T17:31:00Z' \
     -H'ce-datacontentencoding:base64' \
     http://localhost:3000/v03
```

**Comment by duglin** [comment]
Shouldn't `ce-datacontentencoding` map to the equivalent HTTP head in the 2nd snippet?

**Comment by duglin** [comment]
Anyone want to comment on this one?

> Should datacontentencoding maps to Content-Transfer-Encoding in the HTTP Transport Binding?

@clemensv @cneijenhuis 

@fabiojose perhaps open a PR to force the discussion?

**Comment by fabiojose** [comment]
@duglin , yep! I will do that!

**Comment by clemensv** [comment]
datacontentencoding maps to Content-Encoding in RFC7231, not to Content-Transfer-Encoding in RFC7230. We're not really touching RFC7230 with the HTTP binding.

**Comment by evankanderson** [comment]
I think https://github.com/cloudevents/spec/pull/484 closes this out, removing `datacontentencoding` as a CE attribute.

**Comment by duglin** [comment]
Closed due to https://github.com/cloudevents/spec/pull/492 - if incorrect please let me know
