### ISSUE TITLE
String type: "printable Unicode characters" and follow-on problems

### ISSUE THREAD

**Issue by cneijenhuis** [cloudevents/spec#483]
Previous discussion started by @evankanderson here: https://github.com/cloudevents/spec/pull/456#issuecomment-507860941 and in the following comments. Also, here: https://github.com/cloudevents/spec/pull/471/files#r312744230 and here: https://github.com/cloudevents/spec/pull/482#issuecomment-520437625

The `String` type currently only allows "printable" Unicode characters.

There are multiple problems:
- As @evankanderson has pointed out, while "printable" is defined for ASCII, it isn't clear what it means in Unicode.
- One may assume that space is not "printable" (but per ASCII, it is)
- We can't use `String` for the `data` attribute. The most obvious reason is that line breaks can't be used, which is an issue for plain text, but also if we want to model JSON, XML or CSV as `String`.

`String` is used in three places:
- As a key for `Map`. The "printable" requirement makes sense (and may be even to weak?)
- As a value in regular attributes. The "printable" requirement makes sense, or we'd have to rework our HTTP transport a bit (as headers are terminated by a line break).
- As a value in `data`. The requirement is too restrictive.

**Comment by cneijenhuis** [comment]
I think there are three paths forward:

1. We keep the requirement, but specify it more clearly as Evan suggested here: https://github.com/cloudevents/spec/pull/456#issuecomment-509433468 JSON, XML, CSV and even multi-line plain text will have to be modeled as `Binary`.
2. We have a separate `String` type for use within `data`.
3. We drop the "printable" requirement completely, and make sure our transports are able to deal with control characters.

**Comment by duglin** [comment]
what about:
4. Stop trying to define the type for `data`. 

If we're in structured mode then the type is implicit based on the format (e.g. json) being used.
If we're in binary mode then it's just a blob of bytes - unless `ce-dataencoding` is defined.

I think this aligns with our "data PRs" too. But, more importantly, I don't think it actually changes what goes on the wire - it's really just a doc change.

Then we don't need to worry about map keys.

I dunno, maybe I'm missing it, but it feels like we're over complicating things.

**Comment by clemensv** [comment]
@duglin That is good thinking. I like that approach. In that case, we just need the datacontentencoding hint in JSON to tell whether the string is meant to be a binary, and the datacontenttype to figure out what's in the binary if it is a binary,   #471 #482

**Comment by duglin** [comment]
@clemensv @cneijenhuis (et al), see what you think:

full set of changes based on my comment above:
https://github.com/cloudevents/spec/compare/master...duglin:data

just spec.md:
https://github.com/cloudevents/spec/compare/master...duglin:data#diff-958e7270f96f5407d7d980f500805b1b

**Comment by evankanderson** [comment]
+1 for not trying to fit `data` into the schema used for Attributes, and making that a particular problem for the JSON encoding, rather than a general problem for all transports.

**Comment by cneijenhuis** [comment]
@duglin First of all, I'm in favor of that 👍 

However, I don't understand how it is fundamentally different to https://github.com/cloudevents/spec/pull/457 - which we've closed?

(TL;DR: Your suggestion removes the ability to take a JSON envelope with Map-as-JSON data, and turn it into an Avro envelope with Map-as-Avro data. Again, I'm fine removing that feature as I don't value it much, but @clemensv seemed to 🤷‍♂).

**Comment by duglin** [comment]
I can't explain the diff :-)  I'm just trying to digest everything I've heard - I don't claim to fully grok it all. I do suspect it might overlap with James' stuff though.

Can you elaborate on the Avro feature it doesn't support?

**Comment by duglin** [comment]
Created: https://github.com/cloudevents/spec/pull/484

**Comment by timbray** [comment]
For this reason, both XML and JSON explicitly exclude control characters, basically U+0000
   through U+001F with the exception of U+000A \n and U+000D \r. So if anyone tries to use one of those they're probably going to have trouble shipping them around the internet.  So I'll make a PR which defines the String type in a way that at least is shippable in JSON.   It seems likely that for certain types, a further restriction to ASCII is in order.

**Comment by timbray** [comment]
Oh drat, I'm wrong, JSON allows C0 characters but requires they be escaped, e.g. \u0000 is legal (but likely to cause problems)

**Comment by duglin** [comment]
@cneijenhuis will #485 address your concern?

**Comment by cneijenhuis** [comment]
> Can you elaborate on the Avro feature it doesn't support?

An example JSON: `{ "foo": 0 }`
If you know it conforms to the CloudEvents type system, you can simply map `0` to a 32-bit Integer. If it could be "any" JSON (and you want to map all of your events to the same type...), you have to choose between int, long, float, double. You need more info besides the plain JSON document to get that right.

**Comment by duglin** [comment]
Ah, thanks for the example. To me this falls into the "not our problem" category because even w/o CloudEvents if someone wanted to convert that JSON into Avro they would still have that problem.

And, I believe we should not get into the business of telling people what their `data` (business logic) should look like or what kind of constraints might apply to it.  One the main selling points for me of CloudEvents is the notion of "we don't ask you to change your data, we just augment it". And I've gotten a lot of positive feedback on that idea.

**Comment by duglin** [comment]
@cneijenhuis will #485 address this one or will we need a 2nd PR?

**Comment by cneijenhuis** [comment]
#485 addressed it :)
