### ISSUE TITLE
Should datacontentencoding list any transformations applied to the content wrapped by the data property?

### ISSUE THREAD

**Issue by willfranco** [cloudevents/spec#486]
Proposal:

The datacontentencoding should list all the transformations that were applied to the content that is wrapped by the data property.

For example: 

 In the case that we're compressing and encrypting the content wrapped by the data property, we should be listing in the datacontentencoding property such transformations in the order they were applied to the data.

{
...
"datacontentencoding" : "gzip; aesgcm"
...
}

Clients will be able to reconstitute the data by applying the same transformations in the reverse order.

Another nice change would be to change the datacontentencoding from a String to a JSON array to simplified its parsing.

"datacontentencoding" : "gzip; aesgcm" vs "datacontentencoding" : ["gzip", aesgcm"]

Thanks.

**Comment by duglin** [comment]
@clemensv any thoughts on this?

**Comment by evankanderson** [comment]
I think https://github.com/cloudevents/spec/pull/484 addresses this?

**Comment by duglin** [comment]
Closed due to https://github.com/cloudevents/spec/pull/492 - if incorrect please let me know
