### ISSUE TITLE
AMQP spec needs to treat datacontentencoding as special

### ISSUE THREAD

**Issue by alanconway** [cloudevents/spec#501]
Currently the spec only mentions 'data' and 'datacontenttype' as having special status. Now that events have a datacontentencoding attribute, it needs to be given the same status. It is treated in the same way - AMQP messages have a ContentEncoding property.

**Comment by duglin** [comment]
@alanconway we removed datacontentencoding last week.

**Comment by alanconway** [comment]
OK, did it get replaced with anything or have we decided that event data will never be compressed, base64 encoded etc?

**Comment by duglin** [comment]
for json we added a 2nd property (data_base64) to carry base64 encoded data: https://github.com/cloudevents/spec/blob/master/json-format.md#31-handling-of-data
Not sure if amqp needs something similar.  I'm assuming @clemensv would have touched that spec if it did.

**Comment by deissnerk** [comment]
@alanconway There is also [this discussion](https://github.com/cloudevents/spec/pull/496/files#r321721690) about using AMQP data and value sections. Would be great to get your opinion on this.

**Comment by alanconway** [comment]
That was why we agreed to include datacontentencoding in the first place - as an interoperable indicator across bindings. Is there a counter proposal to #371 that explains what to do now that it has been backed out? Or do we handle it separately in each binding and force bridges to decode and re-encode the payload at each hop?

**Comment by alanconway** [comment]
If we are restricting its use to base64 then the "each binding" approach seems OK. If we ever intend to use it for compression then it doesn't. We may be assuming compression to be handled at some other layer though.

**Comment by alanconway** [comment]
> @alanconway we removed datacontentencoding last week.

@n3wscott take note of above conversation - the go-sdk library needs updating.  I'm trying to figure out the ramifications for the binding package. I think it means every binding must unmarshal to raw binary data in the cloudevents.Event, and base64 is now a private detail of the JSON binding.

**Comment by duglin** [comment]
> I'm ok with the latter if we only care about base64 and assume that compression is somebody else's problem.

Someone please correct me if I'm wrong, but I believe that yes we only now care about base64. 
I think that compression could still happen but it would be a transport level concern - a layer above CE.

@cneijenhuis  @clemensv @n3wscott WDYT?

**Comment by duglin** [comment]
Where are we on this one?

**Comment by clemensv** [comment]
We only care about representing binaries inside JSON as base64 right now. That is the narrow use-case. We punted on everything else and leave that to the transport.

`datacontentencoding` ended up clashing with several concepts at once and got folks confused. The concept as we had it does not correspond to HTTP _transfer-encoding_ or _content-encoding_ (which are largely about compression). Our definition borrowed from RFC2045 content-transfer-encoding which has no clean mapping into any of the transports we have.  

There is no single metadata item that allows you to specify compression and "binary encoded as base64" in one field that we can lean on.

HTTP explicitly gets in the way of it, even: 


> [A.5.  Conversion of Content-Transfer-Encoding](https://tools.ietf.org/html/rfc7231#appendix-A.5 )

>   HTTP does not use the Content-Transfer-Encoding field of MIME.
>   Proxies and gateways from MIME-compliant protocols to HTTP need to
>   remove any Content-Transfer-Encoding prior to delivering the response
>   message to an HTTP client.
>
>   Proxies and gateways from HTTP to MIME-compliant protocols are
>   responsible for ensuring that the message is in the correct format
>   and encoding for safe transport on that protocol, where "safe
>   transport" is defined by the limitations of the protocol being used.
>   Such a proxy or gateway ought to transform and label the data with an
>   appropriate Content-Transfer-Encoding if doing so will improve the
>   likelihood of safe transport over the destination protocol.

**Comment by duglin** [comment]
@alanconway can we close this one with all of the recent changes that have gone in?

**Comment by alanconway** [comment]
Closing - since datacontentencoding is out of the abstract event there's no need to treat it specially in AMQP.
