### ISSUE TITLE
Inconsistency in Integer type mapping for AMQP 

### ISSUE THREAD

**Issue by alanconway** [cloudevents/spec#513]
Minor issue: the CloudEvents core spec defines an Integer as 32-signed, the AMQP spec maps it to AMQP long, which is 64-bit signed. AMQP has a 32-bit signed type (int) We should use matching types.

This might be a good time to review the decision to use 32 bits for CE Integer - .the CE spec now refers to JSON numeric format explicitly in the definition of Integer string encoding. It doesn't say anything about JSON integer range (and neither does JSON!), but the practical reality is 52 bits (IEEE double precision mantissa). Perhaps 64 bits is a safer bet for CloudEvents than 32, so we can handle the de-facto range of JSON-encoded integers into the future. Native 64 bit support is common these days, and where native support is lacking there's always a hack.

**Comment by duglin** [comment]
W/o commenting on the issue itself, Alan, can you open a PR today so it can be considered in this week’s call?

**Comment by alanconway** [comment]
Raised 32 vs 64 separately as #514

**Comment by clemensv** [comment]
The mapping to AMQP long is older than the 32-bit constraint for Integer, hence the mismatch. I think if we make a change, we should address #514

**Comment by deissnerk** [comment]
Would #514 and #513 then be v1 issues?

**Comment by alanconway** [comment]
I don't see this as a serious issue, but wanted to raise it for consideration before it was too late. 

My own implementation uses 64 bits outbound as per spec, and convert from any numeric type that fits in int32 on the inbound. 

I'm debating whether int32 or int64 should be the de-facto in-memory representation in Go, i.e. should I be lenient and let bigger numbers sneak through (e.g. JSON can do more that 32 bits and JSON programmers are not very bit-aware) or be strict and reject anything that doesn't fit int32...

**Comment by duglin** [comment]
@alanconway does this issue still need to be open or does #513 or #514 cover it?

**Comment by alanconway** [comment]
> @alanconway does this issue still need to be open or does #513 or #514 cover it?

The don't really cover it - this is an AMQP specific question, but I vote we close this in the spirit of not re-opening old decisions unless it's important. This isn't important. Restraining myself from hitting Close immediately... So ... Hard....

**Comment by duglin** [comment]
LOL  ok - anyone have any concerns with closing this issue?  @deissnerk  ?  if so please speak up before the call on Thursday otherwise I don't think we can restrain @alanconway much longer

**Comment by duglin** [comment]
agreed to close this on the 10/10 call
