### ISSUE TITLE
Review Integer mapping: 32 vs. 64 bit

### ISSUE THREAD

**Issue by alanconway** [cloudevents/spec#514]
The CE spec uses 32 bits for Integer - .this is likely the last chance to review that decision. 

I raise it because the spec now refers explicitly to the JSON string format for numbers in the definitoin of Integer. It doesn't say anything about JSON integer range (and neither does JSON!), but the practical reality is 52 bits (IEEE double precision mantissa). 

Perhaps 64 bits is a safer bet for CloudEvents than 32, so we can handle the de-facto range of JSON-encoded integers into the future. Native 64 bit support is common these days, and where native support is lacking there's always a hack.

I'm not 100% convinced either way but would like to air it one last time before its too late.

(Related to in #513)

**Comment by clemensv** [comment]
I am not 100% convinced either way, either.

**Comment by duglin** [comment]
Would it be possible to get a proposal for this before EOD tomorrow?  Either a PR or a proposal to close the issue.

**Comment by cneijenhuis** [comment]
Proposal to close this issue: At this very late stage, IMO, we shouldn't re-evaluate every decision unless we know it is a major concern. The current decision was part of the spec for a long time, and has not caused an issue so far.

**Comment by duglin** [comment]
Thanks @cneijenhuis , I tend to agree that unless we have new information we shouldn't reopen old/resolved issues.  Anyone have an concerns with closing this?

**Comment by alanconway** [comment]
No objection from me.

**Comment by duglin** [comment]
LOL I didn't mean for you to close it immediately, but obviously since you're the owner of the issue you can do so :-)  - and the issue-tracker in me is glad, but I was going to wait for the call to give people time to think about it. So, for others... if you believe there is a reason to keep it open just speak up and we can reopen if needed.

**Comment by alanconway** [comment]
Oops. Itchy trigger finger.

**Comment by black-snow** [comment]
I'd like to add to this:

With 32 bit signed integers we can't really use `Integer` for UNIX timestamps. We'd have to drop back to `String` but then we end up with comparison issues.
@alanconway @duglin

**Comment by duglin** [comment]
Given the current state of the spec, I think String may be your only option.
Maybe by 2038 we'll have a new rev of the spec and make INTs 64 bit :-)
