### ISSUE TITLE
Avro formatted data using application/avro

### ISSUE THREAD

**Issue by timjroberts** [cloudevents/spec#515]
When considering an Avro formatted event, following https://github.com/cloudevents/spec/blob/master/avro-format.md, I was wondering why the second example in section 4 (where it is using `application/avro` as the contenttype), shows the `data` mapping as a `string` with an example that appears to be base64 encoded?

Would this not be binary instead following the `bytes` Avro type? By determining that `datacontenttype` is set to `application/avro` and given that Avro is itself binary formatted, why would you need to encode it as a base64 encoded string? We treat the JSON example as bytes, why not this?

**Comment by clemensv** [comment]
I agree that this is a bug in that doc. Do you want to file a correcting PR, @timjroberts?

**Comment by timjroberts** [comment]
Will do. I'll try and put something up as soon as I can. Hopefully tomorrow.

**Comment by timjroberts** [comment]
PR for review: https://github.com/cloudevents/spec/pull/516
