### ISSUE TITLE
Concrete example using Open API 3

### ISSUE THREAD

**Issue by Robzilla** [cloudevents/spec#535]
Hi all

I am having a go at defining a Cloud Event using Open API 3. The example is a simple create an order to buy a stock through the mythical Acme stock broker. Yes I have fond memories of Wile E Coyote with his Acme products. Feel free to throw stones as I feel a concrete example is easier for some people to understand as reading the spec will only get you so far. I have attached the yml file as a txt file as the upload file filter seems to not like yml files.
[BrokerAPI.txt](https://github.com/cloudevents/spec/files/3723155/BrokerAPI.txt)

**Comment by duglin** [comment]
Anyone knowledgeable enough with OpenAPI to look this over?  @n3wscott ?

**Comment by n3wscott** [comment]
I don't see OpenAPI as a good match for CloudEvents overall. You can make a file that works with a selected encoding at a selected version of the spec, like HTTP Binary, or HTTP Structured. But where OpenAPI will fall short is trying to also include other encodings and other protocols. For this last reason, I think OpenAPI is not very inclusive for all of CloudEvents Bindings.

**Comment by n3wscott** [comment]
Looking at the example linked, this is not eventing. You are using the CloudEvents format to implement a request-response api. We have talked at length in the working group about eventing vs messaging and this might send the wrong message.

**Comment by duglin** [comment]
@Robzilla I'm going to close this issue as I think @n3wscott answered your question. Let me know if you think we need to reopen it.
