### ISSUE TITLE
Avro example required

### ISSUE THREAD

**Issue by pdebuitlear** [cloudevents/spec#554]
Would it be possible to get an example of an implementation with Avro (and Kafka) , similar to those given with the different SDKs.

**Comment by duglin** [comment]
@fabiojose any thoughts on this one?

**Comment by fabiojose** [comment]
Well, I can provide examples using java and js SDKs.

- Using Java with Kafka, Avro and Schema Registry

Is it may helps?

**Comment by duglin** [comment]
Is this something that would live in an SDK repo or the "spec" repo? If so, perhaps we could move this to the appropriate SDK repos?

**Comment by duglin** [comment]
any update on this?

**Comment by CH-karthikprasad** [comment]
+1

**Comment by fabiojose** [comment]
For me, It is something to live at sdk repos.

**Comment by duglin** [comment]
which repo do you want me to transfer this to?

**Comment by fabiojose** [comment]
Each one that has Kafka impl could have these examples, but for a start, we may transfer to java repo

**Comment by duglin** [comment]
I"m going to suggest that we close this and then if people are interested they can open an issue in each respective SDK repo.  Speak up if you disagree

**Comment by duglin** [comment]
Closing since there's no objection
