### ISSUE TITLE
Milestones is Unclear

### ISSUE THREAD

**Issue by grant** [cloudevents/spec#559]
The spec states:
> Supports CloudEvents at spec milestones and ongoing development version

However, milestones isn't defined anywhere. Do we mean every minor version tag?

Does the SDK need to create transformers for each spec version? Does a single SDK need to be able to handle events in different spec versions? `v1.0-rc1` too?

Supporting these various types would make developing and supporting the SDKs complicated.

**Comment by duglin** [comment]
I'd be ok with stating support for minor and major releases.  Not just "milestones" or "rc" releases.

@n3wscott @clemensv @fabiojose anyone else? wdyt?

**Comment by fabiojose** [comment]
What do you suggest Grant?

For me, supporting old specs like .1, .2 and .3 will be naturally removed when no more people are using it.

After all, I agree with Dug.
