### ISSUE TITLE
Kafka partition key clarification

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/spec#571]
In Kafka binding specification, [it's specified](https://github.com/cloudevents/spec/blob/master/kafka-protocol-binding.md#31-key-attribute) that the message key should be included in the event as `key` extension. But then, the specification links to the [partitioning extension specification](https://github.com/cloudevents/spec/blob/master/extensions/partitioning.md), which states that the key extension should be called `partitionKey`.

Which of the ones should be used?

**Comment by duglin** [comment]
@bluemonk3y any thoughts on this?

**Comment by duglin** [comment]
On 3/5 call we agreed to "PartitionKey"

**Comment by slinkydeveloper** [comment]
Now that I look again at this issue, `partitionKey` sounds a little bit confusing for Kafka specific: the Kafka Consumer in Java SDK returns [`ConsumerRecord`](https://kafka.apache.org/24/javadoc/org/apache/kafka/clients/consumer/ConsumerRecord.html), which exposes both the `key` of the message itself (which is what we mean as `partitionKey`) and the topic partition id, which is the number that identifies the partition where the message is stored. The same if for `ProducerRecord`, and generally other clients also exposes and allows you to set the partition id.
So looking at `partitionKey`, It's confusing for a Kafka user to understand if we're talking about the topic `partition` or the message `key`

**Comment by duglin** [comment]
@slinkydeveloper what do you suggest we do?

**Comment by slinkydeveloper** [comment]
The key in a kafka message is well defined by the kafka message specification already: I don't see the reason to add the partitioning extension, nor the `partitionKeyExtractor` thing which is just confusing. I think we should reword, removing both the partitioning spec link and the `partitionKeyExtractor`, and just state that the Kafka message key maps to the `key` extension of the event.

**Comment by cricket007** [comment]
Or `messageKey` & `partitionId` if you want to be verbose

**Comment by duglin** [comment]
@clemensv took an AI to write-up a proposal

**Comment by duglin** [comment]
@slinkydeveloper we can close this now, right?
