### ISSUE TITLE
Efficient alternative to batch in HTTP binding 

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/spec#574]
The HTTP binding has an encoding to send multiple events in the same envelope called [batch](https://github.com/cloudevents/spec/blob/master/http-protocol-binding.md#33-batched-content-mode).
This content mode is inefficient to implement in SDKs, because it requires the buffering of the whole HTTP body and the unmarshalling of the full json array.

I would love to search for more efficient encodings to send multiple events in the same envelope. Two examples that comes to my mind are:

* multipart bodies
* json streams (which are nothing more than newline separated json objects)

What do you think about it?

**Comment by aslom** [comment]
Even if it is not streaming it should still provide performance benefits by sending one batch of messages instead of multiple HTTP requests?

**Comment by aslom** [comment]
For multipart then CloudEvents could be send HTTP streaming with possibly adding it to next version of HTTP binding when we have implementation(s) supporting it?

**Comment by cneijenhuis** [comment]
My thought is that HTTP + JSON isn't the most efficient to start with, but probably the easiest. I'd lean towards easy/widely used concepts over efficient, but less used ones.

Also, I feel like... buffering the whole HTTP body and unmarshalling the JSON aren't big issues to start with. We recommend to keep the events small: https://github.com/cloudevents/spec/blob/master/spec.md#size-limits 
Assuming batches are not gigantic in size, I don't see a big improvement. Even if you have a batch of 100 events of 64 KB each, I don't think intermediaries (which choose to support batching) will have trouble with that.

**Comment by slinkydeveloper** [comment]
> My thought is that HTTP + JSON isn't the most efficient to start with, but probably the easiest. I'd lean towards easy/widely used concepts over efficient, but less used ones.

Agree, that's why I'm not saying we should replace batch. But having somehow a "batch" version of binary mode could allow to perform optimizations of several types.

> Assuming batches are not gigantic in size, I don't see a big improvement. Even if you have a batch of 100 events of 64 KB each, I don't think intermediaries (which choose to support batching) will have trouble with that.

Let's assume you have an intermediary that gets a batch of 100 events of 64Kb each, which is around ~6 Mb payload, and then ships this batch one request per time to somewhere else. This payload needs to be buffered, converted to json and then re-encoded back to the "final" request. Now assume you receive 10k of requests per second on this intermediary, you will end up with a quite lot of work to do in terms of memory allocations and cpu cycles every time you need to decode the json and encode it back, while I could potentially save some cpu/memory for the json decoding. That's why I'm proposing an alternative to a json array containing events encoded as json objects.

I suppose we can definitely have it as part of the spec, but not as an [hard requirement for the sdk](https://github.com/cloudevents/spec/blob/master/SDK.md#technical-requirements), which now doesn't require batch anyway

**Comment by cneijenhuis** [comment]
> you will end up with a quite lot of work to do in terms of memory allocations and cpu cycles every time you need to decode the json and encode it back

Yes, I fully agree. The server will have to do a lot of work to decode 6 MB of CloudEvents from and to JSON.

> while I could potentially save some cpu/memory for the json decoding

Here is where I don't follow. How is e.g. a JSON stream supposed to save a significant amount of CPU? You've got to decode ~6 MB, whether that comes in one blob or in a 100 * 64 KB = ~6 MB stream.
Same for memory allocations.

Peak memory consumption is lower if you stream, that's true. What I've seen some message APIs do is that they don't limit the batch size in terms of event count, but the size of the request.

Again, I'm leaning towards keeping it simple & stupid for implementations over squeezing a bit performance out of it.

**Comment by slinkydeveloper** [comment]
> How is e.g. a JSON stream supposed to save a significant amount of CPU?

You can potentially decode the events one by one and send them directly, allowing to perform some memory pooling, depending on the context you can apply several

**Comment by slinkydeveloper** [comment]
I've opened three PRs to explain my ideas:

* #592
* #593
* #594

**Comment by jchesterpivotal** [comment]
> The server will have to do a lot of work to decode 6 MB of CloudEvents from and to JSON.

I think this is where the Avro event format will shine.

**Comment by duglin** [comment]
@slinkydeveloper can we close this one given the status of the related PRs?

**Comment by jskeet** [comment]
I'd suggest closing, but trying to remember that we've got this issue - so that if we find folks are actually running into this as a problem in real life, we can reopen it rather than starting afresh.

**Comment by duglin** [comment]
Not hearing any objection - closing.
