### ISSUE TITLE
Revisit the name "source" in Events

### ISSUE THREAD

**Issue by inlined** [cloudevents/spec#58]
On February 1st 2018, we tentatively changed "resource" to "source". We agreed that "resource" is too confusing, but also that "source" may not be the best name. After clarify the meaning of this term we can reaffirm or change the name.

Assigned to: @inlined

**Comment by schatekar** [comment]
@duglin the idea of profiles can simplify this issue greatly. Irrespective of the domain/use case, there will always be an `origin` or `source` indicating who the publisher of the event is. 

Then a FaaS profile can add relevant extension fields to capture the information about various intermediate systems that the event passes through before it hits the function.

**Comment by inlined** [comment]
This seems to be quite settled.
