### ISSUE TITLE
How can i use cloudevents for kubernetes cluster

### ISSUE THREAD

**Issue by chandankumar4** [cloudevents/spec#581]
Is it possible to use cloudevents for kubernetes cluster, The requirement is to get the cluster resource event and store it to some database like elastic ..

**Comment by duglin** [comment]
Have you looked at the Kubernetes API Server event source in Knative?  
https://knative.dev/docs/eventing/sources/  and search for "Kubernetes"

**Comment by duglin** [comment]
Given the 👍 I'm gonna assume we can close this one. If I'm mistaken let me know and I'll reopen it.

**Comment by chandankumar4** [comment]
> Given the  I'm gonna assume we can close this one. If I'm mistaken let me know and I'll reopen it.

Thanks for your info @duglin but knative is not fit in my use-case, I just need the `kubectl get events`  data to elastic DB, like https://github.com/opsgenie/kubernetes-event-exporter is doing but can I do the same using cloudevents?

**Comment by duglin** [comment]
you'd need something to convert the events into a CloudEvent. If you look at the code for the Knative API Server Event Source, in there should be logic to take the incoming Kube event and convert it to a CE.  Some place near: https://github.com/knative/eventing/blob/master/pkg/adapter/apiserver/events/events.go#L101  I would guess.  perhaps @n3wscott can provide more info.

**Comment by chandankumar4** [comment]
okay! Let me check the codebase of knative.
