### ISSUE TITLE
content-type should be explicit 

### ISSUE THREAD

**Issue by yaronha** [cloudevents/spec#59]
We need the `content-type` attribute to be explicit (not part ofthe extensions), much like the schema is, without it there is no way to know how to de-serialize the `data`  

Assigned to: @yaronha

**Comment by duglin** [comment]
@yaronha do you want to take a pass at the PR for this one?

**Comment by schatekar** [comment]
@yaronha I assume you are suggesting to add `content-type` attribute on the context. Where do you define the content type for context itself?

**Comment by yaronha** [comment]
@schatekar @duglin i just did a PR see #64 
IMO the content-type for the context is transport/protocol specific e.g. in HTTP/AMQP headers, we may want to detail that

**Comment by schatekar** [comment]
That definitely needs detailing. 

Are you suggesting that, in case of transport being HTTP,  content-type on context gets transferred onto the HTTP header content-type (and similarly for other protocols)?

**Comment by yaronha** [comment]
@schatekar thats part of the original discussion we had (see my original CloudEvents proposal in: https://github.com/cncf/wg-serverless/tree/master/proposals/cloudevents)

For HTTP based messages (e.g. API Gateways, AWS Kinesis) that will happen automatically as the content type is specified in the request (app/json), other messages may choose older or more CPU/space efficient serialization (e.g. XML, gRPC, Avro, ..) and the only way to figure out the body type is through protocol headers (it cant be part of the body since you cant deserialize it w/o knowing the type)

**Comment by schatekar** [comment]
@yaronha @duglin 
Adopting a cloud event for a specific transport can get complex. Is it best to keep this spec focussed on defining the structure of the event? We can then have separate adoptions of the spec for each transport.

**Comment by yaronha** [comment]
@schatekar there is no sense in building specs that dont translate into a working and interoperable implementations, this is why we need the event message to have wire definitions in a way that producers and consumers work with each-other. it means you need to define how messages get serialised/deserialized and how metadata gets carried.

**Comment by schatekar** [comment]
@yaronha  I re-read what I said in my previous comment. I did not mean to say we build a spec that does not translate into a working and interoperable implementation (though I agree, it came out that way). What I wanted to say was, any design decisions in the spec should not be hugely influenced by one particular transport unless that is the only transport we want to support, which is not the case IMO.

**Comment by yaronha** [comment]
@schatekar we decouple the aspects of transport from message, can read about it in my original [CloudEvents proposal](https://github.com/cncf/wg-serverless/tree/master/proposals/cloudevents)  and in my [older CNEM proposal](https://docs.google.com/document/d/1dFfnWnbRDTvGwpwaBsvXRlw0ZyL3xYl7iXhYqbAPJjk/edit?usp=sharing), the way Headers/Context is passed will be transport specific (e.g. Headers in HTTP, AMQP, ..) and the way the message will be serialized can/should be flexible (e.g. Simplicity of Json vs Efficiency of Protobuf..), note that a message may traverse multiple transport hops, and maybe signed, so we do not want to deserialize and re-serialize the messages over and over. Anyway i'm not clear why you seem to object to this specific attribute ?

**Comment by schatekar** [comment]
@yaronha let me go through the links and get my thoughts together. I don't think I am objecting to this attribute. I am offering a counter-view based on my understanding of what the spec offers.
