### ISSUE TITLE
Reduce strictness in wording around Kafka < 0.10 data format 

### ISSUE THREAD

**Issue by OneCricketeer** [cloudevents/spec#591]
The Kafka spec states that the JSON format MUST be used for Kafka versions that do not support headers

Following #463, I'd simply say that any structured format that adheres to compatibility with the original JSON MUST be used. And that JSON COULD be used for human readability...

Lemme know your thoughts 😷

**Comment by duglin** [comment]
hi @cricket007, we discussed this on this week's call and agreed with you. Would you be willing to write-up a PR to address this?  I think the current thinking was to just remove the ` and encode the event in JSON` from the spec
