### ISSUE TITLE
Definition of Event in the terminology section is confusing

### ISSUE THREAD

**Issue by schatekar** [cloudevents/spec#6]
[Definition of Event](https://github.com/openeventing/spec/blob/master/spec.md#event) introduces terms `notification` and `message` without clearly defining their meaning in the context of an event-driven system.  There may be some implicit assumptions/understanding in there that be explicitly written. 

Assigned to: @schatekar

**Comment by duglin** [comment]
@schatekar PR #15 adds a first pass at "message". Would you like to open a PR to suggest a definition of "notification" ?

**Comment by schatekar** [comment]
@duglin I can give it a try. Do you want me to wait till that PR is merged or should I add it to the same PR?

**Comment by duglin** [comment]
I think a new PR now should be ok.

**Comment by schatekar** [comment]
@duglin  I have given it a try in [this commit](https://github.com/schatekar/spec/commit/5afe271e16d232fba87c926360bf8b17fbbd4357). Is it ok to ask you to take a look before I submit a PR?

**Comment by duglin** [comment]
@schatekar yup - just commented on the commit - overall, I like it.
