### ISSUE TITLE
Protocol binding for Apache Pulsar

### ISSUE THREAD

**Issue by smsufyian** [cloudevents/spec#604]
Apache Pulsar is another pub sub messaging system (http://pulsar.apache.org) . There is no binding available at the moment for this tool .

**Comment by s-m-sufyian** [comment]
I am willing to work on this issue

**Comment by bsideup** [comment]
Since it will match 99% of Kafka's, and given other systems like Pravega, perhaps a more generic binding for Kafka-like systems (Where "Kafka-like" defined as "a record with key, value, headers and partitions") would be a better direction?

**Comment by s-m-sufyian** [comment]
@bsideup yes it makes more sense to have a generic binding for Kafka and alikes , but what will you recommend for the 1% difference ? Or just ignore that 1% ? 
Also what other options we have which are alike Kafka other then Apache Pulsar ?

**Comment by duglin** [comment]
FYI - this was discussed on this week's call and there was no objection/concern to people working on a PR for this.

**Comment by s-m-sufyian** [comment]
@liangyuanpeng yes sure , lets discuss how to proceed further with this 

@duglin this is good news , awsome . So on it now

**Comment by duglin** [comment]
@smsufyian any update on this? Should we close it?

**Comment by duglin** [comment]
I'm going to propose we close this. We can reopen if someone is still interested in it

**Comment by duglin** [comment]
Not hearing any objection - I'm going to close. Always open to a new PR though
