### ISSUE TITLE
Invalid "subscriptions-api-openapi.yaml"

### ISSUE THREAD

**Issue by Thoemmeli** [cloudevents/spec#606]
I tried to use the provided yaml file in Azure API Management, but it failed:

![Issue creating API in Azure 2020-04-23 202943](https://user-images.githubusercontent.com/622679/80303415-74b16c80-87b0-11ea-9706-44525d19e582.png)

The expression "`example: null`" seems to be invalid for Azure API Management Service.

**Comment by duglin** [comment]
@Thoemmeli @mikehelmick would removing the property fix it?

**Comment by mikehelmick** [comment]
@clemensv

**Comment by duglin** [comment]
Oops wrong author. 🙂

**Comment by Thoemmeli** [comment]
Yes, removing the property is a possible fix. Sorry, I forgot to mention that.

**Comment by duglin** [comment]
@Thoemmeli  wanna PR it?

**Comment by Thoemmeli** [comment]
PR opened https://github.com/cloudevents/spec/pull/608
