### ISSUE TITLE
Discovery and Subscriptions are hard to understand

### ISSUE THREAD

**Issue by tweing** [cloudevents/spec#609]
I spent several hours reading through the documentation of [discovery](https://github.com/cloudevents/spec/blob/master/discovery.md) and [subscriptions](https://github.com/cloudevents/spec/blob/master/subscriptions-api.md) and my head is swirling around.

One of the possible issues is that the terminology is slightly different between the two documents.

## Discovery

In the discovery abstract it is written that "... for determining what events an Event Producer ... has available...", but then int he [Entities section](https://github.com/cloudevents/spec/blob/master/discovery.md#entities-in-the-api) the `EventProvider` and `Type` are mentioned as the basis of the directory.

The entity name `Type` is confusing to me, since it is used in different places in discovery. The `type` entity also has a `type` attribute? I propose to use `CloudEventType` as the entity here.

There are several inconsistencies in the discovery document for example here:

> producer entity Attributes
> The Provider entity is the main component of the discovery API. This section covers the structure of that entity and the next section describes the requirements for the query API.

The relationship between the entities is not clear to me, so I tried to draw it:
![image](https://user-images.githubusercontent.com/622679/80596411-9a47ab80-8a26-11ea-925d-ab63f09b715e.png)

## Subscription

The [yaml](https://github.com/cloudevents/spec/blob/master/subscriptions-api-openapi.yaml) file helps to understand the API and the intend.

Nevertheless I did not figure out the relationship between discovery and subscription in full.

Terminology for `Producer`, `Source` and `Consumer` are slightly different from the ones in discovery.

My understanding of the subscription model is the following (natssettings have been cropped):
![image](https://user-images.githubusercontent.com/622679/80596910-63be6080-8a27-11ea-8388-a3615c5ec1e6.png)

## Conclusion

Since I did not understand the intend of the two documents, I was not able to file a PR with suggestions. I propose to align terminology and give some more background information in the two documents. Use cases how to use the API's would actually help a lot.

**Comment by deissnerk** [comment]
@Thoemmeli You can contact me on the [CNCF Slack workspace](https://slack.cncf.io/), LinkedIn or Twitter (kdeissner). I'd rather not post my mail address here. 😄

**Comment by deissnerk** [comment]
@tweing In your diagram describing the discovery model, aren't the cardinalities the other way around? I think eventprovider and type are aggregations of producer. So imho the diamond shapes should at the other end. I understand the current model like this:

![CE-Discovery](https://user-images.githubusercontent.com/28010705/81726778-38f0f500-9488-11ea-9d55-ebc318ee5275.png)

**Comment by tweing** [comment]
@deissnerk Besides that this was exactly my struggle with the model, I believe you mixed up UML class diagrams (using multiplicity) with an Entity Relationship Diagrams (using cardinality). Specifically when you show the attributes in the different entities one might think these are foreign keys for a relational database. Those attributes `type` and `eventprovider` made me think too.
Nevertheless, I think the whole discussion was restarted by Doug.

**Comment by deissnerk** [comment]
@tweing I intentionally chose a database model, because I wanted to make the foreign key relations more explicit. These are imho important for the discussion of the different REST paths. The spec even uses terms like _composite key_. 

You are right about _mulitplicity_. This is the correct term for UML class diagrams, although the multiplicity is in the end about cardinalities:

[UML spec 7.8.8](https://www.omg.org/spec/UML/2.5.1/PDF ):
> A MultiplicityElement embeds this information to specify the allowable cardinalities for an instantiation of the Element.
