### ISSUE TITLE
Add PHP SDK to CloudEvents community efforts

### ISSUE THREAD

**Issue by grant** [cloudevents/spec#612]
PHP is an extremely popular programming language amongst web servers, more so than Ruby for example, which I'm not sure why we support it over PHP.

https://github.com/cloudevents/spec/blob/master/SDK.md#contribution-acceptance

We also have a Rust repo, which I'm not sure why we support that language more: https://github.com/cloudevents/sdk-rust

Do you mind if we create a PHP CESDK repo and add it to the list?

**Comment by duglin** [comment]
As long as we have people willing to keep it an activity community, I'm all for it.  I'll add it to the agenda for tomorrow's call so others can chime in.

**Comment by bsideup** [comment]
@grant FYI we just started working on a common set of (Cucumber-based) tests for SDKs, in case you want to integrate it and benefit from tests written by others (well, who don't? :D)

You will find the feature files here:
https://github.com/cloudevents/conformance/tree/master/features

And here is an example of them added to the Golang SDK (note the submodule):
https://github.com/cloudevents/sdk-go/pull/474

There is [Behat](https://docs.behat.org/en/latest/) framework for PHP to run Cucumber-based tests that should make it trivial to add them. Feel free to ping me in case you need help! 👍

**Comment by duglin** [comment]
Approved on the 4/30 call
See: https://github.com/cloudevents/sdk-php

**Comment by duglin** [comment]
Closing since I think we're all set
