### ISSUE TITLE
[Discovery] Investigate "sourcepattern" support

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#629]
From @deissnerk 
See: https://github.com/cloudevents/spec/pull/624/files#r427110899

@deissnerk would you be willing to take a first pass at this?

**Comment by deissnerk** [comment]
Yes, I can do that

**Comment by duglin** [comment]
@deissnerk still something you want to consider?

**Comment by deissnerk** [comment]
@duglin I think I did with #636 😄

**Comment by duglin** [comment]
Can we close this now?

**Comment by deissnerk** [comment]
@duglin As I said. Last year I did as you suggested and provided a PR that got merged. Although there is of course potential to further evolve the concept, I think that this issue can be closed.

**Comment by duglin** [comment]
@deissnerk thanks - just wanted to double check - closing
