### ISSUE TITLE
[Registry] de-normalize our data model?

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#630]
from @deissnerk 
See: https://github.com/cloudevents/spec/pull/624/files#r427115684

@deissnerk would you like to write-up a rough idea of what you think the changes to the spec would be?

**Comment by deissnerk** [comment]
This depends on what we want to achieve with discovery. Is the discovery API only used to support UIs for browsing events? Do people have in mind to generate boiler plate coding for event handling and generation based on the descriptions in discovery? Will there be some kind of document format to describe a set of events and services? This could be needed for registering a producer with an intermediary. The drafts for subscription and discovery are important pieces in the puzzle, but the overall picture is not yet clear to me. Perhaps we should work on a primer for these topics first.
Btw. #635 is also related to this.

**Comment by duglin** [comment]
@deissnerk do you still want to consider this one?

**Comment by deissnerk** [comment]
Yes, I think some of the questions raised in there are still valid. I hope I can address them with the proposal I'm working on.

**Comment by duglin** [comment]
Moved to https://github.com/xregistry/spec/issues/4
