### ISSUE TITLE
[Discovery] Do we need "producer" in the model?

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#635]
I'm not sure I understand what "producer" is meant to represent. Per the CE spec, "producer" is the entity that is creating the CloudEvent itself. Given that we already have the "Service", I'm not sure what "Producer" is or how/why the consumer who know or care who actually created the CE.

Also, the definition of producer says this:
- - -
Once discovery narrows down to a specific event `type` that we want to subscribe
to from a specific `service`, the appropriate `producer` entity can be
retrieved by key. The key is a composite key of the `service` and `type` names.
- - -
If the 'key' is derived fro 'service' and 'type', then do we need a separate entity in the model for it?

**Comment by deissnerk** [comment]
@duglin I agree it's confusing at the moment. For discovery, we summarized producer and intermediaries under producer. So for discovery, producer is the thing that delivers the events to you. On the other hand we introduced the subscription manager in the description of the subscription API, and things like the subscription endpoint may not be part of the producer. Perhaps the entity should be called `subscription-details`?
What would you propose to get rid of this entity?

**Comment by duglin** [comment]
I think this is old since "producer" isn't in our schema any more and our only ref to it is really a ref to CE's definition of it. Speak up if you think we need to keep this open.

**Comment by duglin** [comment]
Closing since there's no objection
