### ISSUE TITLE
Artifact Hub using Cloud Events

### ISSUE THREAD

**Issue by mattfarina** [cloudevents/spec#639]
I wasn't sure where to communicate this so I figured I would file an issue.

In the [Artifact Hub](https://artifacthub.io/) you can setup webhooks when an artifact is updated. The default payload uses cloudevents.

![Screen Shot 2020-06-08 at 9 25 15 AM](https://user-images.githubusercontent.com/62991/84035619-05f82f00-a96a-11ea-9db4-c559afd24e86.png)

Just wanted to pass this along. If there is another place I should put it please let me know.

**Comment by duglin** [comment]
That's pretty cool!  Thanks @mattfarina

**Comment by duglin** [comment]
very cool but going to propose we close this since there's no action to take.  All - let me know if you disagree

**Comment by duglin** [comment]
Closing since there's no objection
