### ISSUE TITLE
JSON schema allows only object and string for `data` attribute.

### ISSUE THREAD

**Issue by matejvasek** [cloudevents/spec#647]
JSON schema allows only object or string as data of CloudEvent:
```
   "datadef": {
      "type": ["object", "string"]
    },
```
however spec says that data may be any JSON value.

```
Unlike attributes, for which value types are restricted to strings per the type-system mapping, the resulting data member JSON value is unrestricted, and MAY contain any valid JSON.
```

**Comment by JemDay** [comment]
I think this an omission in the schema file, it would be a backward compatible change to fix - I'm willing to do a PR for that if required.

I believe prior to doing that we should ensure that the JSON format specification intended the following to be supported...

```
"datacontenttype" : "application/json",
"data" : {
    "foo" : "bar"
}
```

```
"datacontenttype" : "application/json",
"data" : "piece of data"
```

```
"datacontenttype" : "application/json",
"data" : 42
```

```
"datacontenttype" : "application/json",
"data" : true,
```
 
```
"datacontenttype" : "application/json",
"data" : [ "one", "two", "three" ]
```

**Comment by duglin** [comment]
Yes I believe those were intended to be supported.  A PR would be great!  thanks @JemDay
