### ISSUE TITLE
Should we consider changing default branch from master to main on this and SDK repositories?

### ISSUE THREAD

**Issue by lance** [cloudevents/spec#650]
Regarding the default branch name: https://sfconservancy.org/news/2020/jun/23/gitbranchname/

> Existing versions of Git are capable of working with any branch name; there's nothing special about ‘master’ except that it has historically been the name used for the first branch when creating a new repository from scratch (with the git init command). Thus many projects use it to represent the primary line of development. We support and encourage projects to switch to branch names that are meaningful and inclusive, and we'll be adding features to Git to make it even easier to use a different default for new projects.

**Comment by duglin** [comment]
What should we do about this one?  Perhaps an SDK person should open an issue in each SDK repo asking if they want to do this and then each SDK can decide for themselves?  @lance ?

**Comment by lance** [comment]
> What should we do about this one?

I think the github tooling is pretty good now so that PRs that are currently open against `master` just get changed to point to `main`. But to be honest I'm not 100% sure about that. Regarding SDKs, sdk-javascript was done a while ago. Not sure about the others.

**Comment by duglin** [comment]
Per the call today I opened up an issue in each repo asking them to switch. 
I think we can close this issue now and just deal with the issues in the other repos.
