### ISSUE TITLE
Primer: nested event details seem confusing

### ISSUE THREAD

**Issue by Groxx** [cloudevents/spec#653]
"Creating cloud events" contains this paragraph: https://github.com/cloudevents/spec/blame/master/primer.md#L419-L426

>There might exist special cases in which it is necessary to create a CloudEvent that contains another CloudEvent. Although the specification does not define nesting explicitly, it is possible. While the inner event will always be encoded in a stand-alone event format, the outer event can be either binary or structured mode. The datacontenttype attribute of the outer event must not be set to application/cloudevents+json or any other media type that is used to denote the usage of structured mode. A correct example of event nesting would be:

Which is... confusing to me.

1. "the inner event will always be encoded in a stand-alone event format": This seems unnecessarily prescriptive, as [stand-alone event formats are defined as being protocol-agnostic](https://github.com/cloudevents/spec/blob/master/spec.md#event-format), and seems to imply there is no other reasonable option.  Is there some advantage to be gained by choosing e.g. json?  It doesn't seem like consumers of the outer-event can generically understand any nested-event, especially as the spec defines no nesting (as it mentions in the second sentence)... so they'll necessarily have to understand _something_ about it being a custom nested format, and can do whatever is needed in that case.

2. "The datacontenttype attribute of the outer event must not be set to application/cloudevents+json ...": There don't seem to be any implied universal behaviors for specific datacontenttypes, much less `application/cloudevents+json` specifically, so I don't see why this should be avoided.  If there is some reason why it must be avoided?

3. There's no spec, but it's possible, and there's a correct way to do it: this whole paragraph seems a bit self-contradictory.  Maybe it'd be better to just get rid of it?

So I guess to summarize my questions:
1. why would protocol-agnostic inner data formats be the only option (equivalent to MUST)?
2. why MUST datacontenttype `application/cloudevents+json`(etc) be avoided?
3. should this paragraph just be removed?  if there's no spec for nesting, why mention it?

**Comment by Groxx** [comment]
Alrighty, 2 is clearer after reading e.g. the http spec, and does seem covered by the spec itself: it's to avoid ambiguity between binary mode and structured mode.  Makes sense.

An `application/cloudevents` type prefix seems to be the important piece here, but I don't see that spelled out in either the primer or the spec, which opens up questions like "is `application/cloudevents-batch+...` a structured-mode content type?".  That may be worth nailing down explicitly?  Without it, you open the door to intermediaries passing a binary-mode message to something that interprets it as structured-mode, due to differences in what they consider relevant content types.

**Comment by duglin** [comment]
If I remember correctly....
1 - I believe we have to use a stand-alone/structured format for the inner event because we were concerned about conflicting data. If the inner event was binary, where would the CE attributes for the inner event live? They can't appear as HTTP headers w/o conflicting with a binary outer CE. In the case of a structured outer CE, would they appear as attributes in the outer CE and conflict? Or, as http headers and the confuse the receiver as to whether the outer event is binary or structured? And I think this answers your "2", which you said in your 2nd comment.

3 - maybe. But enough people asked about it during the development of the spec that we felt like we had to say something about it.

I do consider batched to be a form of structured since the type starts with "application/cloudevents". I'm not sure we come right out and say this though, nor do we say that each item in the batch MUST use structured.... seems like it might though.

What do others think?

**Comment by deissnerk** [comment]
1. 
>"the inner event will always be encoded in a stand-alone event format": This seems unnecessarily prescriptive, as stand-alone event formats are defined as being protocol-agnostic, and seems to imply there is no other reasonable option. 

The inner event is by definition protocol-agnostic. It is wrapped into the payload of another event and therefore decoupled from the protocol being used. 

2. This issue with `application/cloudevents+xxx` is that the [context attributes may be present in the header, too](https://github.com/cloudevents/spec/blob/master/http-protocol-binding.md#323-metadata-headers). So there would potentially be a conflict between context attributes of the inner and the outer event.

3. Nesting is not explicitly specified, but it isn't excluded either. I added the paragraph to save people from running into 2. Proposals to make this less confusing are welcome. 😄

**Comment by duglin** [comment]
Do people think we can close this one? Speak up if you'd like to keep it open
