### ISSUE TITLE
XML Format

### ISSUE THREAD

**Issue by rektide** [cloudevents/spec#662]
Hello.

I would enjoy having an XML Format for Cloud Events. I have some existing XML processing systems, and trying to integrate Cloud Events messages from other systems with these XML systems relies on some informal JSON->XML glue. It would be lovely to have a real specification for what Cloud Events look like in XML.

**Comment by rektide** [comment]
Since it seems like JSON is the only format right now, I'm interested to see how #626 goes.

**Comment by JemDay** [comment]
Glad to see there are still people interested in XML ;-)

I would advocate for an "attribute heavy model" for efficiency reasons, if I survive the protobuf escapade I might be talked into remembering XML schema syntax ;-)

**Comment by duglin** [comment]
Since we're now introducing specs with an API, it seems only logical to not only talk about XML  but SOAP/WebServices bindings  :-)

**Comment by clemensv** [comment]
@duglin is still hurting from the RESTafarians having won the war.

Thumbs up for an XML format.

**Comment by duglin** [comment]
I think we can close this one now. @jem?

**Comment by duglin** [comment]
I'm going to close this one as we have an XML format now. If I've jumped the gun please let me know and I'll reopen it.
