### ISSUE TITLE
What's the attribute key for sampled-rate extension?

### ISSUE THREAD

**Issue by spirilis** [cloudevents/spec#667]
https://github.com/cloudevents/spec/blob/v1.0/extensions/sampled-rate.md

I see from prior histories of this document that more information was specified at one point in the past - including a "sampledRate" (changed to "sampledrate") key, for which the value was as the current document specified.

However a recent commit deleted all the information about this, leaving the document rather confusing as it specifies the concept of a sampled field with the requisite Value definition, but no key used to define it.

**Comment by duglin** [comment]
@deissnerk I think your PR made this change... any thoughts on this?

**Comment by duglin** [comment]
Closing since #832 addressed this
