### ISSUE TITLE
Webhook-Allowed-Origin instead of Webhook-Request-Origin

### ISSUE THREAD

**Issue by schabungbam** [cloudevents/spec#673]
For the webook, http-webhook.md - in the example of using a wildcard for the validation response, do we mean Webhook-Allowed-Origin instead of Webhook-Request-Origin?

**Comment by deissnerk** [comment]
I think you are right. 😃 
Do you want to create a PR for this?

**Comment by duglin** [comment]
ping @clemensv ^^

**Comment by duglin** [comment]
On 6/17 call, @deissnerk said he'd open a PR for this.

**Comment by duglin** [comment]
#673 addressed this one - so closing.
Not sure why github didn't close it.
