### ISSUE TITLE
[Registry] Detecting changes in the discovery service

### ISSUE THREAD

**Issue by clemensv** [cloudevents/spec#676]
It would be great for the discovery service to raise CloudEvents about state changes:

* Types being added/removed/changed
* Services being added/removed/changed

**Comment by n3wscott** [comment]
Could this be exposed by an entry in the services list? 

Additionally, you could use the subscription api to subscribe to these change events.

**Comment by duglin** [comment]
Seems like the PR for this would be to define the basic outline of what the Discovery Endpoint Service entry would look like - along with the schema of the events themselves (which could live in the schema registry).

Anyone want to volunteer to take a first pass?

**Comment by duglin** [comment]
@n3wscott will take a pass at it - ping him if you want to help

**Comment by duglin** [comment]
Moved to: https://github.com/xregistry/spec/issues/5
