### ISSUE TITLE
[Registry] Add support for partial name matching

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#682]
If we adopt #664 then we should investigate how we can add the ability to search by "name" w/o it being a complete match.

**Comment by duglin** [comment]
I was wondering if we should consider that there might be more than one matching algorithm that people will want to support. And, so perhaps we should define a really simple one and then allow for extensions to define/use others.

I thought about trying to use the stuff in the Subscription API spec but that seemed a bit chatty for our needs from a syntax perspective, from semantically it seemed ok. I think we want to keep it to be something that can be specified in a URL.  However, we also should probably make it something that can easily be mapped into popular search mechanisms, like regex.

With that, I'm bouncing between two options:

Option 1:
- people can do prefix/suffix matching via "*" at the start or end of the value
- people can include a `?language=xxx` parameter if they want to use some other query language

Option 2:
- all values have an implied "* at the start and end. Which basically means people don't need to do anything special at all :-)
- people can include a `?language=xxx` parameter if they want to use some other query language

I'm leaning toward 2 just because it's the easiest for people, but 1 is more explicit.
e.g.
```
opt 1: http://example.com/service?name=*object*
opt 2: http://example.com/service?name=object
```
both would yield the same results.

However, this might be problematic because then we can never have an attribute name that matches some query-parameter option we might want to create for the discovery spec. To deal with that perhaps we could do this:

```
opt 1: http://example.com/service/?.name=xxx    # query names start with '.'
opt 2: http://example.com/service/?q=name=xxx   # double ='s
opt 3: http://example.com/service/?q:name=xxx 
```

We would then support searching over all fields. For fields that are nested we'd use `abc.def` format. For example:
```
# all services that support the github opened event
opt 1: http://example.com/service?events.type=com.github.issue.opened
opt 2: http://example.com/service?.events.type=com.github.issue.opened
opt 3: http://example.com/service?q=events.type=com.github.issue.opened
opt 4: http://example.com/service?q:events.type=com.github.issue.opened

# Multiple searches are ANDed:
e.g   http://example.com/service?q:name=object&q:events.type=created
```

Net:
I'm leaning towards:
```
http://example.com/services?q:name=db&q:events.type=inserted&flag=true
```
- all services that have "db" in the name (case insensitive) AND have a type with "inserted" as part of the string (case insensitive)
- and whatever "flag" option is defined to mean would be applied since its value is "true"

Thoughts?

**Comment by anishj0shi** [comment]
This looks a nice fit for odata protocol based url syntax: more details: https://docs.oasis-open.org/odata/odata/v4.01/os/part2-url-conventions/odata-v4.01-os-part2-url-conventions.html#sec_URLComponents
 odata was designed to query humongous databases over rest and supports a lot of query operations from the URL itself.

**Comment by duglin** [comment]
@anishj0shi was there a specific section you had in mind?  Was the $filter what you had in mind?

**Comment by anishj0shi** [comment]
@duglin that's correct. ODATA spec has a very elaborative and an expressive mechanism to define filter criteria to query data. 
https://docs.oasis-open.org/odata/odata/v4.01/os/part2-url-conventions/odata-v4.01-os-part2-url-conventions.html#_Toc31361038

**Comment by duglin** [comment]
Moved to: https://github.com/xregistry/spec/issues/6
