### ISSUE TITLE
[Discovery] Drop /types endpoint.

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/spec#684]
The `/types` endpoint is nothing more than data processing, forcing the implementor to do this data processing should be reconsidered. I would recommend dropping the `/types` endpoint in favor of some other solution that can do the pivot filtering that is out of scope for CloudEvents. CloudEvents should have the responsibility stop at providing the raw data, not an opinionated projection of the data.

**Comment by nachocano** [comment]
I agree with @n3wscott. I was building a prototype of this in my [eventing fork](https://github.com/nachocano/eventing/tree/discovery/pkg/serverless/discovery) to better understand how we can leverage this spec for custom events with our Broker/Trigger/EventType objects, and all the grouping by types was extra processing and also extra burden to implement, and I'm not sure it added much value. 

Also, it seems to me that we have some kind of cycle... type --> service --> types. 

According to this output of `/types`:

```
{
  "TYPE-VALUE": [
    {
      "id: "{id}",
      "url": "{url}",
      "name: "{name}",
      ... remainder of Service attributes ...
    }
    ...
  ]
  ...
}
```

Say for example I have service `my-svc` that emits types `t1` and `t2`, then the output would look something like this:

```
{
  "t1": [
    {  ...
      "name: "my-svc",
       ...
      "types": [
         { "type": "t1",
            ...
         },   
         { "type": "t2",
            ...
         }, 
       ],
    }
  ],
  "t2": [
    { ...
      "name: "my-svc",
       ...
      "types": [
         { "type": "t1",
            ...
         },   
         { "type": "t2",
            ...
         }, 
       ],
    }
  ],
}
```

Is my interpretation correct?

**Comment by duglin** [comment]
Yes it is a bit of a cycle, but it also allows you to go from "one type" -> "service(s)" -> "what other types does that service support".  So it's not 100% redundant, more like additive.

But I do prefer the idea of getting rid of /types and just using /services?type=...  type of thing instead.
