### ISSUE TITLE
[Discovery] the query pattern match for "matching" on /types and "name" on /services are not aligned.

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/spec#686]
The query key "matching" on `/types` does not indicate that type name is what is is being fuzzy matched. But `/services` have a query param for "name", which does indicate what it is matching, but it does not do fuzzy. This is not symmetrical and it likely should be.

**Comment by duglin** [comment]
good catch. Let's resolve #685 and #684 first tho

**Comment by n3wscott** [comment]
From Klaus Deissner

 This is how OData does filtering http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752358 

 https://www.odata.org/getting-started/basic-tutorial/#filter

**Comment by duglin** [comment]
On the 8/20 call we discussed this and people seemed to want some kind of fuzzy search but want it to be optional to support. They also want it to apply to more than just "name".

Additional comments:
OData filtering: https://www.odata.org/getting-started/basic-tutorial/#filter
Scott: http://serviceroot/Airports?$filter=contains(Location/Address,%20%27San%20Francisco%27)

**Comment by sdatspun2** [comment]
Would it be ok to adopt a simple query language such as FIQL https://tools.ietf.org/html/draft-nottingham-atompub-fiql-00?

> If the argument string begins or ends with an asterisk character ("*"), it acts as a wild card, matching any characters preceding or following (respectively) that position.

**Comment by duglin** [comment]
@n3wscott close in favor of https://github.com/cloudevents/spec/issues/682  ?

**Comment by n3wscott** [comment]
sounds good.
