### ISSUE TITLE
Is there a spec version history available?

### ISSUE THREAD

**Issue by jskeet** [cloudevents/spec#687]
I'm looking at the spec version support in the C# SDK - I'd like to *at least* remove support for 0.1 and 0.2, and I want to check the differences between 0.3 and 1.0 to see how awkward it is to support both. (The spec *recommends* but doesn't *require* supporting 0.3, so I think it's reasonable to explore how tricky that is.)

Currently I can see https://github.com/cloudevents/spec/releases/tag/v1.0 which gives the differences between 1.0 and 1.0-rc1, but not in a particularly helpful semantic way... and there's nothing similar earlier than that.

Is there a document I've missed somewhere that gives the information in a form useful to SDK developers, or am I best off just doing a diff of the 0.3 and 1.0 spec? If that *is* the best option available, would a version history doc be welcomed? If I'm going to have to write up notes myself, I might as well share it...

**Comment by duglin** [comment]
@jskeet good questions.  Unfortunately, the list of github PRs per release that we put into the release notes is really all we have now. If you have the time/desire to write-up a more human friendly description of the major diffs between v0.3 and v1.0 I think that would be great!

**Comment by jskeet** [comment]
Righto - will do. I don't expect it'll be *soon* (as this is only one of the many pies I have my fingers in), but hopefully I'll have something in the next couple of weeks.

**Comment by duglin** [comment]
@jskeet any update on this?  No worries if you're busy... just doing a quick issue triage.

**Comment by jskeet** [comment]
I'm afraid not - I'm hoping to get to it next week. Still on it.

**Comment by jskeet** [comment]
Right, some genuine progress now. I've *only* compared `spec.md` in v1.0 vs v0.3, but here are the changes - I believe this is an exhaustive list aside from reformatting and moving paragraphs around a bit:

- Use "producer" and "consumer" instead of "sender" and "receiver"
- Clarification that intermediaries should forward optional attributes
- Remove constraint that attribute names must start with a letter
- Remove suggestion that attributes names should be descriptive and terse
- Clarify that a single occurrence may result in more than one event
- Add an Event Data section (replacing `data`), making event data a top level concept rather than an attribute
- Introduce an Event Format section
- Define structured-mode and binary-mode messages
- Define protocol binding
- Add extension attributes into "context attributes" description
- Move mention of attribute serialization mechanism from "context attributes" description into
  "type system"
- Change "transport" to "protocol" universally
- Introduce the Boolean, URI and URI-reference types for attributes
- Remove the Any and Map types for attributes
- Clarify which Unicode characters are permitted in String attributes
- Require all context attribute values to be one of the listed types,
  and state that they may be presented as native types or strings.
- Require `source` to be non-empty; recommend an absolute URI
- Update version number from 0.3 to 1.0
- Clarify that `type` is related to "the originating occurrence"
- Remove `datacontentencoding` section
- Clarify handling of missing `datacontenttype` attribute
- Rename `schemaurl` to `dataschema`, and change type from URI-reference to URI
- Constrain `dataschema` to be non-empty (when present)
- Add details of how `time` can be generated when it can't be determined, specifically around consistency within a source
- Add details of extension context attribute handling
- Add recommendation that CloudEvent receivers pass on non-CloudEvent metadata
- Sample CloudEvent no longer has a JSON object as a sample extension value

That's probably not quite in the format we want for a history document, but it's a start. @duglin - any feedback on that list before I look at creating a PR for a new file?

**Comment by duglin** [comment]
closed via #784
