### ISSUE TITLE
WebSockets protocol binding

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/spec#693]
As discussed in 2020/08/13 Serverless WG meeting, there is some interest in the community to develop a Websocket protocol binding spec, in order to allow users to send CloudEvents in websocket streams

**Comment by slinkydeveloper** [comment]
I can kick-off the initial work and then we can iterate on it @n3wscott @clemensv @lance

**Comment by n3wscott** [comment]
Sounds good!! I have played around with a simple version in https://github.com/n3wscott/sockeye/ but at this point the javascript sdk has a better impl than mine.

**Comment by lance** [comment]
@slinkydeveloper works for me. The javascript sdk has an example here https://github.com/cloudevents/sdk-javascript/tree/main/examples/websocket.

Sending an event

https://github.com/cloudevents/sdk-javascript/blob/eca43d907468dd07d9f291bb56f95f658f4b3c40/examples/websocket/client.js#L28-L33

Receiving an event
https://github.com/cloudevents/sdk-javascript/blob/eca43d907468dd07d9f291bb56f95f658f4b3c40/examples/websocket/client.js#L15-L23

**Comment by lance** [comment]
To be honest, it seems like this could be pretty straightforward. The [JSON Event Format](https://github.com/cloudevents/spec/blob/v1.0/json-format.md), which I think all SDKs currently support, makes it pretty simple to just shove JSON across the wire. If we also wanted to support pushing AVRO formatted events for better throughput, that could imply some kind of handshake or content negotiation before events are sent.

**Comment by slinkydeveloper** [comment]
I'm writing down a protocol binding that uses the [subprotocols feature](https://tools.ietf.org/html/rfc6455#section-1.9). I tested an implementation using your websocket sample @lance
