### ISSUE TITLE
[Subscription API] Update subscription is strange REST

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/spec#696]
The current open api doc implies that to update a subscription, you `PUT` to the `subscription/` endpoint. 

I would expect there to be an id in that url for an update. 

In-fact, the standard RESTful way would be to use an endpoint without an id means generate the id. 

I would expect more of the following:

POST `subscription/` <-- creates a subscription and an id for you.

POST `subscription/{id}` <-- creates a subscription with the given id, must not exist with modifications. 

PUT `subscription/` <-- not allowed.

PUT `subscription/{id}` <-- Creates Or updates with the given ID.

**Comment by clemensv** [comment]
That's a bug, indeed.
