### ISSUE TITLE
[Discovery API]  Consider adding history

### ISSUE THREAD

**Issue by erikerikson** [cloudevents/spec#699]
Resulting from discussion 9/17/2020 about #690 during weekly call.

The notion of soft versus hard deletes of service records was being discussed in the context of #690.  The question came up of how consumers of the API react to either.  In a larger context, if we offered a log of the actions taken to define the service (a stream of CloudEvents) there would be no ambiguity and adding support for stream processing would benefit users of such architectures.  That log could be compacted (or not) as Clemens noted.  Ensuring the log is strictly ordered according to observation by the node would support consistency.  Access to the materialization of that log would remain in the specification and could be based on the events, although that would likely be an implementation detail.

**Comment by duglin** [comment]
@erikerikson, or any one else, is this something we'd like to more strongly consider? Should someone take an AI to open a PR? Or is this still in a "thinking about it" state?

**Comment by erikerikson** [comment]
Certainly that would be my preference but being involved rather than committed I'm reticent to exert my preference.  I wouldn't say that there isn't a significant community that shares the preference on the other hand.

**Comment by erikerikson** [comment]
via #868
