### ISSUE TITLE
May need to add event combination and define a way to express event combination

### ISSUE THREAD

**Issue by cathyhongzhang** [cloudevents/spec#70]
In some use cases, a function might be triggered to run by a combination of events. For example, a function could be triggered when both event-x and event-y happen or when either event-x or event-y happen. We may need to consider this in this spec? 

Assigned to: @cathyhongzhang

**Comment by cathyhongzhang** [comment]
I can own this issue

**Comment by deissnerk** [comment]
@cathyhongzhang That sounds really interesting. Would that be part of the cloudevents spec or of the serverless application model you mentioned last week in the call?

**Comment by cathyhongzhang** [comment]
deissnerk: Good question! I think it probably should be part of the serverless application model.

**Comment by deissnerk** [comment]
@cathyhongzhang I have given this issue and #72 some more thought. In addition to the above described combination of events, you may have multiple event processors that do not consume an event but add more sub events like "received on queue xyz" or "signature validated successfully". 
I think based on this we could define roles or patterns for event processing. E.g.
- gateway (forward events between domains, delete sub events, ...)
- enricher (add sub events)
- combinator / state machine (what you described above)
- provider
- consumer
- ...
What do you think?

**Comment by duglin** [comment]
@cathyhongzhang if you agree that solving this problem should be done by something like an "application model", should we close this? It seems like we're focusing on defining the individual events themselves and how groups of events might be correlated would be out of scope - for now.

**Comment by deissnerk** [comment]
@duglin Specifying an application model is definitely out of this spec's scope, but a **common understanding** how the specified events are going to be used should be a prerequisite. Right now I've got the feeling that in the discussions at least the **common** is missing. 
The sub events I mentioned would be part of a single event. I am assuming  that the original event is immutable while being forwarded through the system. So the additional hops would need some means to add additional information. For this I could also use #72, though. 
@cathyhongzhang you created this issue. What do you think?

**Comment by cathyhongzhang** [comment]
@duglin  If for now we only like to concentrate on single event definition, then I can close this one for now.  @deissnerk I think you raised a very important point. You can use #72. I will add my input to #72.
