### ISSUE TITLE
[Discovery] PUT ... import vs update?

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#701]
How should the client indicate which one is the intent?
How about `?import` to mean "import" and  lack of the query param means "update" ?

**Comment by grantr** [comment]
_Cross-posting https://github.com/cloudevents/spec/pull/690#discussion_r492411991. I realized too late that this conversation was split off from #690._

**Comment by duglin** [comment]
I'm going to close this one since I think #690 covers it... and if not we'll bring this up again during interop testing
