### ISSUE TITLE
[Discovery] should epoch be global

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#704]
Should the epoch value be a global, cross services within a D.E., value? Then people can ask for all changes since a certain epoch value?

One issue would be how to deal with importing services - w/o agreement on what epoch means and syncing of those semantics (e.g. clock syncing across hosts) it seems like a real challenge.

**Comment by duglin** [comment]
For https://github.com/cloudevents/spec/pull/707 I decided that retaining the epoch value during an import causes too many problems so I removed that requirement. This means that it opens the door for a more global epoch value, if we want.

Anyone thought more about this? I kind of like the idea of this for the "give me the changes since...." type of query. Will make syncing large DEs easier. At least for those cases where people don't want to be notified via events.

**Comment by deissnerk** [comment]
I wonder, how changes to attributes like `authscope` and `subscriptionurl` are handled. Attributes like these may be adjusted by a DE to reflect a local eventing infrastructure. If epoch had to be retained during import, what would happen, if a DE had to mix in these changes?

**Comment by duglin** [comment]
yet another reason why I don't want to retain the epoch value :-)   The original pain-point I ran into what import, make a change and bump epoch, and then import again... while sync'ing with other DEs I had no idea who was really the latest.

**Comment by duglin** [comment]
Based on the 10/15 call.. will look at a new global epoch value separate from the service specific one

**Comment by duglin** [comment]
As of now `epoch` is scoped to the resource and until we have a concrete usecase that requires something more I think we can close this. Ping me if I jumped the gun.
