### ISSUE TITLE
[Discovery] Discuss REST API

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#706]
As I was coding things up for the interop I realized that I wanted the option to upload lots of Service Entries into a D.E. all in one shot. Which would be the nice opposite of what `GET /services` will do... download a bunch in one shot.

I'm probably going to open a PR for `POST /services` to take an array of Services instead of just one, but it got me thinking that it might be good to write down, and brainstorm, on the overall pattern of the REST APIs. Then people can see it all in one easy spot to make sure it all looks consistent and makes sense:

```
VERB URL (+Body)                       -> Action
-------------------------             --------------------------------------
GET  /services                         -> []Service
GET  /services/{id}                    -> Service
POST /services + []Service             -> creates new Services (new id/epoch)
POST /services?import []Service        -> imports Services (id/epoch are retained)
PUT  /services/{id} + Service          -> updates an existing Service (just epoch is updated)
PUT  /services/{id}?import + Service   -> import a Service (id/epoch are retained)
```
Does this seem ok?

(I don't care about the word "import", that can change, it's the overall pattern that I'm wondering about)

**Comment by clemensv** [comment]
The "import" switch is a good idea if we want to allow bulk import as a push operation from the outside. 

I would generally lean towards making those import operations a pull operation by the importing service, also for synchronization, which should be triggered by change events.

**Comment by duglin** [comment]
Closing for now
