### ISSUE TITLE
Release strategy for CloudEvents

### ISSUE THREAD

**Issue by deissnerk** [cloudevents/spec#719]
Since we released version 1.0 of CloudEvents, we did almost all changes in the master branch. Many changes were non-normative, but there are normative changes like #713, too. There were also additions like protocol bindings. I wonder, which of the PRs that were merged into master branch after the 1.0 release need to be down-ported. 

### Example
Before #713 was merged, it wasn't clearly defined how to deal with `null` in JSON format. Would an SDK implementation that raises an error, if a `null` value occurs, still be CloudEvents 1.0 compliant?

### The new specs
We started new specifications for discovery and subscription in the same repository. I suppose they will be versioned independently from the main spec. The README page already lists the formats and protocol bindings with their own versions. 

### Release strategy
How will we do releases in the future? Do we create releases of the whole spec repository and list the spec version of each contained spec? We could then even do more frequent releases without increasing the spec versions. The releases would then contain a set of specs that are intended to be used in conjunction.

Any ideas?

**Comment by duglin** [comment]
Per the 12/3 call - we agreed to treat #713 as a non-breaking change, so I think we can close this now.
