### ISSUE TITLE
[Subscription-API] Outlining Difference b/w subscriptionconfig and protocolsettings 

### ISSUE THREAD

**Issue by anishj0shi** [cloudevents/spec#724]
it seems that the property [subscriptionconfig](https://github.com/cloudevents/spec/blob/master/discovery.md#subscriptionconfig) in discovery api is somewhat similar to the [protocolsettings](https://github.com/cloudevents/spec/blob/master/subscriptions-api.md#321-subscription-object) property in the subscription api. 
Are there any fundamental differences b/w these two if yes, then we probably should outline it and if there's no difference b/w the two then, it'd be a nice idea to remove one of them and stay consistent.

**Comment by duglin** [comment]
Been doing some thinking about this one and decided to write down my rambling thought process here: https://docs.google.com/document/d/19U0N3r7k2nPWI_bRQ8ZMhXHyv9gTMEU3EkOZGmAmAbY/edit

The net result of my thoughts are:
- I think we need an OR for our "simple" Filter stuff
- I think we need to allow for filtering of things outside of the Message
- Filtering should be optional to support for Subcription Managers
- Discovery needs to include indication of what type of filtering is supported (e.g. dialect, properties, etc..)
- The specs shouldn't try to force when an implementation uses Filters or Config options - meaning, the impl should decide when something is a config option vs specified as a filter

But I'd love to hear what other people think.

As for this issue, I created https://github.com/cloudevents/spec/pull/752 to try to address it.

**Comment by duglin** [comment]
Closing due to #752 being merged
