### ISSUE TITLE
design goals for CloudEvents V.1

### ISSUE THREAD

**Issue by ultrasaurus** [cloudevents/spec#73]
Roadmap says: Agree on design goals for CloudEvents V.1. for January

I don't think we've actually accomplished this.  

@ac360 got together last week and brainstormed what might be an interim goal that would be useful in aligning a core subset of meta data:

* draft specification that WG members agreed *could* work
* at least 3 sample events that conform to the specification

Assigned to: @ultrasaurus

**Comment by duglin** [comment]
@ultrasaurus does #88 address this or is an additional PR needed?

**Comment by ultrasaurus** [comment]
The above interim goals are addressed in PR#88, but we still lack design goals, see #101

**Comment by ultrasaurus** [comment]
yes https://github.com/cloudevents/spec/pull/101 resolves this issue. 

I've opened https://github.com/cloudevents/spec/issues/121 for the separate roadmap about the scope of the spec.
