### ISSUE TITLE
CloudEvents Expression Language

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/spec#730]
I want to propose to start a new effort to develop an expression language to filter CloudEvents.

## Motivation

One of the main drivers is the ability to have more powerful filtering capabilities in the subscription API, where the existing filter dialect `basic` is not powerful enough for most of production use cases. I foresee an eventual application of such language in the Discovery API and the Workflow spec. 

## Expected outcome

Our goal is to develop a spec for an expression language tailored for CloudEvents. Some goals of this language are, but not limited to, the following features:

* [Total functional programming language](https://en.wikipedia.org/wiki/Total_functional_programming), hence the termination of the evaluation of the expression is always guaranteed
* Type system conform to the [CloudEvents type system](https://github.com/cloudevents/spec/blob/master/spec.md#type-system)
* Boolean operators (and/or/nor/xor)
* Comparison operators on the types provided by the type system
* Regex
* Function invocation semantics + basic built-ins (e.g. type assertions/casting, 

It's out of the scope of the effort to develop a generic expression language, hence the input of the expression will always be a `CloudEvent`.

## Notes

* We could help the implementers providing the antlr grammar for it.
* We should implement this language in our sdks (I'm willing to help for java, golang, rust).
* I would prefer to exclude payload filtering from the initial efforts, since I consider it a complex argument (It comes to my mind problems like payload too big, supporting different content types, ...)
* We don't want anything particularly fancy regarding the syntax, so my feeling is that we should a C-like syntax or similar, something familiar for cloud developers out there

**Comment by lance** [comment]
You don't explicitly call it out, so I have to ask... this would also include arithmetic expressions, correct? (like calculating pi :rofl:)

**Comment by slinkydeveloper** [comment]
@lance do you have a use case for including arithmetics? I didn't included them now, but if they're useful, i guess we can add them to the scope

**Comment by lance** [comment]
> @lance do you have a use case for including arithmetics? I didn't included them now, but if they're useful, i guess we can add them to the scope

No I don't really, so maybe what you have is sufficient.

**Comment by deissnerk** [comment]
@slinkydeveloper Good idea! You can count me in under "people interested in this" 😄

**Comment by deissnerk** [comment]
This might provide some inspiration:
[https://www.tbray.org/ongoing/When/201x/2019/12/18/Content-based-filtering](https://www.tbray.org/ongoing/When/201x/2019/12/18/Content-based-filtering)

**Comment by loopingz** [comment]
One of the concerns we heard in the past, was resources intensive filtering, it is pretty common on regexp. As you might not have control over who is calling your subscription API we need to find a way to limit its impact

**Comment by jamesurquhart** [comment]
Would this language necessarily be executed on a source/producer infrastructure? Couldn't an intermediate (such as an edge node) or the consumer itself (via the SDK?) be a better place to process some filtering? Should CloudEvents determine where to execute a filtering request, and if so, how? (Long time listener, first time caller. Forgive me if I am missing key context.)

**Comment by slinkydeveloper** [comment]
> One of the concerns we heard in the past, was resources intensive filtering, it is pretty common on regexp. As you might not have control over who is calling your subscription API we need to find a way to limit its impact

I guess the simple solution to the "regex" problem is to make it an optional builtin 

> Couldn't an intermediate (such as an edge node) or the consumer itself (via the SDK?) be a better place to process some filtering?

Yes, the design of this language should be agnostic from the "executor", which component in which place of the infra executes it

**Comment by slinkydeveloper** [comment]
I managed to sketch some ideas and I wrote them down in a doc. It's not a spec, it's not formal, It's more a braindump with all the ideas I have for this language: https://hackmd.io/@fcByUhAFQKOgNywKFruHOA/B18qKs59w

**Comment by slinkydeveloper** [comment]
As requested by some members of the community in the various Serverless WG meetings, I've developed another draft of a language with the same goals, but SQL like, in order to compare the alternatives we've on the table.

* C-like, more oriented to developers: https://hackmd.io/@slinkydeveloper/B18qKs59w
* SQL-like, more oriented to data engineers: https://hackmd.io/@slinkydeveloper/S1ZXgFSyu

Please check out both and get back with opinions on which approach we should follow.

**Comment by beriberikix** [comment]
Might I throw another suggestion in the ring, if only to help as a point of comparison? Google has a spec for their [Common Expression Language (CEL)](https://github.com/google/cel-spec) and examples of their use are  [Cloud IAM](https://cloud.google.com/iam/docs/conditions-overview) & [Firebase](https://firebase.google.com/docs/rules/get-started) (I was on the Firebase team many years ago.) It is worth noting that in Google's new language [CUE ](https://cuelang.org/) they do not use CEL (here's [why](https://cuelang.org/docs/usecases/generate/#cel).)

**Comment by slinkydeveloper** [comment]
I'm going to close this as I think most of the work to boostrap the spec is done

**Comment by duglin** [comment]
@DanielYWoo  I think you're referring to https://github.com/cloudevents/spec/blob/main/cesql/spec.md right? It's still a work-in-progress. Most of our focus has been on the Discovery spec right now, but eventually we'll get around to the secondary specs, such as CESQL, Subscription API, etc...
