### ISSUE TITLE
Vote: rename "master" branch to ....

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#731]
This issue will track the votes for the rename of the "master" branch. Options are:
1 - "dev"
2 - "next"

The following companies/people are eligible to vote:
commercetools, Continental, Google, IBM, Microsoft, NATS/Synadia, Nokia Bell Labs, Nuxeo, RX-M, SAP, Splunk, VMWare, Erik Erikson, Tommy Chung, Sanjay Dalal

Since we're not having a call next week, this vote will last 2 weeks and end at the start of the next regular weekly call (12pm ET on Dec 2).

You may either vote by adding a comment to this issue or during that next call.

**Comment by duglin** [comment]
Email with more info/history:  https://lists.cncf.io/g/cncf-cloudevents/message/197

**Comment by n3wscott** [comment]
VMware votes `3 - "main"`

and second `2 - "next"`

**Comment by loopingz** [comment]
Nuxeo: "next"

**Comment by duglin** [comment]
IBM votes "dev"

**Comment by grant** [comment]
I'm not sure if this a unique issue with this repo.
Personally, I'd expect the default branch for this org's repo to eventually be `main`.

1. Per GitHub renaming guidance: https://github.com/github/renaming
1. It's the default branch for new GitHub repos since Oct. 1, 2020

**Comment by loopingz** [comment]
@grant what was discussed during the last call is that the default branch should be the latest published version, so even if we end up choosing 'main' as the development branch it won't be the default.

**Comment by duglin** [comment]
if you can vote, please add a comment instead of thumbs up - just to make it official

**Comment by duglin** [comment]
IBM/Red Hat votes for "dev".

On the last call we agreed to make the github default branch be the latest release (v1.0.0 as of now) so that people coming to the repo would be presented with the latest approved spec. This would avoid possible confusion and them picking up newer (unreleased) spec changes. With that change, we need to make it clear which other branch is the "development" branch that contains work-in-progress changes. "dev" conveys that thought. "main" does not since it could mean anything along the lines of "latest", 
primary" or "most significant" branch, and that could be easily confused with "latest release".

**Comment by bryeung** [comment]
Google votes for "main", with "dev" as a second choice.

**Comment by deissnerk** [comment]
SAP votes "next".

The guidelines from github do not necessarily apply, as our use of the repository is not software development as such, but authoring and publishing a specification. For a specification "next" appears to be more appropriate than "dev".

**Comment by duglin** [comment]
Just to be clear... 'main' technically isn't on the ballot per our last call

**Comment by gcolliso** [comment]
Synadia/NATS votes "dev"

**Comment by dbaldwin-splunk** [comment]
Splunk - "dev"

**Comment by duglin** [comment]
Vote was closed at the start of the 2020/12/3 call - results are:
Commercetools - Christoph - 
Continental - Matthieu - 
Google - Bryan - dev
IBM/Redhat - Doug - dev
Microsoft - Clemens - dev
NATS/Synadia - Ginger - dev
Nokia Bell Labs - Manuel - 
Nuxeo - Remi - next
RX-M - Christian - 
SAP - Klaus - next
Splunk - David - dev
VMWare - Scott - next
Erik Erikson - next
Tommy Chung - dev
Sanjay Dalal - dev

Total: dev: 7   next: 4
