### ISSUE TITLE
roadmap with milestones

### ISSUE THREAD

**Issue by ultrasaurus** [cloudevents/spec#74]
Proposal to adjust the roadmap to have numbered milestones to help focus our work.

Based on a brainstorm with @ac360:

https://docs.google.com/document/d/1ZLCWPeNcNyjttvgo2QHY9CMtzDaA0_81vmh5C-r9QB4/edit

Assigned to: @ultrasaurus

**Comment by markito** [comment]
LGTM overall but not sure why the removed items were removed.  We could discuss more about that during the call.

**Comment by duglin** [comment]
@ultrasaurus can you turn this into a PR so people can see it in full context? It'll be easier/faster to review

**Comment by duglin** [comment]
@ultrasaurus can we close this now that #88 is merged?

**Comment by ultrasaurus** [comment]
yes, this is resolved -- thank you!
