### ISSUE TITLE
CloudEvents Website

### ISSUE THREAD

**Issue by barkerd427** [cloudevents/spec#75]
This was mentioned in the call today. We're currently hosting a simple site on SquareSpace. Do we want to use something like Hugo and just run it using GitHub Pages? The current site is pretty simple, so it wouldn't take much to convert it.

Here are some potential theme options:
* https://themes.gohugo.io/hugo-theme-lean-launch-page/
* https://themes.gohugo.io/material-docs/
* https://themes.gohugo.io/theme/hugo-base-theme/

These basically represent three options that are quite different from each other, but all can allow the website to grow without changing much as more is added or linked to. The first option is the most basic and is very similar to what exists today. The second is a little more advanced and allows us to link to multiple items in GitHub from the main page. The third is the most elaborate with a picture and a simple blog capability.

I think my preference would be for the second option. I'm happy to do any work to transfer what exists today. I just want to know if there's any interest in this.

**Comment by ac360** [comment]
Hi @barkerd427, 

This sounds great.  We've always had the intention of moving to our own option via Github Pages.  If you are up for handling the transition, this would be super helpful.

I think the 2nd theme will work well too.  I recommend keeping it very simple since many things are still in flux.  Imitating the styles and the content of the current site is a good first step for now, IMO.

If you're up for this, I'll get you the email list config (Mailchimp).

**Comment by barkerd427** [comment]
I agree. I'm just going to mimic what exists now.

I'm definitely up for getting this transitioned. Feel free to send the info and I'll work on getting everything set up and ready to transition.

**Comment by barkerd427** [comment]
I can't say I'm happy with this, but here's my start: http://danbarker.codes/cloudevents-org/

The code is here: https://github.com/barkerd427/cloudevents-org

I've mostly overridden the original theme, so it may make sense to create a separate theme soon or switch to something when/if we want this to be more elaborate.

**Comment by duglin** [comment]
my only comment so far is that there's a lot of wasted whitespace on the sides, so I would reduce that so you can add more space between the columns. Would reduce the the odds of them columns feeling like they're squeezed together.

-Doug

**Comment by ac360** [comment]
@barkerd427 Thanks for getting this started.  I believe we can improve the design.  Do you mind if I take a shot at it via PR?

**Comment by barkerd427** [comment]
Go for it! Some work stuff came up, and I haven't been able to cycle back
yet.

**Comment by duglin** [comment]
Since we have a new website, can we close this one now?

**Comment by barkerd427** [comment]
We need a second repo named cloudevents-web or something similar to store the code. The current repo will store the generated content. Once I load everything, I'll probably need someone with more permissions to configure GitHub Pages.

**Comment by duglin** [comment]
@barkerd427 I just created: https://github.com/cloudevents/cloudevents-web and made you an admin. Let me know if you need anything else. And thanks!

**Comment by barkerd427** [comment]
Thanks @duglin. I don't seem to have admin permissions to that repo and I can't push to it.

**Comment by duglin** [comment]
@barkerd427 look for an invite to join the repo

**Comment by barkerd427** [comment]
Thank you. Kinda sad I don't know how GitHub works yet.

**Comment by barkerd427** [comment]
I've got the website updated. We need to complete the 3rd item on this link: https://help.github.com/articles/quick-start-setting-up-a-custom-domain/

**Comment by barkerd427** [comment]
This is now complete. Thank you for your help. We can now make all updates in GitHub and Travis will run to deploy the updated site when there's a merge to master.
