### ISSUE TITLE
Subscription OAS use of required and anyOf 

### ISSUE THREAD

**Issue by manuelstein** [cloudevents/spec#758]
I've noticed the subscription-api-openapi.yaml doesn't validate and found a couple of bugs:

The operation /subscriptions/{id}, which has id as a path field, has two occasions trying to make {id} optional (GET and OPTIONS), which is not allowed per OAS (see [4.7.12.2 parameter fixed field 'required'](https://spec.openapis.org/oas/v3.0.3#fixed-fields-9)).

The content body when creating a subscription is rightfully required, but the spec is missing the required attribute - allowing to send POST /subscriptions operations without a body.
Same goes for updating (PUT /subscriptions/{id}) operations whose content (proposed subscription object) is required.

The protocolsettings currently use anyOf in the context of specifying a single object. It's correct to have only one protocolsettings object held by the parameter as the subscription can only choose a single protocol. Semantically, oneOf is a better fit here.

**Comment by duglin** [comment]
#761 is merged - closing
