### ISSUE TITLE
Align discovery OAS and discovery spec 

### ISSUE THREAD

**Issue by manuelstein** [cloudevents/spec#759]
To use client code generators etc, the discovery OAS should be aligned with the spec implemented in the interop effort.

- specversions is specified a list of strings, but OAS uses an object.
- subscriptiondialects is described in the spec as "`Array` or `URI-reference` valuies", where in fact it should be strings (note that OAS uses the term List and Array interchangeably, protocols parameter is described as a "List"), suggesting "List of `String` values"
- OAS is missing id, epoch and subscriptiondialect altogether
- the spec currently doesn't distinguish the subscription object from the embedded event types object (it lists type and other event type parameters alongside subscription parameters), suggesting to separate

**Comment by duglin** [comment]
#760 is merged - closing
