### ISSUE TITLE
Add @dan-j to @sdk-go-maintainers

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/spec#764]
Following the process defined here: https://github.com/cloudevents/spec/blob/v1.0.1/community/SDK-GOVERNANCE.md#new-maintainers

**Who's dan-j?** Daniel has made several important contributions to sdk-go, in particular in the space of stan/nats. We would love to include him in the sdk-go maintainers team to further develop and improve the project. 

**Question**: Do you want to add @dan-j as sdk-go-maintainer?

**Entitled to vote**:

* @cloudevents/sdk-go-maintainers 

**Voting ends**: 8th February 2020 17:00 CET

Required agreement: 50% + 1

**Comment by slinkydeveloper** [comment]
+1

**Comment by n3wscott** [comment]
+1 🎉

**Comment by duglin** [comment]
vote passes.
