### ISSUE TITLE
Question about proto spec

### ISSUE THREAD

**Issue by Andrew-Wichmann** [cloudevents/spec#779]
Hi,
it appears to me that [the proto spec](https://github.com/cloudevents/spec/blob/v1.0.1/spec.proto) violates [the attribute naming convention](https://github.com/cloudevents/spec/blob/v1.0.1/spec.md#attribute-naming-convention) because it uses `_` in a few of the attributes (ie. `spec_version`).
Is this intentional?

Andrew

**Comment by duglin** [comment]
@JemDay

**Comment by jskeet** [comment]
The protobuf field names aren't CloudEvent attribute names though. They're just part of the proto representation of the CloudEvent, which doesn't need to conform to any particular conventions - just like it would be fine to have JSON within a JSON-event-formatted CloudEvent that happened to contain non-lower-case JSON properties.

In this case, the names wouldn't even end up being part of the transport message anyway - the binary wire representation of protobuf messages uses the field numbers, not the names. (The JSON representation of the protobuf messages wouldn't have underscores, but would have capital letters - but I don't think that's expected to be used.)

**Comment by JemDay** [comment]
+1 to @jskeet's comments.

The only place where the real 'names' are used would be in the map of that's used to carry the optional and extension attributes - those are keyed by a (hopefully) spec-compliant attribute name.

**Comment by duglin** [comment]
On the March 4th call the WG agreed with the above comments and to close the issue.
@Andrew-Wichmann if you think more discussion is needed please let us know

**Comment by Andrew-Wichmann** [comment]
It still doesn't really make sense. What's the difference between CloudEvent attributes names and a "proto representation of the CloudEvent"?

**Comment by Andrew-Wichmann** [comment]
I see, so the thing that translates to and from the CloudEvent and this protobuf message knows which proto field maps to which CloudEvent attribute, so there is no rule saying they must be named the same?

Is that right?

**Comment by jskeet** [comment]
Yes, exactly. (And indeed if we did name them the same, it would be non-idiomatic within the proto file.)
