### ISSUE TITLE
Reference section of spec should show CloudEvents version of examples

### ISSUE THREAD

**Issue by benkehoe** [cloudevents/spec#78]
The examples under the Reference section of the spec are useful, but it would be enlightening for a more outside observer like me if they had a comparison with what those events might look like when transformed into the CloudEvents spec.

**Comment by ultrasaurus** [comment]
I think we decided this should live outside of the specification.  There's another issue to move the specific references elsewhere: https://github.com/cloudevents/spec/issues/19 -- will work on a PR for that now!

**Comment by duglin** [comment]
@benkehoe would you be interested in working on a PR for this? Perhaps one that extends the current "references.md" file and for each type of event in there it shows one possible serialization/mapping to the CloudEvents fields.  This might be a bit premature, but at the same time, I kind of like the idea of being able to see which fields map to our fields vs which would end up in "extensions".  It could help us see if we made a mistake by defining one, or not defining one.

**Comment by duglin** [comment]
Does anyone want to run with this one? If no one speaks up by the call this week I'm going to suggest that we close it.

**Comment by duglin** [comment]
on the call today we agreed to close this issue - we can reopen if new info comes up.
