### ISSUE TITLE
WebHook "Origin" header concept clashes with RFC6454

### ISSUE THREAD

**Issue by clemensv** [cloudevents/spec#781]
https://github.com/cloudevents/spec/blob/v1.0.1/http-webhook.md#21-delivery-request 

We mandate that push deliveries made after the abuse protection handshake use the "Origin" header.

While our Web Hook delivery notion of "Origin" is somewhat similar in intent to the Origin concept defined in RFC6454 and as used, for instance in CORS (W3C/WHATWG, https://fetch.spec.whatwg.org/#origin-header) it is not the same. The RFC6454 concept refers to the relationship of sequences of HTTP requests amongst each other (referrer, but without path), and the Origin points to the server to which the prior request was made whose result is now motivating this request. Our notion of Origin describes the originating server of the request and it purely an identifier.

To make matters worse the RFC6454 Origin header holds a URI and our header is a DNS style expression.

We have two choices here:

a) We are not at all referencing RFC6454 in our spec, which means we can just take the stance that our "Origin" header is a different thing. The problem is that existing HTTP clients do indeed know about RFC6454. Arguably, WebHook push requests are always issued independent from other requests, meaning that the RFC6454 concept does not apply.
b) We change our header name for delivery requests to 'WebHook-Request-Origin', e.g. the same as for the validation handshake.

**Comment by deissnerk** [comment]
Conceptually I'd prefer b), but it would break existing implementations of our spec, wouldn't it?

**Comment by duglin** [comment]
is "WebHook-Request-Origin" a CE thing or is it part of some formal RFC?  I looked but couldn't find one.

**Comment by duglin** [comment]
@clemensv we chatted about this on today's call and the group appears to be headed more towards "b" - do you want to create a PR?
