### ISSUE TITLE
Webhooks link is broken

### ISSUE THREAD

**Issue by raminorujov** [cloudevents/spec#811]
Introduction section of [HTTP Webhooks spec document](https://github.com/cloudevents/spec/blob/v1.0.1/http-webhook.md) contains [a broken link http://progrium.com/blog/2007/05/03/web-hooks-to-revolutionize-the-web/](http://progrium.com/blog/2007/05/03/web-hooks-to-revolutionize-the-web/)

**Comment by duglin** [comment]
thanks!
@clemensv do you know if it's been moved? I wasn't able to find it doing a quick search.
Would pointing to: https://en.wikipedia.org/wiki/Webhook  be sufficient?

**Comment by duglin** [comment]
Lu Dang found it: https://progrium.github.io/blog/2007/05/03/web-hooks-to-revolutionize-the-web/index.html
I'll PR it - thanks for the issue

**Comment by raminorujov** [comment]
Thanks
