### ISSUE TITLE
[Kafka spec] Conflicting sentences in message mapping

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/spec#812]
In message mapping paragraph we have 2 sentences:

> The receiver of the event can distinguish between the two content modes by inspecting the content-type Header of the Kafka message. If the header is present and its value is prefixed with the CloudEvents media type application/cloudevents, indicating the use of a known event format, the receiver uses structured mode, otherwise it defaults to binary mode.

My interpretation is the following:

```
if content type is present and value is prefixed with application/cloudevent {
  structured
} else {
  binary
}
```

This logic is the same as every other protocol binding spec we have. But then, a couple of lines below, we have this sentence:

> If the content-type header is not present then the receiver uses structured mode with the JSON event format.

This is in contrast with the above sentence, because if the content type is not present, following the above pseudocode, i should fall in the second branch.

I suspect this second sentence was placed to make the behaviour more _kafkesque_, because in kafka the content-type of a topic is usually known at-priory and using content-type header is not really kafka-idiomatic

**Comment by slinkydeveloper** [comment]
Proposals to fix (we should accept one of the two):

* https://github.com/cloudevents/spec/pull/813: This just align with the other protocol bindings
* https://github.com/cloudevents/spec/pull/814: This adopts the more _kafkesque_ approach, that is when no content type header is there, then it's a json structured cloudevent

**Comment by slinkydeveloper** [comment]
@duglin can we close this one?

**Comment by duglin** [comment]
ok looks like we can close this one since #813 was merged. Let me know if I'm mistaken
