### ISSUE TITLE
Add k8s based release notes tool and automation.

### ISSUE THREAD

**Issue by n3wscott** [cloudevents/spec#817]
We have decided to leverage the tool developed in k8s to extract release notes from PRs for releases. 

- [x] Add PR template to include the release-note body.
- [ ] Add a document for PR process expectations. 
- [x] Add GitHub Action automation to extract release notes with manual invocation. 
- [ ] Add a document outlining how to use the action.

**Comment by duglin** [comment]
@n3wscott any update on this?

**Comment by n3wscott** [comment]
Fell off the radar, thanks for the ping. I think I did start some of this, let me look....
