### ISSUE TITLE
Definition: Occurrence

### ISSUE THREAD

**Issue by clemensv** [cloudevents/spec#83]
https://github.com/cloudevents/spec/blob/master/spec.md#occurrence 

The definition of "occurrence" is unnecessarily narrowing the scope of what an occurrence may be, especially by calling out specific technologies/protocols. 

Suggestion:

An "occurrence" is the capture of a statement of fact during the operation of a software system. This may occur because of a signal raised by the system or a signal being observed by the system, because of a state change, because of a timer elapsing, or any other noteworthy activity.

Assigned to: @clemensv

**Comment by duglin** [comment]
@clemensv can you open a PR with your proposed change?

**Comment by clemensv** [comment]
Yes. FWIW, I think it's useful to have issues for PRs.

**Comment by duglin** [comment]
PR #90 is the PR for this one, its merged, so closing this issue.
