### ISSUE TITLE
Add @jcrossley3 to @sdk-rust-maintainers

### ISSUE THREAD

**Issue by slinkydeveloper** [cloudevents/spec#842]
Following the process defined here: https://github.com/cloudevents/spec/blob/v1.0.1/community/SDK-GOVERNANCE.md#new-maintainers

**Who's jcrossley3?** Jim has made several important contributions to sdk-rust, in particular in the last release with the reorganization of the package integrations to compile time features. We would love to include him in the sdk-rust maintainers team to further develop and improve the project. 

**Question**: Do you want to add @jcrossley3 as sdk-go-maintainers?

**Entitled to vote**:

* @cloudevents/sdk-rust-maintainers 

**Voting ends**: 16th July 2021 15:00 CET

Required agreement: 50% + 1

**Comment by slinkydeveloper** [comment]
+1

**Comment by dejanb** [comment]
+1 non-binding

**Comment by bobmcwhirter** [comment]
+1 if my vote makes any difference.

**Comment by ctron** [comment]
+1 (not sure I am eligible to vote)

**Comment by andrewwebber** [comment]
+1

**Comment by linuxbasic** [comment]
+1

**Comment by Lazzaretti** [comment]
+1

**Comment by lance** [comment]
+1

**Comment by duglin** [comment]
looks like the vote passed. Welcome  @jcrossley3
