### ISSUE TITLE
no redirects in webhook spec

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#847]
In https://github.com/cloudevents/spec/blob/v1.0.1/http-webhook.md it says: 
> The response MUST NOT use any of the 3xx HTTP Redirect status codes and the client MUST NOT follow any such redirection.

I'm wondering if this is too restrictive - what if the endpoint is correct, but the sender used http instead of https. The server needs to reject it with a 4xx instead of a 3xx redirecting the client to use https?

Is the assumption here that we don't want redirects because senders will often be machines and we don't want them to act as DDOS clients due to a rogue server? I guess we could assume that it's a config error if they weren't using https from the starts.   Thoughts @clemensv

**Comment by GrahamCampbell** [comment]
> but the sender used http instead of https

This is not allowed, and a hard error being triggered is the right approach here, to avoid accidently sending events in plain text and having the issue silently hidden.

**Comment by clemensv** [comment]
@duglin the point is that we don't want a rogue subscriber abusing the push-agent, correct.

What you could construct with redirects is that you have a rogue subscriber that has the push-agent point to an endpoint that redirects all requests to a victim endpoint that did not opt into deliveries.
