### ISSUE TITLE
Definition: Event

### ISSUE THREAD

**Issue by clemensv** [cloudevents/spec#85]
https://github.com/cloudevents/spec/blob/master/spec.md#event

The specification should either drop "occurrence" or nor restate a partial definition in "event".  

Suggestion:

An "event" is a data record expressing an occurrence and its context or a set of occurrences and their shared context. Events are routed from the emitting [re]source to interested parties for the purpose of notifying the about the [re]source occurrence. The routing may be performed based on information contained in the event, but an event will generally not identify a specific routing destination.

Assigned to: @clemensv

**Comment by duglin** [comment]
@clemensv wanna open a PR?

**Comment by clemensv** [comment]
Yes, I am logging issues first and then doing PRs

**Comment by duglin** [comment]
@clemensv ok - we're not that formal here, you can go straight to a PR if you want. The extra noise isn't necessary.

**Comment by ultrasaurus** [comment]
By the way, we agreed to use the term "source" for now, and I think dropping the "[re]source" will make the definition more readable.  Introducing the idea that an event should represent "a set of occurrences" is new -- I would think that packaging a group of events together would be a transport-level optimization, though I haven't thought about that deeply.

I do like your wording.  Would love to see a PR that just clarifies the wording, without adding the multiple occurrences for now.
