### ISSUE TITLE
[Discovery] Duplication?

### ISSUE THREAD

**Issue by erikerikson** [cloudevents/spec#850]
With projects like [Amundsen](https://github.com/amundsen-io/amundsen) or [Atlas](https://atlas.apache.org/) are we perhaps [reinventing the wheel](https://xkcd.com/2140/) and missing out on a more mature and full featured capability?  We have tended to avoid any kind of leader making and the current specification is purpose built and lean so building it out may be the right course of action regardless.

Are there open source alternatives we should seriously consider?

**Comment by jskeet** [comment]
I think this is particularly important if we're expecting Discovery not to be CloudEvent-specific (which I *think* was one of the things I picked up on...)

**Comment by duglin** [comment]
On the 8/5 call @erikerikson agreed to write a comparison between our spec and those other projects so we can compare/contrast the features and UX

**Comment by duglin** [comment]
@erikerikson based on your quick look at these do you think we need to change direction?

**Comment by erikerikson** [comment]
I haven't made time to review these.  I believe the work we are doing remains useful and necessary.  In lieu of an active reason to shift, I would suggest we proceed.

**Comment by erikerikson** [comment]
Closing for now to reduce issue noise.  If a fit for purpose offering exists, we can consider it in the future.
