### ISSUE TITLE
Subscription API: type and source filtering

### ISSUE THREAD

**Issue by odacremolbap** [cloudevents/spec#859]
Subscription API contains these 3 optional fields:

- [source](https://github.com/cloudevents/spec/blob/master/subscriptions-api.md#source-1): filters CloudEvents based on the mandatory source field. 
- [types](https://github.com/cloudevents/spec/blob/master/subscriptions-api.md#types): filters CloudEvents based on a set of the mandatory type field.
- [filters](https://github.com/cloudevents/spec/blob/master/subscriptions-api.md#filters): filters CloudEvents based on a set of expressions and attributes.

`types` and `source` seems to be overlapping the `filters` field.
`types` is an array, a consumer can subscribe to many of them using a single subscription, while `sources` does not.

Trying to understand the design I would say that the spec is expecting `types` and `source` filters more often than custom expression filters, and that it would be more common to filter on multiple types than on a set of sources, but I still find the `type` and `source` filters as a (too?) early optimization.

Is there some other rationale behind the existence of those two fields at the subscription API?

**Comment by duglin** [comment]
I believe the way to view this is that often there's a 2-phase bit of processing around subscriptions. The first step is to identify the event stream to which you want to get events - or which event producer are you interested in. "source" and "types" are used to decide this part of the subscription.  Then, once you have a stream of events you can then choose to subset that stream and that's were the filter comes into play. And sometimes that filtering can be done by a completely separate component from the entity producing the stream. 

While it's true that you could possibly write it all into a single filter expression, splitting these two aspects could then become very challenging - especially if the expression did some interesting things like combined checking 'source/type' with simple metadata on the events. So it made more sense to make the split more formal.

Having said that, I think it's easy to see why mixing 'source' and 'filter' would be the more problematic case, but does "type" fall into that same category where it would influence the component we talk to get a stream of events? I can't say for sure... anyone else?  Maybe thinking of it as 'create' vs 'delete' could be a big decision point.  Maybe?

But @clemensv - wanna chime in here?

**Comment by clemensv** [comment]
Doug explains that correctly. We want filtering to be as cheap as possible to execute; source and type are the most common criteria and therefore worth "hard-wiring" before you need to deal with filter expressions, which are usually more complex.

**Comment by odacremolbap** [comment]
Thanks both for clarifying, I'm closing this issue.
