### ISSUE TITLE
Issues with discovery

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#863]
WIP

https://github.com/cloudevents/spec/blob/master/discovery.md#get-services
- [ ] `Any Service previously returned to a client that does not appear in this result can be assumed to be no longer available.` I think this needs to be limited to just unfiltered queries since a missing entry from a filtered set could mean that it was deleted or that the filtered field changed.
- [ ] `Discovery endpoints MUST support filtering with the following attributes and MUST reject any unsupported filters. ` we should probably say what the HTTP response code is.
- [x] is Epoch allowed to be a negative int?
- [x] "name" must be non-empty string
- [x] typo: dataschama

**Comment by clemensv** [comment]
The CRUD model of the Discovery API needs work.

* On the "services" collection, you can POST a list of services, but no single service. The typical pattern is to add a single item with a 201+Location return code
* On the "services/{id}" node, you can't PUT for an update. POST is not the right choice here.
* On the "services/{id}" node, you need to construct a payload to DELETE. That is clunky and there should be a query parameter option.
* Bulk delete is a potential source of pain

**Comment by duglin** [comment]
Moved to: https://github.com/xregistry/spec/issues/8
