### ISSUE TITLE
Events in the Actor Model world

### ISSUE THREAD

**Issue by rogeralsing** [cloudevents/spec#87]
I'm trying to get what context this initiative is trying to cover.
I run the Proto.Actor project, cross platform actor framework (http://proto.actor)

For us, things like batching to increase throughput and reduce overall message size is important.
e.g. we buffer messages either until the buffer is full or deadline timeout and then compress the payload by replacing message names/namespaces with identifiers unique for the message batch.

We also heavily rely on things like location transparency, we have the concept of PID (process ID, copied from Erlang, ActorRef in Akka).

Are things like this taken into consideration when designing the spec?

At what level does the spec live, is it down to the raw bits and bytes serialization level?
Or is it more of a checklist that applies above this?
e.g. you can be cloudevent compatible while using either JSON or ProtoBuf or other serializers?

**Comment by duglin** [comment]
@rogeralsing see: https://github.com/cloudevents/spec/pull/84
If adopted it'll mean that, for now, the mechanisms by which we transport events over the wire are not yet covered by the spec.  Does that help?

**Comment by duglin** [comment]
@rogeralsing given the change we've made to the spec, is this still an issue or can we close this?

**Comment by duglin** [comment]
@rogeralsing lots of serializations can be written for CloudEvents. I would like to close this but I think the question of whether we should deal with batching is one that might be worth discussion - going to tag this as v1.0

**Comment by duglin** [comment]
Related to:https://github.com/cloudevents/spec/issues/72 ?

**Comment by rogeralsing** [comment]
Potentially, but I read #72 as an 1-1 layering/wrapping of messages.
In our case, and I assume this is true for other high throughput messaging aswell.
we map multiple in process messages targeting the same remote node into a single batch envelope.
which is later unpacked by the receiving node, redistributing each individual message to the individual receivers on that node.

```
 Actor1       Actor2      Actor3
    |           |            |
    v           v            v
Many messages targeting actors on Node2

--------------Node1------------------
                |
                |
                v
         Batch Envelope
                |
                |
                v
--------------Node2------------------

          Many messages 
    |           |           |
    v           v            v
 Actor4       Actor5      Actor6
```

**Comment by duglin** [comment]
During the 6/15 f2f we agreed to close this for now and if it pops up as a requirement later on then we can reopen it.
