### ISSUE TITLE
  [Subscription API] invalid JSON in example

### ISSUE THREAD

**Issue by adgerrits** [cloudevents/spec#871]
In the [subscription API](https://github.com/cloudevents/spec/blob/master/subscriptions-api.md) the example JSON serialization of a subscription resource contains invalid JSON. The field 'sink' is incorrectly followed by a comma. I suppose it is meant to be placed,  in line with the specification, above 'protocol' (after which the final comma has to be removed).

**Comment by duglin** [comment]
Fixed this as part of https://github.com/cloudevents/spec/pull/893 since it's trivial
Thanks for letting us know
