### ISSUE TITLE
[Subscription API] Use of name/value pairs

### ISSUE THREAD

**Issue by adgerrits** [cloudevents/spec#873]
Subscription API describes the use of filtering via expressions. The default filter dialects say: 
> "Use of this MUST include exactly one nested property, where the key is the name of the CloudEvents attribute to be matched, and its value is the String value to use in the comparison." 

[Types](https://github.com/cloudevents/spec/blob/master/subscriptions-api.md#types) is an array so there you can use multiple values to be matched but will it (ever?) be possible to use an (extension) attribute with name/value pairs (e.g. {"organization" : "x", "department" : "y"}).
It would make filtering functionally (much) richer, but also provide extra complexity, which is not desirable in view of '[We want filtering to be as cheap as possible to execute](https://github.com/cloudevents/spec/issues/859#issuecomment-908329471)'.

**Comment by duglin** [comment]
I believe the intent was to allow for CE extension attributes to be included in there.  @clemensv ?
If so, we should probably make that clear in the spec.

**Comment by duglin** [comment]
@clemensv any thoughts?

**Comment by jskeet** [comment]
I note we removed the notion of a "map" CloudEvent attribute type a while ago - I'd be reluctant to see if come back via the back door here.

**Comment by clemensv** [comment]
An extension attribute with key/value pairs implies that there is a particular encoding to express that data structure. We don't have such an encoding for extension attributes that the spec knows of. It only knows strings, not JSON. You can use filters against extensions, but the filters cannot assume some particular encoded structure.

**Comment by duglin** [comment]
going to close this as I think it's been answered. Feel free to ping us if we need to reopen it

**Comment by adgerrits** [comment]
Thank you for the clear answer
