### ISSUE TITLE
JSON format implicit datacontenttype is asymmetrical

### ISSUE THREAD

**Issue by jskeet** [cloudevents/spec#880]
Just trying to write tests for the clarifications in #861, and I think there's an asymmetry:

- When deserializing a CloudEvent, if `datacontenttype` isn't specified it defaults to `application/json`
- When [serializing a CloudEvent](https://github.com/cloudevents/spec/blob/master/json-format.md#311-payload-serialization), there's no such defaulting that I can see

I *suspect* that we should say that if `datacontenttype` is missing when serializing - and if `data` is present - it should default to `application/json`, so the payload should be serialized as JSON.

I'll proceed along those lines, and we can discuss whether that was actually the intention - and I can put together a PR to clarify the spec if so.

**Comment by jskeet** [comment]
(I may well have just missed it, of course...)

cc @dazuma

**Comment by jskeet** [comment]
(Just in case I forget - Clemens pointed out that the core spec does say that an event using JSON format can be implicitly application/json. So I'll just make that absolutely concrete in 3.1.1)

**Comment by duglin** [comment]
@jskeet can we close this now?

**Comment by jskeet** [comment]
Yup!
