### ISSUE TITLE
Possibly remove the Open Source page?

### ISSUE THREAD

**Issue by jskeet** [cloudevents/spec#886]
The [Open Source](https://github.com/cloudevents/spec/blob/v1.0.1/community/open-source.md) page is doing more harm than good at the moment, I believe:

- It's breaking the build at the moment due to a stale link
- Most of the links are to projects that haven't been updated for a long time (e.g. since 2018 or 2019) - I suspect most don't support CE 1.0
- The still-active ones tend to be large projects where the CloudEvents aspect is only a small part (and may well still be stale, e.g. for Gloo, the [Gloo SDK](https://github.com/solo-io/gloo-sdk-go) supports CloudEvents, but hasn't been updated since 2018)
- Some projects are effectively alternative SDKs (e.g. [cloudevent.js](https://github.com/smartiniOnGitHub/cloudevent.js)); we should consider carefully how we want to talk about multiple SDKs for a single language, but I don't believe that listing alternative SDKs here without any other guidance is a good idea

**Comment by duglin** [comment]
I believe we can close this due to https://github.com/cloudevents/spec/pull/888 being merged.
Ping if I'm mistaken.
