### ISSUE TITLE
[Schema registry] support for schema references

### ISSUE THREAD

**Issue by harikrishnakanchi** [cloudevents/spec#887]
Hi,

I was going through existing schema registry spec. Really thankful for putting together spec around schema registry. Mentioned APIs in spec are sufficient for fully contained schemas. Is there any plans to include references?

Context: Single protobuf schema might contain multiple dependencies. One of the ways to solve this is, we can pack all dependencies in `google.protobuf.FileDescritporSet` and serve it as fully contained schema. But Users/Organizations tend to manage protobuf schema in single repo (eg: [googleapis](https://github.com/googleapis/googleapis)) which can have huge number of schemas. If user needs single schema we end up sending whole FileDescriptorSet which contain other schemas as well, this can be problem if FileDescriptorSet size is huge.

If references are supported, then it will help to link schema dependencies, then implementations can download only dependent proto schemas.

Created this issue to start off the discussion for this.

**Comment by duglin** [comment]
Closing - please ping if we need to reopen
