### ISSUE TITLE
[CESQL] MUST requirement to support CESQL?

### ISSUE THREAD

**Issue by deissnerk** [cloudevents/spec#919]
The subscription spec [states](https://github.com/cloudevents/spec/blob/main/subscriptions/spec.md#3241-filter-dialects) that among others CESQL MUST be supported by all implementations:

> This specification defines the following 7 filter dialects that all implementations MUST support:

Is this really what we intend? CESQL is complex to implement and potentially expensive at runtime. I suggest to make it optional.

**Comment by loopingz** [comment]
Yes my understanding is it was supposed to be optional

**Comment by deissnerk** [comment]
Solved by #1228
