### ISSUE TITLE
Vote: Protobuf v1.0 release

### ISSUE THREAD

**Issue by duglin** [cloudevents/spec#939]
The WG agreed to start a vote to release the protobuf spec [1] as a v1.0 version.

The vote will stay open for 1 week and end at the start of next week's call (Thursday 12pm ET).

Eligible voters are: Chainguard, Google, IBM/RedHat, Intel, Microsoft, SAP, Splunk, Erik Erikson, Tommy Chung

You may vote asynchronously by adding a comment to this issue or on the call next week.

If anyone (voting member or not) has any comments (for or against) the release of the new spec please feel free to add a comment to this issue.

If the vote passes then the WG has also agreed to create a v1.0.2 of the CloudEvents specifications (based on v1.0.1) to include this new spec - and that vote will start next week.

[1] https://github.com/cloudevents/spec/blob/main/cloudevents/formats/protobuf-format.md

**Comment by jroper** [comment]
I'm not a voting member but I'm for it.

**Comment by stevenhartley** [comment]
Same here!

**Comment by jskeet** [comment]
Unsurprisingly, I vote in favour :)

**Comment by lance** [comment]
:+1:

**Comment by n3wscott** [comment]
👍

**Comment by duglin** [comment]
Finally vote:
Yes: Chainguard, Google, IBM/RedHat, Erik Erikson, Tommy Chung
No: none
Abstain: Microsoft, SAP, Splunk
Not present: Intel

The vote passes. A new release/vote will be started soon.
