### ISSUE TITLE
Why Attribute Naming not support camel-casing

### ISSUE THREAD

**Issue by hxnan** [cloudevents/spec#943]
```
Attribute Naming Convention
The CloudEvents specifications define mappings to various protocols and encodings, and the accompanying CloudEvents SDK targets various runtimes and languages. Some of these treat metadata elements as case-sensitive while others do not, and a single CloudEvent might be routed via multiple hops that involve a mix of protocols, encodings, and runtimes. Therefore, this specification limits the available character set of all attributes such that case-sensitivity issues or clashes with the permissible character set for identifiers in common languages are prevented.

CloudEvents attribute names MUST consist of lower-case letters ('a' to 'z') or digits ('0' to '9') from the ASCII character set. Attribute names SHOULD be descriptive and terse and SHOULD NOT exceed 20 characters in length.
```

I have many business message with dash-sepreator or camel-casing attribute name.

message( attribute name: dash-sepreator ) --> cloudevent ( attribute name:  all lower-case ) -- not reversible -->message( attribute name: dash-sepreator )

The only way to work around this issue is replace - with number 1, but than seems ugly.

**Comment by duglin** [comment]
You quoted the text in the spec as to why we did it. While the authors understood the possible pains this might cause, the desire for interoperability and compatibility across the various protocols, transports and languages overrode those concerns.

Just a wild idea if you really want to do some kind transformation... you could "escape" all other chars. For example: abc-def could be represented as `abc02ddef`, where `2d` is the ascii hex code for `-`. You'd of course need to escape `0` as `030` too, but at least you won't lose anything.

**Comment by n3wscott** [comment]
The fields inside the data payload are allowed to have dash-case and camelCased names. This limitation is only for the top level attributes (they would be extensions to the spec) on the envelope. 

So you will need to translate routing fields to a compatible format for cloudevents attributes. If you don't intent to route on these fields, then no change on your side is required.
