### ISSUE TITLE
Details regarding Extension Attributes w.r.t Binary Mode and Structured Mode

### ISSUE THREAD

**Issue by ankit6193** [cloudevents/spec#953]
We have allot of optional attributes for our service wanted to know what is the spec for naming convention to differentiate with Cloud Event attributes 

For. e.g. In binary mode headers have ce-specversion and our optional attributes is ce-optionalattribute. Can we change these naming convention according to our usecase like xyz-optionalattribute instead. 

Also in our payload we dont differentiate cloud event attribute with our attributes. Does this need to be done ? 

If there is any documentation for these it will help .

**Comment by JemDay** [comment]
HI @ankit6193,

As it stands today there isn't any prescribed naming convention for custom extensions (which is what I believe we're talking about here).

My suggestion is that you prefix all of your (extension) attribute names in a common way to reduce the chances of clashing with some other organization - for example internally we prefix with our stock ticker symbol `pypl`.

So (In our situation) `customattribute` becomes `pyplcustomattribute` which then enables it to flow over all transports using a binary or structured mode without information loss when following the standards and/or SDKs

Hope this helps .. ping me if not ;-)

**Comment by duglin** [comment]
To be clear though, you'd still need the "ce-" prefix in some cases, like HTTP binary mode.

I think we can close this one. Let me know if we need to reopen it.
