### ISSUE TITLE
GitHub branching/versioning proposal

### ISSUE THREAD

**Issue by jskeet** [cloudevents/spec#954]
(I can make this a Google doc or a PR if that would be more useful.)

# Issue

Our current GitHub branching scheme is confusing, and sometimes requires changes to be made in multiple places.

# Proposal

- Change to a new default "stable" branch
- Create a new "working" branch; this is the *only* branch that new commits are added to via PRs
- Use tags (instead of branches) to specify the commits at which specific versions are created
- "Release a new version" process becomes:
  - Update the "working" branch to refer to spec locations by new tagged URLs, and update a history file. (Note: the tags won't actually exist at that point...)
  - Create the tag to point to the latest commit on "working"
  - Catch up "stable" to match "working"

(I'm happy to bike-shed on the branch names, e.g. "development", "work", "unstable" etc.)

## Benefits

- Only two branches to work with - one effectively read-only for consumers, and one for the working group to work on
- Still easy to refer to a specific version via tag
- We can keep the history file up to date as we go (or at least periodically, before a release) which will make it immediately clear what changes aren't yet released

## Drawbacks

- Need to work out how to migrate existing branches. Probably just create tags for them but drop them as branches. I don't *think* GitHub has a problem with that, although it's a little odd.
- This assumes a single version number, and that when we want to "do a release" that everything is still stable. If there are in-progress changes to the JSON format that aren't stable yet, we can't easily release changes to the Protobuf format.
- The "single version number" assumption bites particularly hard when Discovery etc eventually become stable. Does everything in the working branch have to be "ready to become part of a stable release at any time"? What does the tag look like for Discovery 1.0? (This is already an issue for the current branching scheme though, at least to some extent.)

**Comment by jskeet** [comment]
Notes from the meeting on 2022-02-17:

- Proposal as written doesn't quite work as the versioned branches don't contain any "not-yet-stable" specs (e.g. Discovery)
  - To keep a completely linear history, we'd need to move away from that
- Releases should be immutable; at the moment they're not
  - This proposal represents a change: there's no concept of "make a bug fix to 1.0.1" - we'd cut a 1.0.2, or sit on the change if it's just a trivial typo
- Could potentially include not-yet-stable specs in the stable branch, but with README.md in each directory making the status clear
- The default branch being a release branch (or, with the above proposal, the stable branch) is somewhat annoying for GitHub flow

# New proposal

- *Just one branch*
- We put the stable specs on the web site as the primary place we expect people to read them
- We use tags for releases (and still have links in GitHub so it's easy to browse them if you want to do so there)
- No bug fixes for older versions (as above, we can't "fix 1.0.1" - you just focus on the latest)
- When v2 hoves into view, we probably create a new branch for that, before it's stable - allowing us to still bugfix v1

**Comment by duglin** [comment]
To be clear... the newer (unreleased specs, e.g. Discovery) will be visible in our single branch (`main`) in github but will not be visible on the cloudevents.io web site until we explicitly do so (e.g. via a formal release).

@n3wscott is working on the website infra to support this.

**Comment by duglin** [comment]
@jskeet can we close this one?

**Comment by jskeet** [comment]
Yes, I believe so. Closing.
