### ISSUE TITLE
Reason behind 20 character limit suggestion for attributes?

### ISSUE THREAD

**Issue by morlando016** [cloudevents/spec#955]
Hello, I was wondering why 20 was chosen as the recommended character limit for attributes? I see its not a hard and fast rule but was curious how this number came to be. Currently looking at my implementation I see I've exceeded the limit for some attributes but I don't understand the pros/cons of this beyond just trying to keep the whole message small vs more descriptive.

**Comment by duglin** [comment]
If I remember correctly, it was done to ensure maximum interop across the largest number of protocols and formats. But if you know you're only using ones that can deal with longer ones... then it's ok.

**Comment by morlando016** [comment]
Ok thanks! Would be helpful if some more info explaining the decision was included in the spec. I wasn't sure if it was arbitrary or not.

**Comment by duglin** [comment]
Done: https://github.com/cloudevents/spec/pull/962

**Comment by morlando016** [comment]
Thanks!
