### ISSUE TITLE
[Subscription] New feature requirements: Event Lane

### ISSUE THREAD

**Issue by ifplusor** [cloudevents/spec#967]
For topic-based messaging middleware, such as Apache Kafka, we can store events in separate topics to achieve isolation. But there is not a mechanism to represent event lanes, or another names for this, in Subscription API. I think the mechanism is necessary to eventing middleware.

**Comment by deissnerk** [comment]
@ifplusor This sounds very interesting. Could you elaborate a bit more on the scenarios you have in mind? Is it about consuming from a topic or queue?

The subscription spec mentions [Native Subscription Management Mechanisms](https://github.com/cloudevents/spec/blob/main/subscriptions/spec.md#31-native-subscription-management-mechanisms).  As far as I know, these native subscription mechanisms are not (yet) represented in the discovery spec, though. 

@clemensv This sounds a lot like your ideas around consumption endpoints. What do you think?

**Comment by ifplusor** [comment]
@deissnerk

My team is developing an Eventing middleware that supports CloudEvents natively. As a platform product, whether for achieving multi-tenancy or ensuring filter performance, it is obvious that we need a way to isolate events. In order to provide a single endpoint of control plane, we need a centralized Subscription Manager instead of opening a port for each Lane.

The concept of Lane can be analogized to Topic in Kafka and to Broker in Knative. In Kafka, Consumer is associated with Topic; in Knative, Trigger is associated with Broker. However, in the current Subscription API, the Subscription Manager is directly implemented on the Producer, and the Producer will directly deliver the Event to the Consumer based on the Subscription. There is no way for Subscription to be associated with Lane, this will restrict the works an Intermediary can do.

https://github.com/cloudevents/spec/blob/284e82c60e8f9e51bf9f910823e43ac20976d2b0/subscriptions/spec.md?plain=1#L1009-L1019

The CloudEvents specification has been well practiced in the end-to-end scenario. It would be great if better support for the development of middleware was provided.

**Comment by deissnerk** [comment]
@ifplusor I'm actually in a similar situation regarding the work focus on infrastructure. That's why I'm asking a bit more about your scenarios. 
> However, in the current Subscription API, the Subscription Manager is directly implemented on the Producer, and the Producer will directly deliver the Event to the Consumer based on the Subscription.

This might be a misunderstanding. In fact the relation between _Subscription Manager_ and _Producer_ is not defined as part of the spec. You don't have to reserve one port per tenant/topic on your Subscription Manager. Another approach could be a path segment. Discovery could then point to subscription URLs like `https://subscription.manager/tenant1` and `https://subscription.manager/tenant2`. Another approach can be to use the hostname. 

Nevertheless @clemensv and I have been discussing use cases where two infrastructures exchange events and need means to create/delete channels between each other. As a result @clemensv created [this issue](https://github.com/cloudevents/spec/issues/830) which focuses on channels for the event transfer as such.

I also did a presentation in the regular group call last year that touches some of these topics. In that presentation I was referring to _Scopes_. The recording can be found [here](https://youtu.be/IRGlNtWAYEY?t=1076).

So there is also some activity with more infrastructure focus going on, and you are welcome to share more of your thoughts.

**Comment by ifplusor** [comment]
@deissnerk

I see what you mean, but sentences below mislead me. 

https://github.com/cloudevents/spec/blob/284e82c60e8f9e51bf9f910823e43ac20976d2b0/subscriptions/spec.md?plain=1#L894-L899

And in current [subscriptions-openapi.yaml](https://github.com/cloudevents/spec/blob/284e82c60e8f9e51bf9f910823e43ac20976d2b0/subscriptions/subscriptions-openapi.yaml), the `path` of operations is well defined, so `hostname` is the only way. But I think it is not a good way, because every `hostname` will expose a new endport of the _Subscription Manager_.

Our implementation wants to reuse the _Subscription Object_ internally, and considers providing a declarative API, so I tend to add an optional extension attribute to the _Subscription Object_.

**Comment by deissnerk** [comment]
@ifplusor Looking at the [OpenAPI spec](https://swagger.io/specification/), I see the following description for `path`:
> A relative path to an individual endpoint. The field name MUST begin with a forward slash (/). The path is appended (no relative URL resolution) to the expanded URL from the [Server Object](https://swagger.io/specification/#server-object)'s url field in order to construct the full URL. [Path templating](https://swagger.io/specification/#path-templating) is allowed.

I'm not an OpenAPI expert, but this looks to me like server URLs as I described above would be fine. It is misleading that the path in OpenAPI always starts with a `/`, as this makes it look like a relative URI reference with an absolute path. 

**Regarding hostname:**
It is possible to define a wildcard DNS entry. The HTTP server can then evaluate the [host header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html). 

Having said all this, I understand your requirement. I'm just not completely convinced a specific attribute is needed to solve it, as the mechanisms of the underlying protocol provide some means. An attribute would have the advantage that it could be the same, even if we define the subscription API for protocols like AMQP.  

If we discuss it in the group, I would like to see it combined with the discussion of #830.

**Comment by ifplusor** [comment]
@deissnerk You are right. Both `path` and `hostname` will work well, and its good way for open API.

When using these ways, a new server definition with variables needs to be introduced.

```yaml
servers:
- url: https://server.example.com/v0.1/{scope}
  description: specify scope in path
  variables:
    scope:
      default: demo
      description: event scope
- url: https://{scope}.server.example.com/v0.1
  description: specify scope in hostname
  variables:
    scope:
      default: demo
      description: event scope
```

**Comment by ifplusor** [comment]
I will merge this session into #830 later.
