### ISSUE TITLE
Improve CLOMonitor score (CNCF Project Requirements)

### ISSUE THREAD

**Issue by jeefy** [cloudevents/spec#969]
Hello! 

The CNCF is starting to use a [new tool](https://clomonitor.io/projects/cloudevents/cloudevents) to track project requirements and best practices.

Since the Spec repo is the "primary" repo defined for the project, there are a few things that would be awesome to add in to it:
- [ ] Adopters
- [ ] Changelog
- [ ] Code of Conduct
- [ ] Contributing guide
- [ ] Governance documentation
- [ ] Roadmap
- [ ] Security policies

In the SDK repos, they should also have OWNERS files. 

The details/definitions for these things should be laid out in the CLOMonitor tool, but please reach out if you have any questions or need examples for any of these. :) Also if you'd like this broken up into multiple issues I'm happy to knock that out as well.

Thanks!

**Comment by tomkerkhove** [comment]
> * [ ]  Code of Conduct
> * [ ]  Contributing guide
> * [ ]  Governance documentation
> * [ ]  Security policies

For this content, moving it to `cloudevents/.github` would be recommended since that's a magical repo that will add all the files to the other repos.

**Comment by duglin** [comment]
If we already have these files but in a subdir is there a way to tell the tool?

**Comment by tomkerkhove** [comment]
Not for now but they are very responsive on issues.

Having a pointer from readme is also ok.

That's what we do for KEDA.

**Comment by duglin** [comment]
@jeefy CloudEvents I think the category for CE would be better under "Serverless" instead of "App Def".
Can we fix fix that?
![image](https://user-images.githubusercontent.com/1944671/158585634-352eb4ca-bf53-46dc-b827-d53b53258505.png)

Opened: https://github.com/cncf/clomonitor/issues/183

**Comment by duglin** [comment]
> Having a pointer from readme is also ok.
> That's what we do for KEDA.

We do that for some of ours too, but I don't think the look detects those yet.

**Comment by duglin** [comment]
@jeefy got any info on what "Security policies" refers to?

**Comment by duglin** [comment]
For reference, more info on how the tool does its checks: https://github.com/cncf/clomonitor/blob/main/docs/checks.md

**Comment by jeefy** [comment]
Yeah, it's primarily "How should you disclose a Security issue with us?" and "How will we handle a new Security issue?"

Here are a couple examples that you could reference:
https://github.com/argoproj/argo-workflows/blob/master/SECURITY.md
https://github.com/prometheus/prometheus/blob/main/SECURITY.md

**Comment by duglin** [comment]
Closing since we're all 100% compliant now
