### ISSUE TITLE
[Docs] Translate cloudevents/spec/blob/main/cloudevents/spec.md to zh-CN

### ISSUE THREAD

**Issue by JieDing** [cloudevents/spec#977]
**Document to translate:**

https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md

**Translation target:**

https://github.com/cloudevents/spec/blob/main/cloudevents/languages/zh-CN/spec.md

Translators who accept the task SHOULD follow [instructions for CloudEvents translation](https://github.com/cloudevents/spec/blob/main/languages/languages-spec.md).

**Comment by JieDing** [comment]
This translation needs to be updated as the English doc has changed.

**Comment by sunshengjing** [comment]
@duglin pls, assign this task to me, thanks.

**Comment by sunshengjing** [comment]
@duglin @JieDing  translation is done, please review. thankls

**Comment by JieDing** [comment]
@sunshengjing Cool, I'll review it and leave my feedbacks later

**Comment by JieDing** [comment]
The related-PR is merged.
