### ISSUE TITLE
[Docs] Translate cloudevents/spec/blob/main/cloudevents/SDK.md to zh-CN

### ISSUE THREAD

**Issue by JieDing** [cloudevents/spec#978]
Document to translate:

https://github.com/cloudevents/spec/blob/main/cloudevents/SDK.md

Translation target:

https://github.com/cloudevents/spec/blob/main/cloudevents/languages/zh-CN/SDK.md

Translators who accept the task SHOULD follow [instructions for CloudEvents translation](https://github.com/cloudevents/spec/blob/main/languages/languages-spec.md).

**Comment by wenfengwang** [comment]
@JieDing  Could assign this issue to me?

**Comment by JieDing** [comment]
> @JieDing Could assign this issue to me?

Please wait for the maintainer to do that thx.

**Comment by JieDing** [comment]
@wenfengwang After we re-org the repo structure, we noticed that the translation target is complete and up-to-date, so this issue will be closed.
Thanks a ton for your contribution, you can choose other translation issues to contribute if you want.
