### ISSUE TITLE
[Docs] Translate cloudevents/spec/blob/main/cloudevents/adapters.md to zh-CN

### ISSUE THREAD

**Issue by JieDing** [cloudevents/spec#979]
Document to translate:

https://github.com/cloudevents/spec/blob/main/cloudevents/adapters.md

Translation target:

https://github.com/cloudevents/spec/blob/main/cloudevents/languages/zh-CN/adapters.md

Translators who accept the task SHOULD follow [instructions for CloudEvents translation](https://github.com/cloudevents/spec/blob/main/languages/languages-spec.md).

**Comment by wangwei538** [comment]
@JieDing please assign it to me, thanks

**Comment by JieDing** [comment]
@wangwei538 After we re-org the repo structure, we noticed that the translation target is complete and up-to-date, so this issue will be closed.
Thanks a ton for your contribution, you can choose other translation issues to contribute if you want.
