### ISSUE TITLE
[Docs] Translate cloudevents/spec/blob/main/cloudevents/documented-extensions.md to zh-CN

### ISSUE THREAD

**Issue by JieDing** [cloudevents/spec#980]
Document to translate:

https://github.com/cloudevents/spec/blob/main/cloudevents/documented-extensions.md

Translation target:

https://github.com/cloudevents/spec/blob/main/cloudevents/languages/zh-CN/documented-extensions.md

Translators who accept the task SHOULD follow [instructions for CloudEvents translation](https://github.com/cloudevents/spec/blob/main/languages/languages-spec.md).

**Comment by xiaoduo** [comment]
I can this one, please assign it to me, thanks.

**Comment by JieDing** [comment]
@xiaoduo After we re-org the repo structure, we noticed that the translation target is complete and up-to-date, so this issue will be closed.
Thanks a ton for your contribution, you can choose other translation issues to contribute if you want.
