### ISSUE TITLE
[Docs] Translate cloudevents/spec/blob/main/cloudevents/http-webhook.md to zh-CN

### ISSUE THREAD

**Issue by JieDing** [cloudevents/spec#981]
Document to translate:

https://github.com/cloudevents/spec/blob/main/cloudevents/http-webhook.md

Translation target:

https://github.com/cloudevents/spec/blob/main/cloudevents/languages/zh-CN/http-webhook.md

Translators who accept the task SHOULD follow [instructions for CloudEvents translation](https://github.com/cloudevents/spec/blob/main/languages/languages-spec.md).

**Comment by xdlbdy** [comment]
pls assign it to me @JieDing

**Comment by JieDing** [comment]
I re-organized the languages structure, plz rebase your work and make sure your translation is up-to-date. @xdlbdy

**Comment by xdlbdy** [comment]
I have done, pls review @JieDing

**Comment by JieDing** [comment]
Ok, I'll review it and leave my feedbacks later

**Comment by JieDing** [comment]
The related-PR is merged.
