### ISSUE TITLE
[Docs] Translate cloudevents/spec/blob/main/cloudevents/primer.md to zh-CN

### ISSUE THREAD

**Issue by JieDing** [cloudevents/spec#982]
Document to translate:

https://github.com/cloudevents/spec/blob/main/cloudevents/primer.md

Translation target:

https://github.com/cloudevents/spec/blob/main/cloudevents/languages/zh-CN/primer.md

Translators who accept the task SHOULD follow [instructions for CloudEvents translation](https://github.com/cloudevents/spec/blob/main/languages/languages-spec.md).

**Comment by JieDing** [comment]
This translation needs to be updated as the English doc has changed.

**Comment by sunshengjing** [comment]
@duglin @JieDing pls, assign this task to me. thanks a lot.

**Comment by JieDing** [comment]
The related-PR is merged.
