### ISSUE TITLE
Reference Implementation Proposal - CloudEvents Transform Library

### ISSUE THREAD

**Issue by ac360** [cloudevents/spec#99]
**Objectives**

* Create a simple reference implementation for CloudEvents.
* Create a tool that incentivizes early adoption of the CloudEvents specification.

**Overview**

This proposal is for a library that transforms common events (e.g. AWS S3 Object Created, webhooks) into the CloudEvents format.

The library could be used by publishers, middleware and subscribers.  In the case of serverless, the library could be used at the beginning of serverless function handlers, so the user only needs to work with the CloudEvents format.

*Example:*

- An "AWS S3 Object Created" event is published on AWS.
- An AWS Lambda function that is subscribed to that event runs.
- The initial code in the AWS Lambda Function does the transformation.
- The user doesn't have to worry about proprietary AWS event formats.

```javascript
// Node.js Example

// Load the cloudevents Node.js library
var cloudevents = require('cloudevents')

module.exports = function(event, context, callback) {
    
    // Perform transformation of AWS event format into CloudEvents event format
    event = cloudevents.transform(event)
    
    // Write your business logic around the familiar cloudevents format
    return callback(null, 'success')
}
```

**V.0 Specs**

* Language agnostic transformation templates should be a major focus of this effort.  These can be re-used by cloudevents libraries written in multiple languages.  Here is a quick (non-working) example of a template in JSON to communicate the general idea:

```JSON
// AWS S3 Object Created > CloudEvents
// Keys are CloudEvents properties and values are provided by the original event format

{
    "event-type": "aws.s3.(${eventName}='ObjectCreated:Put'?'object.created')",
    "event-type-version": "${eventVersion}",
    "data": "${s3}"
}
```

* Transformation templates should offer basic conditional logic.
* Transformation templates should be loaded selectively by the user, to avoid loading irrelevant ones.

**Future**

* This can be incorporated into a standard FaaS signatures, so that this transformation is always performed.

**Comment by clemensv** [comment]
In my view, the point of the WG effort is for (cloud-) platform providers to support a standardized event format natively. Such a project as a WG sanctioned activity would be counterproductive towards that goal because it removes the implementation incentive.

**Comment by ac360** [comment]
@clemensv I understand your point.  Though, consider:

- It could take a while for major platform providers to support CloudEvents.
- This allows use of CloudEvents with major platforms today, which will encourage growth of the ecosystem.  Growth of the ecosystem then pressures platform providers to make the change faster, or they risk falling behind the market.

**Comment by Vlaaaaaaad** [comment]
I think this is parallel to the SDK work. The transformation is defined somewhere and then all the SDKs implement it. Platform providers **should** do this... but it will take a ton until native support for CloudEvents is added and a transform library is a perfect tool until then.

I too was considering doing something similar to this as I totally missed this issue. There are issues that have to be discussed( such as provider-specific properties and auth), but I do believe that the discussion should happen in the main group.

**Comment by ac360** [comment]
@duglin Sure, we will work on this via the SDK.

**Comment by duglin** [comment]
I'm going to suggest that we close this one since our SDK work should cover it. Please speak up if you think otherwise.

**Comment by duglin** [comment]
I'm going to close this one given @ac360's comment: https://github.com/cloudevents/spec/issues/99#issuecomment-434271230
